Repository intershop/intershop-pwa, pull requests merged in 2019-11, with the labels that each got.

#3 fix: update dependencies with vulnerabilities in sub projects
  e2e/package-lock.json
  schematics/package-lock.json
  tslint-rules/package-lock.json
Labels: dependencies

#9 fix: quote request notification messages improvements (ISREST-880)
  src/app/extensions/quoting/shared/product/containers/product-add-to-quote-dialog/product-add-to-quote-dialog.container.html
  src/app/extensions/quoting/shared/product/containers/product-add-to-quote-dialog/product-add-to-quote-dialog.container.ts
  src/app/extensions/quoting/shared/quote/components/quote-edit/quote-edit.component.html
  src/app/extensions/quoting/shared/quote/components/quote-edit/quote-edit.component.spec.ts
  src/app/extensions/quoting/shared/quote/components/quote-edit/quote-edit.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug

#12 fix: hide compare link in mobile view for disabled compare feature (ISREST-928)
  src/app/shell/header/components/user-information-mobile/user-information-mobile.component.html
  src/app/shell/header/components/user-information-mobile/user-information-mobile.component.spec.ts
Labels: bug

#13 feat: add page meta information for SEO with ngx-meta (ISREST-913)
  package-lock.json
  package.json
  schematics/src/page/factory.js
  schematics/src/page/factory.ts
  src/app/core/extras.module.ts
  src/app/core/models/category/category.interface.ts
  src/app/core/models/category/category.mapper.ts
  src/app/core/models/category/category.model.ts
  src/app/core/models/product/product.interface.ts
  src/app/core/models/product/product.mapper.ts
  src/app/core/models/product/product.model.ts
  src/app/core/models/seo-attribute/seo-attribute.model.ts
  src/app/extensions/seo/seo.module.ts
  src/app/extensions/seo/store/seo-store.module.ts
  src/app/extensions/seo/store/seo/seo.actions.ts
  src/app/extensions/seo/store/seo/seo.effects.spec.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
  src/app/pages/app-routing.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement

#17 fix: production mode support for concardis credit card
  src/app/core/services/script-loader/script-loader.service.ts
  src/app/pages/checkout-payment/components/payment-concardis-creditcard/payment-concardis-creditcard.component.ts
Labels: bug

#22 feat: enable Intershop test payment methods for redirect before and after checkout (ISH creditCard and onlinePay)
  src/app/pages/checkout-payment/components/checkout-payment/checkout-payment.component.spec.ts
  src/app/pages/checkout-payment/components/checkout-payment/checkout-payment.component.ts
  src/environments/environment.model.ts
  src/environments/environment.ts
Labels: enhancement, feature

#23 chore: change recommended Visual Studio Code stylelint extension (#21)
  .vscode/extensions.json
Labels: dependencies

#26 fix: load basket products after merge basket
  src/app/core/store/checkout/basket/basket.effects.spec.ts
  src/app/core/store/checkout/basket/basket.effects.ts
  src/app/core/store/checkout/checkout-store.spec.ts
Labels: bug
