Repository intershop/intershop-pwa, pull requests merged in 2019-12, with the labels that each got.

#29 fix: chromium defer-load: directive only on block-elements
  src/app/pages/category/components/category-image/category-image.component.html
  src/app/shared/cms/components/cms-image/cms-image.component.html
  src/app/shared/cms/components/cms-image/cms-image.component.spec.ts
  src/app/shell/header/components/product-image/product-image.component.html
Labels: bug

#25 refactor: use ngrx/entity in quoting feature
  src/app/extensions/quoting/facades/quoting.facade.ts
  src/app/extensions/quoting/services/quote-request/quote-request.service.ts
  src/app/extensions/quoting/store/quote-request/quote-request.effects.ts
  src/app/extensions/quoting/store/quote-request/quote-request.reducer.spec.ts
  src/app/extensions/quoting/store/quote-request/quote-request.reducer.ts
  src/app/extensions/quoting/store/quote-request/quote-request.selectors.spec.ts
  src/app/extensions/quoting/store/quote-request/quote-request.selectors.ts
  src/app/extensions/quoting/store/quote/quote.effects.ts
  src/app/extensions/quoting/store/quote/quote.reducer.spec.ts
  src/app/extensions/quoting/store/quote/quote.reducer.ts
  src/app/extensions/quoting/store/quote/quote.selectors.spec.ts
  src/app/extensions/quoting/store/quote/quote.selectors.ts
Labels: enhancement

#36 fix: always write apiToken cookie as it is a functional cookie
  src/app/core/services/cookies/cookies.service.spec.ts
  src/app/core/services/cookies/cookies.service.ts
  src/app/core/store/restore/restore.effects.spec.ts
  src/app/core/store/restore/restore.effects.ts
Labels: bug

#8 feat: translations with links and callback (ISREST-915)
  src/app/core/directives/server-html.directive.ts
  src/app/pages/registration/components/registration-form/registration-form.component.html
  src/app/pages/registration/components/registration-form/registration-form.component.spec.ts
  src/app/pages/registration/components/registration-form/registration-form.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement

#37 fix: load quote-requests on login and page refresh
  src/app/extensions/quoting/store/quote-request/quote-request.effects.spec.ts
  src/app/extensions/quoting/store/quote-request/quote-request.effects.ts
Labels: bug

#55 fix: reopen the pwa in the user's language after coming back from payment redirect
  src/app/core/services/basket/basket-payment.service.spec.ts
  src/app/core/services/basket/basket-payment.service.ts
  src/app/core/services/order/order.service.spec.ts
  src/app/core/services/order/order.service.ts
Labels: bug

#70 fix: repair memoization of promotion selectors
  src/app/core/facades/shopping.facade.ts
  src/app/core/store/shopping/promotions/promotions.selectors.spec.ts
  src/app/core/store/shopping/promotions/promotions.selectors.ts
  src/app/shared/components/basket/basket-promotion/basket-promotion.component.spec.ts
  src/app/shared/components/product/product-promotion/product-promotion.component.spec.ts
Labels: bug

#71 feat: remove promotion code from basket
  src/app/core/facades/checkout.facade.ts
  src/app/core/services/basket/basket.service.spec.ts
  src/app/core/services/basket/basket.service.ts
  src/app/core/store/checkout/basket/basket-promotion-code.effects.spec.ts
  src/app/core/store/checkout/basket/basket-promotion-code.effects.ts
  src/app/core/store/checkout/basket/basket.actions.ts
  src/app/core/store/checkout/basket/basket.reducer.spec.ts
  src/app/core/store/checkout/basket/basket.reducer.ts
  src/app/shared/components/basket/basket-promotion/basket-promotion.component.html
  src/app/shared/components/basket/basket-promotion/basket-promotion.component.spec.ts
  src/app/shared/components/promotion/promotion-remove/promotion-remove.component.html
  src/app/shared/components/promotion/promotion-remove/promotion-remove.component.spec.ts
  src/app/shared/components/promotion/promotion-remove/promotion-remove.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/theme/global/promotions.scss
Labels: feature

#58 refactor: move methodes from product compare component to product helper
  src/app/core/models/product/product.helper.spec.ts
  src/app/core/models/product/product.helper.ts
  src/app/pages/compare/product-compare-list/product-compare-list.component.html
  src/app/pages/compare/product-compare-list/product-compare-list.component.spec.ts
  src/app/pages/compare/product-compare-list/product-compare-list.component.ts
  tslint.json
Labels: refactoring

#65 chore: replace mobile logos and icons with fitting ones for the logo
  src/assets/img/logo_192x192.png
  src/assets/img/logo_256x256.png
  src/assets/img/logo_384x384.png
  src/assets/img/logo_512x512.png
  src/assets/img/logo_apple_120x120.png
  src/assets/img/logo_apple_152x152.png
  src/assets/img/logo_apple_167x167.png
  src/assets/img/logo_apple_180x180.png
  src/assets/img/logo_mobile.png
  src/favicon.ico
Labels: enhancement
