Repository intershop/intershop-pwa, pull requests merged in 2020-01, with the labels that each got.

#45 feat: seo canonical link support
  src/app/core/models/seo-attribute/seo-attribute.model.ts
  src/app/core/pipes/product-route.pipe.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
Labels: feature

#76 prevent multiple html-ids in product-variation-select-component
  e2e/cypress/integration/pages/shopping/product-detail.page.ts
  e2e/cypress/integration/specs/checkout/cart-variation-handling.b2c.e2e-spec.ts
  src/app/shared/components/product/product-variation-select/product-variation-select.component.html
  src/app/shared/components/product/product-variation-select/product-variation-select.component.ts
Labels: bug

#66 feat: seo support for robots.txt
  .gitignore
  dist/.gitignore
  package-lock.json
  package.json
  server.ts
Labels: feature

#43 fix: account overview as root account page
  src/app/pages/account/account-navigation/account-navigation.component.html
  src/app/pages/account/account-navigation/account-navigation.component.ts
  src/app/pages/account/account-page.module.ts
  src/app/shared/components/common/breadcrumb/breadcrumb.component.html
Labels: bug

#83 refactor: use class MockDirective instead of MockComponent to mock directives i…
  src/app/app.component.spec.ts
  src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.spec.ts
  src/app/pages/account-order-history/account-order-history-page.component.spec.ts
  src/app/pages/account-overview/account-overview/account-overview.component.spec.ts
  src/app/pages/account-profile/account-profile/account-profile.component.spec.ts
  src/app/pages/forgot-password/request-reminder/request-reminder.component.spec.ts
  src/app/pages/forgot-password/update-password/update-password.component.spec.ts
  src/app/shared/address-forms/components/address-form-business/address-form-business.component.spec.ts
  src/app/shared/cms/components/cms-image-enhanced/cms-image-enhanced.component.spec.ts
  src/app/shared/components/product/product-promotion/product-promotion.component.spec.ts
  src/app/shared/components/promotion/promotion-details/promotion-details.component.spec.ts
  src/app/shared/forms/components/checkbox/checkbox.component.spec.ts
  src/app/shared/forms/components/input-birthday/input-birthday.component.spec.ts
  src/app/shared/forms/components/input/input.component.spec.ts
  src/app/shared/forms/components/select-address/select-address.component.spec.ts
  src/app/shared/forms/components/select-country/select-country.component.spec.ts
  src/app/shared/forms/components/select-language/select-language.component.spec.ts
  src/app/shared/forms/components/select-region/select-region.component.spec.ts
  src/app/shared/forms/components/select-security-question/select-security-question.component.spec.ts
  src/app/shared/forms/components/select-title/select-title.component.spec.ts
  src/app/shared/forms/components/select-year-month/select-year-month.component.spec.ts
  src/app/shared/forms/components/select/select.component.spec.ts
  src/app/shared/forms/components/textarea/textarea.component.spec.ts
  src/app/shell/footer/footer/footer.component.spec.ts
Labels: refactoring

#67 docs: documentation for pattern without containers
  README.md
  docs/README.md
  docs/migrations.md
  docs/project-structure.md
  docs/state-management.md
  docs/state-management.svg
Labels: documentation

#80 add anchor scrolling / fragment navigation for serverHtml content
  src/app/core/directives/server-html.directive.ts
Labels: enhancement

#86 chore: repair gitlab pipeline
  .gitlab-ci.yml
Labels: regression

#97 fix: missing route in user effects RouterTestingModule #95
  src/app/core/store/user/user.effects.spec.ts
Labels: bug
