Repository intershop/intershop-pwa, pull requests merged in 2020-06, with the labels that each got.

#277 fix: add to order template on product row
  src/app/shared/components/product/product-row/product-row.component.html
Labels: bug

#280 refactor: remove type from customer model
  src/app/core/models/customer/customer.interface.ts
  src/app/core/models/customer/customer.mapper.spec.ts
  src/app/core/models/customer/customer.mapper.ts
  src/app/core/models/customer/customer.model.ts
  src/app/core/services/payment/payment.service.spec.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/core/store/checkout/checkout-store.spec.ts
  src/app/core/store/user/user.effects.spec.ts
  src/app/core/store/user/user.reducer.spec.ts
  src/app/core/store/user/user.selectors.spec.ts
  src/app/extensions/order-templates/store/order-template/order-template.effects.spec.ts
  src/app/extensions/quoting/services/quote-request/quote-request.service.spec.ts
  src/app/extensions/quoting/services/quote/quote.service.spec.ts
  src/app/extensions/quoting/store/quote-request/quote-request.effects.spec.ts
  src/app/extensions/quoting/store/quote/quote.effects.spec.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.spec.ts
  src/app/pages/account-profile-company/account-profile-company-page.component.spec.ts
  src/app/pages/account-profile-company/account-profile-company/account-profile-company.component.spec.ts
  src/app/pages/account-profile/account-profile-page.component.spec.ts
  src/app/pages/account-profile/account-profile/account-profile.component.spec.ts
  src/app/pages/registration/registration-form/registration-form.component.ts
Labels: refactoring

#282 build: automatically retry universal tests
  e2e/test-universal.sh
Labels: regression

#287 build: ignore generated compodoc output
  .prettierignore
  .stylelintrc.json
Labels: regression

#288 chore: remove KB labels from documentation overview
  docs/README.md
  docs/check-kb-labels.js
Labels: documentation

#283 refactor: rename and correctly label action types
  src/app/core/interceptors/auth.interceptor.spec.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/customer-store.spec.ts
  src/app/core/store/customer/orders/orders.actions.ts
  src/app/core/store/customer/orders/orders.effects.spec.ts
  src/app/core/store/customer/user/user.actions.ts
  src/app/core/store/customer/user/user.effects.spec.ts
  src/app/core/store/general/countries/countries.actions.ts
  src/app/core/store/general/regions/regions.actions.ts
  src/app/core/store/shopping/categories/categories.actions.ts
  src/app/core/store/shopping/categories/categories.effects.spec.ts
  src/app/core/store/shopping/compare/compare.actions.ts
  src/app/core/store/shopping/filter/filter.actions.ts
  src/app/core/store/shopping/product-listing/product-listing.actions.ts
  src/app/core/store/shopping/product-listing/product-listing.effects.spec.ts
  src/app/core/store/shopping/products/products.actions.ts
  src/app/core/store/shopping/products/products.effects.spec.ts
  src/app/core/store/shopping/recently/recently.actions.ts
  src/app/core/store/shopping/search/search.actions.ts
  src/app/core/store/shopping/search/search.effects.spec.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/extensions/order-templates/store/order-template/order-template.actions.ts
  src/app/extensions/quoting/store/quote-request/quote-request.actions.ts
  src/app/extensions/quoting/store/quote/quote.actions.ts
  src/app/extensions/sentry/store/sentry-config/sentry-config.actions.ts
  src/app/extensions/seo/store/seo/seo.actions.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.actions.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.spec.ts
Labels: refactoring

#290 deps: dependency upgrades
  package-lock.json
  package.json
Labels: dependencies

#296 deps: ngx-custom-validators instead of ng2-validations
  docs/guides/forms.md
  package-lock.json
  package.json
  src/app/pages/account-profile-email/account-profile-email/account-profile-email.component.ts
  src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.ts
  src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.ts
  src/app/pages/forgot-password/request-reminder-form/request-reminder-form.component.ts
  src/app/pages/forgot-password/update-password-form/update-password-form.component.ts
  src/app/pages/registration/registration-form/registration-form.component.ts
  src/app/shared/forms/components/login-form/login-form.component.ts
Labels: dependencies

#289 refactor: breadcrumb component
  src/app/core/routing/category/category.route.ts
  src/app/core/store/content/pages/pages.effects.ts
  src/app/core/store/shopping/categories/categories.effects.ts
  src/app/core/store/shopping/categories/categories.selectors.spec.ts
  src/app/core/store/shopping/categories/categories.selectors.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/products/products.selectors.spec.ts
  src/app/core/store/shopping/products/products.selectors.ts
  src/app/core/store/shopping/search/search.effects.spec.ts
  src/app/core/store/shopping/search/search.effects.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/extensions/order-templates/store/order-template/order-template.effects.spec.ts
  src/app/extensions/order-templates/store/order-template/order-template.effects.ts
  src/app/extensions/quickorder/pages/quickorder-routing.module.ts
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.html
  src/app/extensions/quoting/store/quote-request/quote-request.effects.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.spec.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.ts
  src/app/pages/account/account-page.component.html
  src/app/pages/account/account-page.component.ts
  src/app/pages/app-routing.module.ts
  src/app/pages/category/category-categories/category-categories.component.html
  src/app/pages/category/category-products/category-products.component.html
  src/app/pages/contact/contact-page.component.html
  src/app/pages/content/content-page.component.html
  src/app/pages/product/product-page.component.html
  src/app/pages/recently/recently-page.component.html
  src/app/pages/search/search-page.component.html
  src/app/pages/search/search-result/search-result.component.html
  src/app/shared/components/common/breadcrumb/breadcrumb.component.html
  src/app/shared/components/common/breadcrumb/breadcrumb.component.spec.ts
  src/app/shared/components/common/breadcrumb/breadcrumb.component.ts
Labels: refactoring

#307 refactor: adapt parsing for changed configurations REST call
  src/app/core/models/server-config/server-config.interface.ts
  src/app/core/models/server-config/server-config.mapper.spec.ts
  src/app/core/models/server-config/server-config.mapper.ts
  tslint.json
Labels: refactoring
