Repository intershop/intershop-pwa, pull requests merged in 2020-07, with the labels that each got.

#284 memoize selectors for categories
  src/app/core/facades/shopping.facade.ts
  src/app/core/models/category-tree/category-tree.helper.spec.ts
  src/app/core/models/category-tree/category-tree.helper.ts
  src/app/core/models/category-view/category-view.model.spec.ts
  src/app/core/models/category-view/category-view.model.ts
  src/app/core/models/category/category.helper.spec.ts
  src/app/core/models/category/category.helper.ts
  src/app/core/models/navigation-category/navigation-category.model.ts
  src/app/core/store/shopping/categories/categories.selectors.spec.ts
  src/app/core/store/shopping/categories/categories.selectors.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/pages/category/category-categories/category-categories.component.html
  src/app/pages/category/category-list/category-list.component.html
  src/app/pages/category/category-list/category-list.component.spec.ts
  src/app/pages/category/category-list/category-list.component.ts
  src/app/pages/category/category-navigation/category-navigation.component.html
  src/app/pages/category/category-navigation/category-navigation.component.spec.ts
  src/app/pages/category/category-navigation/category-navigation.component.ts
  src/app/pages/category/category-page.component.html
  src/app/pages/category/category-tile/category-tile.component.html
  src/app/pages/category/category-tile/category-tile.component.spec.ts
  src/app/pages/category/category-tile/category-tile.component.ts
  src/app/shell/header/header-navigation/header-navigation.component.html
  src/app/shell/header/header-navigation/header-navigation.component.spec.ts
  src/app/shell/header/header-navigation/header-navigation.component.ts
  src/app/shell/header/sub-category-navigation/__snapshots__/sub-category-navigation.component.spec.ts.snap
  src/app/shell/header/sub-category-navigation/sub-category-navigation.component.html
  src/app/shell/header/sub-category-navigation/sub-category-navigation.component.spec.ts
  src/app/shell/header/sub-category-navigation/sub-category-navigation.component.ts
Labels: enhancement

#308 deps: ngx-custom-validators instead of ng2-validations - add missing change
  tslint.json
Labels: dependencies

#314 fix: delay routing after user profile edit
  src/app/core/facades/account.facade.ts
  src/app/core/store/customer/user/user.actions.ts
  src/app/core/store/customer/user/user.effects.spec.ts
  src/app/core/store/customer/user/user.effects.ts
Labels: refactoring

#317 fix: Correcting field type for error message key.
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
Labels: bug

#324 refactor: use camelize for feature switch naming with the extension schematic
  schematics/src/extension/files/__name@dasherize__/exports/__name@dasherize__-exports.module.ts.template
Labels: refactoring

#323 fix: save bic for concardis direct debit payment method
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.spec.ts
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
Labels: bug

#330 fix(tslint-rules): repair use-async-synchronization-in-tests rule
  src/app/core/services/api/api.service.spec.ts
  src/app/core/store/content/content-store.spec.ts
  src/app/core/store/core/configuration/configuration.effects.spec.ts
  src/app/core/store/customer/basket/basket-items.effects.spec.ts
  src/app/extensions/quoting/services/quote-request/quote-request.service.spec.ts
  tslint-rules/src/useAsyncSynchronisationInTestsRule.ts
  tslint-rules/src/useAsyncSynchronizationInTestsRule.spec.ts
  tslint-rules/src/useAsyncSynchronizationInTestsRule.ts
  tslint.json
Labels: enhancement, refactoring

#337 feat: show account identifier attribute of payment instrument
  src/app/core/models/payment-instrument/payment-instrument.interface.ts
  src/app/core/models/payment-method/payment-method.mapper.ts
Labels: enhancement

#331 feat: display approval required info on checkout review page if relevant
  src/app/core/icon.module.ts
  src/app/core/models/basket-approval/basket-approval.model.ts
  src/app/core/models/basket/basket.interface.ts
  src/app/core/models/basket/basket.mapper.spec.ts
  src/app/core/models/basket/basket.mapper.ts
  src/app/core/models/basket/basket.model.ts
  src/app/pages/checkout-receipt/checkout-receipt/checkout-receipt.component.html
  src/app/pages/checkout-review/checkout-review/checkout-review.component.html
  src/app/pages/checkout-review/checkout-review/checkout-review.component.spec.ts
  src/app/shared/components/basket/basket-approval-info/basket-approval-info.component.html
  src/app/shared/components/basket/basket-approval-info/basket-approval-info.component.spec.ts
  src/app/shared/components/basket/basket-approval-info/basket-approval-info.component.ts
  src/app/shared/components/common/modal-dialog-link/modal-dialog-link.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#338 fix: Summary of minor user management issues
  projects/organization-management/src/app/pages/user-detail/user-detail-page.component.html
  projects/organization-management/src/app/pages/user-detail/user-detail-page.component.spec.ts
  projects/organization-management/src/app/pages/users/users-page.component.html
  projects/organization-management/src/app/pages/users/users-page.component.spec.ts
  projects/organization-management/src/app/pages/users/users-page.component.ts
  projects/organization-management/src/app/store/users/users.effects.spec.ts
  projects/organization-management/src/app/store/users/users.effects.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/themes/blue/style.scss
Labels: bug:minor

#340 fix: inconsistent breadcrumb updates on category, search & product page
  src/app/core/store/shopping/categories/categories.effects.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/search/search.effects.ts
  src/app/core/store/shopping/shopping-store.spec.ts
Labels: enhancement

#345 build: use service principal for azure demo servers
  .github/workflows/demo-server-down.yml
  .github/workflows/demo-server.yml
Labels: enhancement

#347 refactor: remove deprecated exports
  docs/guides/migrations.md
  src/app/core/store/content/content-store.module.ts
  src/app/core/store/core/core-store.module.ts
  src/app/core/store/shopping/shopping-store.module.ts
  src/app/core/utils/dev/ngrx-testing.ts
  src/app/extensions/quoting/store/quoting-store.module.ts
  src/app/extensions/wishlists/store/wishlists-store.module.ts
  tslint.json
Labels: refactoring

#303 docs: add headless app type migration information
  docs/concepts/hybrid-approach.md
  docs/guides/migrations.md
  docs/guides/ssr-startup.md
  src/hybrid/default-url-mapping-table.ts
Labels: documentation

#353 fix: tacton localization
  src/app/extensions/tacton/pages/configure/configure-page.component.html
  src/app/extensions/tacton/pages/configure/configure-page.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-bom/tacton-bom.component.html
  src/app/extensions/tacton/pages/configure/tacton-bom/tacton-bom.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-parameter/tacton-parameter.component.html
  src/app/extensions/tacton/pages/configure/tacton-parameter/tacton-parameter.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-selected-image/tacton-selected-image.component.html
  src/app/extensions/tacton/pages/configure/tacton-selected-image/tacton-selected-image.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-step-buttons/tacton-step-buttons.component.html
  src/app/extensions/tacton/pages/configure/tacton-step-buttons/tacton-step-buttons.component.spec.ts
  src/app/extensions/tacton/shared/product/tacton-configure-product/tacton-configure-product.component.html
  src/app/extensions/tacton/shared/product/tacton-configure-product/tacton-configure-product.component.spec.ts
  src/assets/i18n/en_US.json
Labels: bug

#354 documentation for tacton integration
  docs/README.md
  docs/check-dead-links.js
  docs/guides/tacton-product-configuration.md
Labels: documentation
