Repository intershop/intershop-pwa, pull requests merged in 2020-03, with the labels that each got.

#130 fix: change password redirects to login page on success
  src/app/core/guards/login.guard.ts
  src/app/pages/forgot-password/update-password/update-password.component.ts
Labels: bug

#137 chore: update new product-route import for wishlist
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-line-item/account-wishlist-detail-line-item.component.spec.ts
Labels: regression

#138 fix: set correct URL for sharing product page via email
  src/app/core/facades/app.facade.ts
  src/app/pages/product/product-detail-actions/product-detail-actions.component.html
  src/app/pages/product/product-detail-actions/product-detail-actions.component.ts
  src/app/pages/product/product-detail/product-detail.component.html
  src/app/pages/product/product-detail/product-detail.component.ts
  src/app/pages/product/product-page.component.html
  src/app/pages/product/product-page.component.ts
Labels: bug

#136 chore: update recommended vscode extensions
  .vscode/extensions.json
Labels: enhancement

#142 Thank you for your order! - Quote Links are not working
  src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.html
  src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.html
Labels: bug

#145 refactor: fix translations in localization files
  src/assets/i18n/de_DE.json
  src/assets/i18n/fr_FR.json
Labels: refactoring

#139 build: introduce commitizen and commitlint
  .cz-config.js
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: research

#147 fix: consistent success messages in My Account area
  src/app/core/facades/account.facade.ts
  src/app/core/store/addresses/addresses.effects.spec.ts
  src/app/core/store/addresses/addresses.effects.ts
  src/app/extensions/quoting/store/quote-request/quote-request.effects.spec.ts
  src/app/extensions/quoting/store/quote-request/quote-request.effects.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.spec.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.selectors.spec.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.selectors.ts
  src/app/pages/account-addresses/account-addresses-page.component.html
  src/app/pages/account-addresses/account-addresses-page.component.ts
  src/app/pages/account-addresses/account-addresses/account-addresses.component.spec.ts
  src/app/pages/account-addresses/account-addresses/account-addresses.component.ts
  src/app/pages/account-profile-company/account-profile-company-page.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug

#153 refactor: matcher for category url rewrite
  src/app/core/routing/category/category.route.ts
Labels: bug

#152 fix: use data.id for ContentPageletEntryPoint id (#151)
  e2e/cypress/integration/specs/cms/server-html.mock.e2e-spec.ts
  src/app/core/models/content-pagelet-entry-point/content-pagelet-entry-point.mapper.spec.ts
  src/app/core/models/content-pagelet-entry-point/content-pagelet-entry-point.mapper.ts
Labels: bug

#159 fix: searchbox prevent "null"
  src/app/shell/header/search-box/search-box.component.html
Labels: bug

#81 ISREST-608: added quantity fixed handling
  src/app/core/models/line-item/line-item.interface.ts
  src/app/core/models/line-item/line-item.mapper.ts
  src/app/core/models/line-item/line-item.model.ts
  src/app/shared/components/basket/line-item-list/line-item-list.component.html
Labels: enhancement

#155 refactor: routing & breadcrumb of account orders (history/detail)
  src/app/core/store/orders/orders.effects.spec.ts
  src/app/core/store/orders/orders.effects.ts
  src/app/pages/account-order-history/account-order-history-page.module.ts
  src/app/pages/account/account-page.module.ts
Labels: bug, feature, refactoring

#158 fix: remove personalized content from store
  src/app/core/store/content/content-store.module.ts
  src/app/core/store/content/includes/includes.actions.ts
  src/app/core/store/content/includes/includes.effects.spec.ts
  src/app/core/store/content/includes/includes.effects.ts
  src/app/core/store/content/includes/includes.reducer.ts
  src/app/core/store/content/pagelets/index.ts
  src/app/core/store/content/pagelets/pagelets.actions.ts
  src/app/core/store/content/pagelets/pagelets.effects.spec.ts
  src/app/core/store/content/pagelets/pagelets.effects.ts
  src/app/core/store/content/pagelets/pagelets.reducer.ts
  src/app/core/store/content/pages/pages.actions.ts
  src/app/core/store/content/pages/pages.effects.spec.ts
  src/app/core/store/content/pages/pages.effects.ts
  src/app/core/store/content/pages/pages.reducer.ts
Labels: bug, enhancement

#168 fix: fix styling of user information box for mobile (#90)
  src/app/shell/header/language-switch/language-switch.component.html
  src/app/shell/header/language-switch/language-switch.component.spec.ts
  src/app/shell/header/language-switch/language-switch.component.ts
  src/app/shell/header/user-information-mobile/user-information-mobile.component.html
  src/styles/components/header/user-information-mobile.scss
Labels: bug

#175 i18n: added and unified wish list messages
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug
