Repository intershop/intershop-pwa, pull requests merged in 2020-12, with the labels that each got.

#458 fix: display only one validation error for a form element at once
  src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.html
  src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.spec.ts
  src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.ts
Labels: bug:minor

#475 fix: repair schema build
  schematics/src/extension/schema.json
  schematics/src/model/schema.json
  schematics/src/page/schema.json
  schematics/src/utils/ts-morph.ts
Labels: bug:major

#352 feat: SSO with Auth0 for B2C
  .github/workflows/development.yml
  .github/workflows/integration.yml
  docs/README.md
  docs/concepts/sso.md
  docs/guides/nginx-startup.md
  docs/guides/sso-auth0.md
  docs/guides/ssr-startup.md
  nginx/channel.conf.tmpl
  package-lock.json
  package.json
  src/app/core/configurations/configuration.meta.ts
  src/app/core/identity-provider.module.ts
  src/app/core/identity-provider/auth0.identity-provider.ts
  src/app/core/identity-provider/icm.identity-provider.ts
  src/app/core/identity-provider/identity-provider.factory.ts
  src/app/core/identity-provider/identity-provider.interface.ts
  src/app/core/store/customer/addresses/addresses.effects.spec.ts
  src/app/core/store/customer/addresses/addresses.effects.ts
  src/app/core/store/customer/basket/basket.effects.ts
  src/app/pages/account-profile/account-profile/account-profile.component.html
  src/app/pages/account-profile/account-profile/account-profile.component.spec.ts
  src/app/shared/address-forms/components/address-form/address-form.factory.ts
  src/environments/environment.model.ts
Labels: feature

#482 chore: temporarily ignore failing test for 7.10.26.0
  e2e/cypress/integration/specs/checkout/checkout-payments.b2c.e2e-spec.ts
  scripts/tslint-hard.js
Labels: regression

#477 fix: display the user's inactive status on the b2b user list
  projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.spec.ts
  projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.ts
Labels: bug:minor

#488 refactor: use API for creating quote request from quote request
  e2e/cypress/integration/specs/quoting/quote-handling.b2b.e2e-spec.ts
  src/app/extensions/quoting/facades/quote-context.facade.ts
  src/app/extensions/quoting/services/quoting/quoting.service.spec.ts
  src/app/extensions/quoting/services/quoting/quoting.service.ts
  src/app/extensions/quoting/store/quoting/quoting.actions.ts
  src/app/extensions/quoting/store/quoting/quoting.effects.spec.ts
  src/app/extensions/quoting/store/quoting/quoting.effects.ts
Labels: refactoring

#479 feat: checkout - simple basket acceleration
  src/app/core/facades/checkout.facade.ts
  src/app/core/store/customer/basket/basket-validation.effects.spec.ts
  src/app/core/store/customer/basket/basket-validation.effects.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.reducer.ts
  src/app/core/store/customer/customer-store.spec.ts
  src/app/pages/basket/basket-page.component.ts
Labels: feature
