Repository intershop/intershop-pwa, pull requests merged in 2020-11, with the labels that each got.

#4 feat: render view context content
  src/app/core/facades/cms.facade.ts
  src/app/core/models/call-parameters/call-parameters.model.ts
  src/app/core/models/category/category.interface.ts
  src/app/core/models/category/category.mapper.ts
  src/app/core/models/category/category.model.ts
  src/app/core/services/cms/cms.service.ts
  src/app/core/store/content/content-store.module.ts
  src/app/core/store/content/content-store.ts
  src/app/core/store/content/pagelets/pagelets.reducer.ts
  src/app/core/store/content/viewcontexts/index.ts
  src/app/core/store/content/viewcontexts/viewcontexts.actions.ts
  src/app/core/store/content/viewcontexts/viewcontexts.effects.spec.ts
  src/app/core/store/content/viewcontexts/viewcontexts.effects.ts
  src/app/core/store/content/viewcontexts/viewcontexts.reducer.spec.ts
  src/app/core/store/content/viewcontexts/viewcontexts.reducer.ts
  src/app/core/store/content/viewcontexts/viewcontexts.selectors.spec.ts
  src/app/core/store/content/viewcontexts/viewcontexts.selectors.ts
  src/app/shared/cms/components/content-viewcontext/content-viewcontext.component.html
  src/app/shared/cms/components/content-viewcontext/content-viewcontext.component.spec.ts
  src/app/shared/cms/components/content-viewcontext/content-viewcontext.component.ts
  src/app/shared/shared.module.ts
Labels: feature

#451 fix: repair setting of locales meta tags
  src/app/core/store/core/configuration/configuration.selectors.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
Labels: bug:major

#448 Bugfix/promotion messages
  e2e/cypress/integration/pages/checkout/cart.page.ts
  e2e/cypress/integration/specs/checkout/basket-promotion-handling.b2c.e2e-spec.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/app/shared/components/basket/basket-promotion-code/basket-promotion-code.component.html
  src/app/shared/components/basket/basket-promotion-code/basket-promotion-code.component.spec.ts
  src/app/shared/components/basket/basket-promotion-code/basket-promotion-code.component.ts
  src/app/shared/components/common/success-message/success-message.component.html
  src/app/shared/components/common/success-message/success-message.component.spec.ts
  src/app/shared/components/common/success-message/success-message.component.ts
  src/app/shared/shared.module.ts
Labels: bug

#454 test: cypress stabilization
  e2e/cypress/integration/pages/account/my-account.page.ts
  e2e/cypress/integration/pages/account/wishlists-details.page.ts
  e2e/cypress/integration/pages/checkout/checkout-payment.page.ts
  e2e/cypress/integration/specs/extras/wishlists-management.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/authentication-timeouts-loggedin.b2c.e2e-spec.ts
Labels: enhancement

#456 chore: update required/tested Node.js version to 14.15.0 LTS (including npm 6.14.8)
  .github/workflows/dead-code.yml
  .github/workflows/development.yml
  .github/workflows/docs.yml
  .github/workflows/integration.yml
  .github/workflows/updates.yml
  .github/workflows/windows.yml
  Dockerfile
  Dockerfile_reports
  docs/guides/getting-started.md
  docs/guides/migrations.md
  package-lock.json
  package.json
  templates/Dockerfile_dev
  tslint-rules/src/ishUsefulImportsRule.ts
Labels: dependencies

#459 fix: prevent an error if language switched on order details page
  src/app/core/store/customer/orders/orders.effects.ts
Labels: bug

#457 docs: add migration note for new multi-channel format
  CHANGELOG.md
  docs/guides/migrations.md
Labels: documentation

#437 feat(schematics): lazy-components for projects
  e2e/test-schematics.sh
  schematics/src/helpers/customized-copy/factory_spec.ts
  schematics/src/helpers/lazy-components/factory.ts
  schematics/src/helpers/move-component/factory_spec.ts
  schematics/src/lazy-component/factory.ts
  schematics/src/lazy-component/factory_spec.ts
  schematics/src/lazy-component/files/__name@dasherize__/__name@dasherize__.component.ts.template
  schematics/src/store/factory_spec.ts
  schematics/src/utils/registration.ts
  tslint.json
Labels: enhancement

#462 fix: customization start script should add themes with inject false
  schematics/customization/add/index.js
Labels: bug:major

#466 perf: run configurations call only once for SSR
  src/app/core/store/general/server-config/server-config.effects.ts
Labels: bug

#465 perf: deny SSR rendering when accept headers do not match
  server.ts
Labels: enhancement

#414 feat: use new REST API for filters and products on master variation page
  src/app/core/facades/shopping.facade.ts
  src/app/core/models/product-variation/product-variation.helper.spec.ts
  src/app/core/models/product-variation/product-variation.helper.ts
  src/app/core/models/search-parameter/search-parameter.mapper.spec.ts
  src/app/core/models/search-parameter/search-parameter.mapper.ts
  src/app/core/models/search-parameter/search-parameter.model.ts
  src/app/core/services/filter/filter.service.spec.ts
  src/app/core/services/filter/filter.service.ts
  src/app/core/services/product-master-variations/product-master-variations.service.spec.ts
  src/app/core/services/product-master-variations/product-master-variations.service.ts
  src/app/core/services/products/products.service.ts
  src/app/core/state-management.module.ts
  src/app/core/store/shopping/filter/filter.actions.ts
  src/app/core/store/shopping/filter/filter.effects.spec.ts
  src/app/core/store/shopping/filter/filter.effects.ts
  src/app/core/store/shopping/product-listing/product-listing.actions.ts
  src/app/core/store/shopping/product-listing/product-listing.effects.ts
  src/app/core/store/shopping/product-listing/product-listing.reducer.ts
  src/app/core/store/shopping/products/products.actions.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/products/products.selectors.ts
  src/app/core/utils/url-form-params.spec.ts
  src/app/core/utils/url-form-params.ts
  src/app/shared/components/filter/filter-navigation-badges/filter-navigation-badges.component.html
  src/app/shared/components/filter/filter-navigation-badges/filter-navigation-badges.component.ts
  src/app/shared/components/product/product-price/product-price.component.ts
  src/app/shared/components/product/product-row/product-row.component.html
  src/app/shared/components/product/product-tile/product-tile.component.html
  src/app/shared/components/product/product-tile/product-tile.component.spec.ts
  src/app/shared/components/product/product-tile/product-tile.component.ts
Labels: enhancement

#469 fix: replace interfering special characters from product and categoy slugs
  src/app/core/routing/category/category.route.spec.ts
  src/app/core/routing/category/category.route.ts
  src/app/core/routing/product/product.route.spec.ts
  src/app/core/routing/product/product.route.ts
  src/app/core/utils/routing.ts
Labels: bug
