Repository intershop/intershop-pwa, pull requests merged in 2020-05, with the labels that each got.

#234 fix: Concardis DirectDebit cannot be assigned to basket
  src/app/core/models/payment-method/payment-method.mapper.ts
Labels: bug

#236 fix: use exhaustMap for user login to prevent creating multiple sessions
  src/app/core/store/user/user.effects.ts
Labels: bug

#217 fix: hide loading spinner after order creation failed
  src/app/core/store/checkout/basket/basket-validation.effects.spec.ts
  src/app/core/store/checkout/basket/basket-validation.effects.ts
Labels: bug

#242 deps(e2e): cleanup e2e dependencies
  e2e/cypress/plugins/cy-ts-preprocessor.js
  e2e/cypress/plugins/index.js
  e2e/package.json
Labels: dependencies

#241 fix: display the region in the address form on the checkout address page
  src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.ts
  src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.ts
Labels: bug

#240 fix: display concardis direct debit form on checkout payment page
  src/app/core/models/payment-method/payment-method.mapper.spec.ts
  src/app/core/models/payment-method/payment-method.mapper.ts
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
  src/app/shared/forms-dynamic/components/input-dynamic/input-dynamic.component.html
  src/app/shared/forms-dynamic/components/select-dynamic/select-dynamic.component.html
  src/app/shared/forms-dynamic/forms-dynamic.spec.ts
Labels: bug

#243 docs: guide for upgrading dependencies
  docs/README.md
  docs/guides/upgrading-pwa.md
Labels: documentation

#252 docs: replace dead link
  docs/guides/angular-component-development.md
Labels: documentation

#254 fix(schematics): handle imports of complex typings for input decorated fields in lazy-component schematic
  schematics/src/lazy-component/factory.ts
  schematics/src/lazy-component/factory_spec.ts
Labels: bug

#259 deps: update Bootstrap 4.4.1 to 4.5.0
  package-lock.json
  package.json
Labels: dependencies

#255 chore: remove (feature toggle) security question
  src/app/core/facades/account.facade.ts
  src/app/core/models/credentials/credentials.model.ts
  src/app/core/services/user/user.service.ts
  src/app/core/store/checkout/basket/basket.effects.spec.ts
  src/app/core/store/checkout/checkout-store.spec.ts
  src/app/core/store/user/user.actions.ts
  src/app/core/store/user/user.effects.spec.ts
  src/app/pages/registration/registration-credentials-form/registration-credentials-form.component.html
  src/app/pages/registration/registration-credentials-form/registration-credentials-form.component.spec.ts
  src/app/pages/registration/registration-credentials-form/registration-credentials-form.component.ts
  src/app/pages/registration/registration-form/registration-form.component.html
  src/app/pages/registration/registration-form/registration-form.component.ts
  src/app/shared/forms/components/select-security-question/select-security-question.component.spec.ts
  src/app/shared/forms/components/select-security-question/select-security-question.component.ts
  src/app/shared/forms/forms.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/environments/environment.model.ts
Labels: regression

#261 fix: PWA container healthcheck now supports ICM https
  dist/healthcheck.js
Labels: bug

#266 development helpers
  .github/workflows/windows.yml
  .prettierignore
  docs/guides/development.md
  package.json
  scripts/init-local-environment.js
Labels: enhancement
