Repository intershop/intershop-pwa, pull requests merged in 2020-10, with the labels that each got.

#391 feat: monitor PWA containers with prometheus
  docs/README.md
  docs/check-dead-links.js
  docs/guides/prometheus-monitoring-dashboard-annotated.png
  docs/guides/prometheus-monitoring-dashboard.json
  docs/guides/prometheus-monitoring.md
  docs/guides/ssr-startup.md
  nginx/Dockerfile
  nginx/README.md
  nginx/channel.conf.tmpl
  nginx/entrypoint.sh
  nginx/features/prometheus.conf
  package-lock.json
  package.json
  server.ts
  templates/docker-compose.yml
Labels: feature

#395 fix: replace parantheses in URL slugs
  src/app/core/routing/category/category.route.spec.ts
  src/app/core/routing/category/category.route.ts
  src/app/core/routing/product/product.route.ts
Labels: bug

#396 fix: display payment costs according to the configured display type (…
  src/app/core/models/payment-method/payment-method.mapper.spec.ts
  src/app/core/models/payment-method/payment-method.mapper.ts
  src/app/core/models/payment-method/payment-method.model.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
Labels: bug

#404 fix: close toast on routing
  src/app/core/facades/account.facade.ts
  src/app/core/store/core/messages/messages.effects.ts
Labels: enhancement

#397 fix: display and edit the b2b user's active status
  projects/organization-management/src/app/components/user-profile-form/user-profile-form.component.html
  projects/organization-management/src/app/components/user-profile-form/user-profile-form.component.spec.ts
  projects/organization-management/src/app/models/b2b-user/b2b-user.interface.ts
  projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.spec.ts
  projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.ts
  projects/organization-management/src/app/models/b2b-user/b2b-user.model.ts
  projects/organization-management/src/app/pages/user-create/user-create-page.component.spec.ts
  projects/organization-management/src/app/pages/user-create/user-create-page.component.ts
  projects/organization-management/src/app/pages/user-detail/user-detail-page.component.html
  projects/organization-management/src/app/pages/user-edit-profile/user-edit-profile-page.component.spec.ts
  projects/organization-management/src/app/pages/user-edit-profile/user-edit-profile-page.component.ts
  projects/organization-management/src/app/pages/users/users-page.component.html
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug

#402 fix: set breadcrumb from routing only if none was set previously
  e2e/cypress/integration/pages/account/order-templates-details.page.ts
  e2e/cypress/integration/pages/account/order-templates-overview.page.ts
  e2e/cypress/integration/pages/account/quote-detail.page.ts
  e2e/cypress/integration/pages/account/quote-list.page.ts
  e2e/cypress/integration/pages/account/wishlists-details.page.ts
  e2e/cypress/integration/pages/account/wishlists-overview.page.ts
  e2e/cypress/integration/specs/extras/order-templates-management.b2b.e2e-spec.ts
  e2e/cypress/integration/specs/extras/wishlists-management.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/quoting/quote-handling.b2b.e2e-spec.ts
  src/app/core/store/core/viewconf/viewconf.effects.ts
  src/app/core/store/customer/orders/orders.effects.spec.ts
  src/app/core/store/customer/orders/orders.effects.ts
  src/app/extensions/order-templates/store/order-template/order-template.effects.spec.ts
  src/app/extensions/order-templates/store/order-template/order-template.effects.ts
  src/app/extensions/quoting/store/quoting/quoting.effects.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.spec.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.ts
Labels: bug

#409 fix: display error messages on the b2b user edit profile page
  projects/organization-management/src/app/pages/user-edit-profile/user-edit-profile-page.component.html
Labels: bug:minor

#413 fix: remove loading animation after creating an address during checkout
  src/app/core/store/customer/addresses/addresses.reducer.ts
Labels: bug

#412 fix: repair setting of canonical urls and other meta data
  docs/concepts/search-engine-optimization.md
  e2e/cypress/integration/pages/meta-data.module.ts
  e2e/cypress/integration/pages/shopping/family.page.ts
  e2e/cypress/integration/specs/system/seo-home-page.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/seo-product-detail-page.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/seo-search-page.b2c.e2e-spec.ts
  e2e/test-universal.sh
  src/app/core/models/seo-attributes/seo-attributes.mapper.ts
  src/app/core/models/seo-attributes/seo-attributes.model.ts
  src/app/core/utils/routing.ts
  src/app/extensions/seo/guards/meta.guard.ts
  src/app/extensions/seo/seo.module.ts
  src/app/extensions/seo/store/seo/index.ts
  src/app/extensions/seo/store/seo/seo.actions.ts
  src/app/extensions/seo/store/seo/seo.effects.spec.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
  tslint.json
Labels: bug

#416 refactor: Bootstrap Modal HTML unification and cleanup
  e2e/cypress/integration/pages/account/add-to-order-template.module.ts
  e2e/cypress/integration/pages/account/add-to-wishlist.module.ts
  src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.html
  src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.html
  src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.html
  src/app/extensions/quoting/shared/product-add-to-quote-dialog/product-add-to-quote-dialog.component.html
  src/app/extensions/wishlists/pages/account-wishlist/account-wishlist-list/account-wishlist-list.component.html
  src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.html
  src/app/extensions/wishlists/shared/wishlist-preferences-dialog/wishlist-preferences-dialog.component.html
  src/app/shared/components/common/modal-dialog/modal-dialog.component.html
  src/app/shared/components/login/login-modal/login-modal.component.html
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/global/modals.scss
Labels: refactoring

#423 test: stabilization
  .github/workflows/development.yml
  .github/workflows/integration.yml
  e2e/cypress/integration/specs/checkout/basket-handling.b2c.e2e-spec.ts
Labels: refactoring

#425 chore: re-activate configuration meta reducer for development
  src/app/core/store/core/core-store.module.ts
Labels: enhancement

#426 docs: customization for cypress tests
  docs/guides/customizations.md
Labels: documentation

#436 fix: submit a promotion code by pressing enter
  src/app/extensions/order-templates/shared/product-add-to-order-template/product-add-to-order-template.component.html
  src/app/extensions/wishlists/shared/product-add-to-wishlist/product-add-to-wishlist.component.html
  src/app/shared/components/basket/basket-promotion-code/basket-promotion-code.component.html
  src/app/shared/components/basket/basket-promotion-code/basket-promotion-code.component.ts
Labels: bug

#435 chore: clean up error messages in localization files
  docs/concepts/localization.md
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: refactoring

#442 fix: display line item quantity on checkout cart page after merging q…
  e2e/cypress/integration/pages/checkout/cart.page.ts
  e2e/cypress/integration/specs/checkout/basket-handling.b2c.e2e-spec.ts
  src/app/shared/components/line-item/line-item-list/line-item-list.component.ts
Labels: bug

#443 fix: improve ui of out-of-stock products on the cart page
  src/app/pages/basket/shopping-basket-empty/shopping-basket-empty.component.html
  src/app/shared/components/basket/basket-validation-items/basket-validation-items.component.html
  src/app/shared/components/basket/basket-validation-products/basket-validation-products.component.html
  src/styles/pages/checkout/shopping-cart.scss
Labels: bug:minor
