Repository intershop/intershop-pwa, pull requests merged in 2020-04, with the labels that each got.

#170 fix: fix loading animation display for scrollable pages (#166)
  src/app/shared/components/common/loading/loading.component.scss
Labels: bug

#182 feat: delete payment instrument link on checkout payment page
  e2e/cypress/integration/specs/checkout/checkout-payments.b2c.e2e-spec.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
Labels: enhancement

#184 fix: if payment failed after order creation navigate to checkout paym…
  src/app/core/store/orders/orders.effects.spec.ts
  src/app/core/store/orders/orders.effects.ts
Labels: bug

#194 fix: prevent error after login on checkout address page
  src/app/core/models/basket/basket.interface.ts
  src/app/core/models/basket/basket.mapper.spec.ts
  src/app/core/models/basket/basket.mapper.ts
  src/app/core/models/basket/basket.model.ts
  src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.spec.ts
  src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.ts
  src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.spec.ts
  src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.ts
Labels: bug

#197 Revert "fix: fix loading animation display for longer pages (#166, #170)"
  src/app/shared/components/common/loading/loading.component.scss
Labels: bug

#177 feat: add quickorder functionality as configurable feature
  .github/workflows/test.yml
  .vscode/settings.json
  e2e/cypress/integration/pages/header.module.ts
  e2e/cypress/integration/pages/quickorder/quickorder.page.ts
  e2e/cypress/integration/specs/quickorder/quickorder-handling.b2b.e2e-spec.ts
  src/app/app.module.ts
  src/app/core/icon.module.ts
  src/app/core/store/checkout/basket/basket-items.effects.ts
  src/app/extensions/quickorder/exports/quickorder-exports.module.ts
  src/app/extensions/quickorder/exports/quickorder/lazy-header-quickorder/lazy-header-quickorder.component.html
  src/app/extensions/quickorder/exports/quickorder/lazy-header-quickorder/lazy-header-quickorder.component.ts
  src/app/extensions/quickorder/pages/quickorder-routing.module.ts
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.html
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.spec.ts
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.ts
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.module.ts
  src/app/extensions/quickorder/quickorder.module.ts
  src/app/extensions/quickorder/shared/header/header-quickorder/header-quickorder.component.html
  src/app/extensions/quickorder/shared/header/header-quickorder/header-quickorder.component.spec.ts
  src/app/extensions/quickorder/shared/header/header-quickorder/header-quickorder.component.ts
  src/app/shared/shared.module.ts
  src/app/shell/header/header-default/__snapshots__/header-default.component.spec.ts.snap
  src/app/shell/header/header-default/header-default.component.html
  src/app/shell/header/header-default/header-default.component.spec.ts
  src/app/shell/shell.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/environments/environment.model.ts
  src/styles/components/header/header-sticky.scss
  src/styles/components/header/search-container.scss
Labels: feature

#202 build(deps): update dependencies to fix vulnerabilities
  e2e/package-lock.json
  package-lock.json
  package.json
  schematics/package-lock.json
  tslint-rules/package-lock.json
Labels: dependencies

#195 feat: wishlist widget on account overview page
  src/app/extensions/wishlists/exports/account/lazy-wishlist-widget/lazy-wishlist-widget.component.html
  src/app/extensions/wishlists/exports/account/lazy-wishlist-widget/lazy-wishlist-widget.component.ts
  src/app/extensions/wishlists/exports/wishlists-exports.module.ts
  src/app/extensions/wishlists/facades/wishlists.facade.ts
  src/app/extensions/wishlists/shared/account/wishlist-widget/wishlist-widget.component.html
  src/app/extensions/wishlists/shared/account/wishlist-widget/wishlist-widget.component.spec.ts
  src/app/extensions/wishlists/shared/account/wishlist-widget/wishlist-widget.component.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.selectors.ts
  src/app/extensions/wishlists/wishlists.module.ts
  src/app/pages/account-overview/account-overview/account-overview.component.html
  src/app/pages/account-overview/account-overview/account-overview.component.spec.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#203 build(deps): make "conventional-changelog-cli" a devDependency and set it to a fixed version
  package-lock.json
  package.json
Labels: dependencies

#211 feat: display loading animation while restoring user on first navigation
  e2e/test-universal.sh
  src/app/core/facades/app.facade.ts
  src/app/core/guards/auth.guard.spec.ts
  src/app/core/guards/auth.guard.ts
  src/app/pages/login/login-page.component.html
  src/app/pages/login/login-page.component.spec.ts
  src/app/pages/login/login-page.component.ts
Labels: enhancement

#222 fix: prevent mixed locale due to race condition using ngx-translate service use with SSR
  src/app/core/store/configuration/configuration.effects.spec.ts
  src/app/core/store/configuration/configuration.effects.ts
Labels: bug
