Repository intershop/intershop-pwa, pull requests merged in 2020-02, with the labels that each got.

#105 chore: repair compodoc generation
  tsconfig.app.json
Labels: bug

#108 feat: add support for CMS Landing Page components
  src/app/shared/cms/cms.module.ts
  src/app/shared/cms/components/cms-landing-page/cms-landing-page.component.html
  src/app/shared/cms/components/cms-landing-page/cms-landing-page.component.spec.ts
  src/app/shared/cms/components/cms-landing-page/cms-landing-page.component.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#107 feat: localized product attributes
  src/app/core/models/product/product.mapper.spec.ts
  src/app/core/models/product/product.mapper.ts
Labels: feature

#111 fix: missing product names in quote items listing (#111)
  src/app/shared/components/basket/line-item-list/line-item-list.component.html
Labels: bug

#113 deps: update Angular dependencies
  package-lock.json
  package.json
Labels: dependencies

#114 chore: adapt copyright notice
  LICENSE
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug

#121 chore: start app from root for github actions
  .github/workflows/test.yml
Labels: regression

#126 feat: add og:image to meta-tags
  src/app/core/models/seo-attribute/seo-attribute.model.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
  src/assets/img/og-image-default.jpg
Labels: enhancement

#112 fix: quote dialog submit behaviour
  e2e/cypress/integration/specs/quoting/quote-handling-anonymous.b2b.e2e-spec.ts
  e2e/cypress/integration/specs/quoting/quote-handling.b2b.e2e-spec.ts
  src/app/extensions/quoting/facades/quoting.facade.ts
  src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.html
  src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.spec.ts
  src/app/extensions/quoting/shared/product/product-add-to-quote-dialog/product-add-to-quote-dialog.component.ts
  src/app/extensions/quoting/shared/quote/quote-edit/quote-edit.component.html
  src/app/extensions/quoting/store/quote-request/quote-request.actions.ts
  src/app/extensions/quoting/store/quote-request/quote-request.effects.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug

#100 feat: multitheme logos
  .gitlab-ci.yml
  angular.json
  src/app/core/utils/theme/theme.service.ts
  src/assets/themes/blue/img/favicon.ico
  src/assets/themes/blue/img/logo.png
  src/assets/themes/blue/img/logo_192x192.png
  src/assets/themes/blue/img/logo_256x256.png
  src/assets/themes/blue/img/logo_384x384.png
  src/assets/themes/blue/img/logo_512x512.png
  src/assets/themes/blue/img/logo_apple_120x120.png
  src/assets/themes/blue/img/logo_apple_152x152.png
  src/assets/themes/blue/img/logo_apple_167x167.png
  src/assets/themes/blue/img/logo_apple_180x180.png
  src/assets/themes/blue/img/logo_mobile.png
  src/assets/themes/blue/manifest.webmanifest
  src/assets/themes/default/img/favicon.ico
  src/assets/themes/default/img/logo.png
  src/assets/themes/default/img/logo_192x192.png
  src/assets/themes/default/img/logo_256x256.png
  src/assets/themes/default/img/logo_384x384.png
  src/assets/themes/default/img/logo_512x512.png
  src/assets/themes/default/img/logo_apple_120x120.png
  src/assets/themes/default/img/logo_apple_152x152.png
  src/assets/themes/default/img/logo_apple_167x167.png
  src/assets/themes/default/img/logo_apple_180x180.png
  src/assets/themes/default/img/logo_mobile.png
  src/assets/themes/default/manifest.webmanifest
  src/environments/environment.model.ts
  src/index.html
  src/styles/themes/blue/variables.scss
  src/styles/themes/default/variables.scss
Labels: feature

#120 fix: removing preferred language in user profile
  e2e/cypress/integration/pages/account/profile-edit-details.page.ts
  e2e/cypress/integration/pages/account/profile.page.ts
  e2e/cypress/integration/specs/account/edit-user-preferred-language.b2c.e2e-spec.ts
  src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.html
  src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.spec.ts
  src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.ts
  src/app/pages/account-profile/account-profile/account-profile.component.html
  src/app/pages/account-profile/account-profile/account-profile.component.ts
  src/app/pages/registration/registration-form/registration-form.component.html
  src/app/pages/registration/registration-page.module.ts
  src/app/pages/registration/registration-personal-form/registration-personal-form.component.html
  src/app/pages/registration/registration-personal-form/registration-personal-form.component.spec.ts
  src/app/pages/registration/registration-personal-form/registration-personal-form.component.ts
  src/app/shared/forms/components/select-language/select-language.component.spec.ts
  src/app/shared/forms/components/select-language/select-language.component.ts
  src/app/shared/forms/forms.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug

#131 fix: display of product labels for product lists (#73)
  src/app/core/models/product/__snapshots__/product.mapper.spec.ts.snap
  src/app/core/models/product/product.interface.ts
  src/app/core/models/product/product.mapper.spec.ts
  src/app/core/models/product/product.mapper.ts
  src/app/core/services/products/products.service.spec.ts
  src/app/core/services/products/products.service.ts
Labels: bug

#133 Bugfix/login redirecting
  src/app/core/guards/auth.guard.ts
Labels: bug

#134 fix: display product labels on search result page
  src/app/core/services/products/products.service.ts
Labels: bug
