Repository intershop/intershop-pwa, pull requests merged in 2020-08, with the labels that each got.

#358 fix: adapt localizalized texts for user management
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#368 fix: tacton improvements
  src/app/core/directives.module.ts
  src/app/core/directives/intersection-observer.directive.ts
  src/app/core/store/core/messages/messages.effects.ts
  src/app/extensions/tacton/facades/tacton.facade.ts
  src/app/extensions/tacton/pages/configure/configure-page.component.html
  src/app/extensions/tacton/pages/configure/tacton-configure-navigation/tacton-configure-navigation.component.html
  src/app/extensions/tacton/pages/configure/tacton-configure-navigation/tacton-configure-navigation.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-configure-navigation/tacton-configure-navigation.component.ts
  src/app/extensions/tacton/pages/configure/tacton-group/tacton-group.component.html
  src/app/extensions/tacton/pages/configure/tacton-group/tacton-group.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-group/tacton-group.component.ts
  src/app/extensions/tacton/pages/configure/tacton-image-text-buttons/tacton-image-text-buttons.component.html
  src/app/extensions/tacton/pages/configure/tacton-image-text-buttons/tacton-image-text-buttons.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-step-buttons/tacton-step-buttons.component.html
  src/app/extensions/tacton/pages/configure/tacton-step-buttons/tacton-step-buttons.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-text-buttons/tacton-text-buttons.component.html
  src/app/extensions/tacton/pages/configure/tacton-text-buttons/tacton-text-buttons.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-text-buttons/tacton-text-buttons.component.ts
  src/app/extensions/tacton/store/product-configuration/product-configuration.effects.ts
  src/app/pages/product/product-detail-actions/product-detail-actions.component.html
  src/app/pages/product/product-detail-actions/product-detail-actions.component.spec.ts
  src/app/pages/product/product-detail/product-detail.component.html
  src/app/pages/product/product-detail/product-detail.component.spec.ts
  src/app/shared/components/product/product-row/product-row.component.html
  src/app/shared/components/product/product-row/product-row.component.spec.ts
  src/app/shared/components/product/product-tile/product-tile.component.html
  src/app/shared/components/product/product-tile/product-tile.component.spec.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/pages/productdetail/tacton.scss
Labels: enhancement, refactoring

#372 feat: enhance option to overwrite URL for ICM in express server
  docs/guides/ssr-startup.md
  server.ts
Labels: enhancement
