Repository intershop/intershop-pwa, pull requests merged in 2020-09, with the labels that each got.

#374 fix(schematics): enable customized-copy schematic for subfolders
  e2e/test-schematics.sh
  schematics/src/helpers/customized-copy/factory.ts
  schematics/src/helpers/customized-copy/schema.json
Labels: bug

#377 docs: provide new link to sentry sensitive data
  docs/guides/sentry-error-monitoring.md
Labels: documentation

#376 fix: repair loading of lazy extension components
  schematics/src/lazy-component/factory_spec.ts
  schematics/src/lazy-component/files/__name@dasherize__/__name@dasherize__.component.ts.template
Labels: bug, refactoring

#379 fix(schematics): respect original component selector when generating lazy components
  e2e/test-schematics.sh
  schematics/src/lazy-component/factory.ts
Labels: bug

#380 refactor: provide login guard handling in lazy module instead of app routing module
  src/app/core/guards/login.guard.ts
  src/app/pages/app-routing.module.ts
  src/app/pages/login/login-page.module.ts
  src/app/shell/shell.module.ts
Labels: refactoring

#319 feat: Implement save for later checkbox for Direct Debit
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.html
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
Labels: feature

#356 feat: styled toast messages for success and error messages
  e2e/cypress/integration/pages/account/registration.page.ts
  src/app/core/store/core/messages/messages.effects.spec.ts
  src/app/core/store/core/messages/messages.effects.ts
  src/app/shared/components/common/error-message/error-message.component.html
  src/app/shared/components/common/error-message/error-message.component.spec.ts
  src/app/shared/components/common/error-message/error-message.component.ts
  src/app/shared/components/login/login-form/login-form.component.html
  src/styles/global/toasts.scss
Labels: feature

#387 fix: use product name for basket line item name and order line item name for orders
  src/app/core/models/basket/basket.model.ts
  src/app/core/models/line-item/line-item.mapper.ts
  src/app/core/models/line-item/line-item.model.ts
  src/app/core/models/order/order.model.ts
  src/app/core/store/customer/basket/basket-items.effects.spec.ts
  src/app/core/store/customer/customer-store.spec.ts
  src/app/core/utils/dev/basket-mock-data.ts
  src/app/shared/components/basket/basket-items-summary/basket-items-summary.component.html
  src/app/shared/components/basket/basket-items-summary/basket-items-summary.component.spec.ts
  src/app/shared/components/line-item/line-item-list/line-item-list.component.ts
  src/app/shell/header/mini-basket/mini-basket.component.html
  src/app/shell/header/mini-basket/mini-basket.component.spec.ts
Labels: bug

#386 feat: add posibility to deploy nginx with selected features
  .prettierignore
  nginx/Dockerfile
  nginx/README.md
  nginx/channel.conf.tmpl
  nginx/entrypoint.sh
  nginx/features/cache.conf
  nginx/features/compression.conf
  nginx/features/device_detection-off.conf
  nginx/features/device_detection.conf
  nginx/features/pagespeed.conf
  nginx/nginx.conf
  templates/docker-compose.yml
Labels: documentation, enhancement

#390 chore: do not cancel workflows on main branches and tags
  .github/workflows/development.yml
  .github/workflows/integration.yml
  .github/workflows/windows.yml
Labels: enhancement

#389 perf: add preload link for stylesheet
  src/app/core/utils/theme/theme.service.ts
Labels: enhancement

#393 feat: display user role description
  projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.html
  projects/organization-management/src/app/models/b2b-role/b2b-role.interface.ts
  projects/organization-management/src/app/models/b2b-role/b2b-role.mapper.spec.ts
  projects/organization-management/src/app/models/b2b-role/b2b-role.mapper.ts
  projects/organization-management/src/app/models/b2b-role/b2b-role.model.ts
Labels: feature
