Repository intershop/intershop-pwa, pull requests merged in 2021-09, with the labels that each got.

#859 no broken page on missing requisition data
  projects/requisition-management/src/app/components/requisitions-list/requisitions-list.component.html
  projects/requisition-management/src/app/models/requisition/requisition.mapper.spec.ts
  projects/requisition-management/src/app/models/requisition/requisition.mapper.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.html
Labels: bug

#830 refactor: optimize clean-up-localizations script for projects
  scripts/clean-up-localizations.js
Labels: enhancement, nice to have

#852 fix: enable logout of punchout user in combination with SSO
  src/app/core/guards/identity-provider-logout.guard.ts
Labels: bug

#858 feat: add version method for inspecting version information
  src/polyfills.ts
Labels: enhancement, nice to have

#866 fix: use get instead of value in global variables
  src/setupJest.ts
Labels: refactoring

#871 fix: noSSR PWA Docker container does not support deep links
  templates/nginx.conf
Labels: bug

#873 feat: customizable nginx cache duration
  docs/guides/nginx-startup.md
  nginx/Dockerfile
  nginx/channel.conf.tmpl
Labels: enhancement

#882 docs: update hybrid approach ssl documentation
  docs/concepts/hybrid-approach.md
Labels: documentation

#876 fix: use translate get instead of instant for product-image component
  src/app/shared/components/product/product-image/product-image.component.spec.ts
  src/app/shared/components/product/product-image/product-image.component.ts
Labels: bug, refactoring

#881 perf: cache compiled translations in PWA process
  src/app/core/utils/translate/pwa-translate-compiler.ts
Labels: performance

#879 test(e2e): split and rewrite cost-center e2e test
  e2e/cypress/integration/specs/checkout/checkout-cost-center-multiple.b2b.e2e-spec.ts
  e2e/cypress/integration/specs/checkout/checkout-cost-center-no-costcenter.b2b.e2e-spec.ts
  e2e/cypress/integration/specs/checkout/checkout-cost-center-order.b2b.e2e-spec.ts
  e2e/cypress/integration/specs/checkout/checkout-cost-center.b2b.e2e-spec.ts
Labels: refactoring

#880 perf: prevent compiling translations with very large values
  docs/concepts/localization.md
  src/app/core/utils/translate/pwa-translate-compiler.ts
Labels: performance

#885 fix: filter with special characters
  src/app/core/utils/url-form-params.ts
Labels: bug

#884 fix: restrict product-quantity input to numbers (browser dependend)
  src/app/shared/components/product/product-quantity/product-quantity.component.html
  src/app/shared/components/product/product-quantity/product-quantity.component.spec.ts
Labels: bug

#878 chore: improve PWA REST API logging
  src/app/core/interceptors/universal-log.interceptor.ts
Labels: enhancement

#877 perf: remove individual loading of path categories
  src/app/core/store/shopping/categories/categories.effects.ts
  src/app/core/store/shopping/shopping-store.spec.ts
Labels: refactoring, performance

#841 feat: add virtual theme "all" for always overriding files
  docs/guides/customizations.md
  docs/guides/multiple-themes.md
  schematics/src/helpers/override/schema.json
  templates/webpack/webpack.custom.ts
  tslint.json
Labels: enhancement

#861 fix: enable cxml punchout with unclean user state
  src/app/core/guards/identity-provider-logout.guard.ts
  src/app/core/identity-provider/auth0.identity-provider.ts
  src/app/core/identity-provider/identity-provider.interface.ts
  src/app/extensions/punchout/pages/punchout/punchout-page.guard.ts
Labels: bug:minor

#856 feat: add option for only building specific themes in docker build
  Dockerfile
  docker-compose.yml
Labels: enhancement, nice to have

#875 feat: helper for never forgetting npm install on branch change
  .husky/post-checkout
Labels: enhancement, nice to have

#853 refactor: build and bundle docker scripts with webpack
  .dockerignore
  Dockerfile
  dist/.gitignore
  docs/guides/migrations.md
  package-lock.json
  package.json
  scripts/build-multi-pwa.js
  scripts/compile-docker-scripts.js
  src/ssr/server-scripts/.gitignore
  src/ssr/server-scripts/build-ecosystem.js
  src/ssr/server-scripts/livenessprobe.js
  src/ssr/server-scripts/prometheus.js
  src/ssr/server-scripts/readinessprobe.js
  src/ssr/server-scripts/server.js
Labels: enhancement, dependencies

#889 perf: restrict NgRx state transfer filtering to two levels
  docs/concepts/state-management.md
  src/app/core/configurations/ngrx-state-transfer.spec.ts
  src/app/core/configurations/ngrx-state-transfer.ts
Labels: documentation, performance
