Repository intershop/intershop-pwa, pull requests merged in 2021-01, with the labels that each got.

#493 fix: wrap budget-widget to approval scope
  src/app/pages/account-overview/account-overview/account-overview.component.html
Labels: bug

#497 fix: basket promotion code assignment gets lost after registration
  e2e/cypress/integration/specs/checkout/basket-handling.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/checkout/basket-promotion-handling.b2c.e2e-spec.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/core/store/customer/basket/basket.effects.ts
  src/app/core/store/customer/user/user.effects.spec.ts
  src/app/core/store/customer/user/user.effects.ts
Labels: bug

#498 fix: user registration mail always sent in english
  projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.spec.ts
  projects/organization-management/src/app/pages/user-create/user-create-page.component.spec.ts
  projects/organization-management/src/app/pages/user-create/user-create-page.component.ts
  projects/organization-management/src/app/services/users/users.service.spec.ts
  projects/organization-management/src/app/services/users/users.service.ts
  src/app/core/models/user/user.interface.ts
  src/app/core/models/user/user.mapper.ts
  src/app/core/models/user/user.model.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/pages/registration/registration-form/registration-form.component.spec.ts
  src/app/pages/registration/registration-form/registration-form.component.ts
Labels: bug:major

#499 feat: if the basket total equals 0 display only an info message on checkout payment page
  src/app/core/utils/dev/basket-mock-data.ts
  src/app/pages/checkout-payment/checkout-payment-page.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment-page.component.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#501 fix: send PGID for CMS View Context calls
  src/app/core/services/cms/cms.service.ts
Labels: bug

#508 fix: use carousel select method to set active slide
  src/app/pages/product/product-images/product-images.component.html
  src/app/pages/product/product-images/product-images.component.ts
Labels: bug

#502 feat: add order templates widget on MyAccount overview page
  e2e/cypress/integration/pages/account/my-account.page.ts
  projects/organization-management/src/app/components/budget-widget/budget-widget.component.html
  src/app/extensions/order-templates/exports/order-templates-exports.module.ts
  src/app/extensions/order-templates/facades/order-templates.facade.ts
  src/app/extensions/order-templates/order-templates.module.ts
  src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.html
  src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.spec.ts
  src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.ts
  src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.html
  src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.spec.ts
  src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.ts
  src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.html
  src/app/pages/account-overview/account-overview/account-overview.component.html
  src/app/pages/account-overview/account-overview/account-overview.component.spec.ts
  src/app/shared/components/order/order-widget/order-widget.component.html
  src/app/shared/components/order/order-widget/order-widget.component.spec.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/pages/checkout/checkout.scss
Labels: feature

#518 fix: use localStorage as storage for oauth
  src/app/core/identity-provider.module.ts
  src/app/core/identity-provider/auth0.identity-provider.ts
Labels: bug:major

#464 Feature/cybersource creditcard authorize
  src/app/pages/checkout-payment/checkout-payment-page.module.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
  src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.html
  src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.scss
  src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.spec.ts
  src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.ts
Labels: feature
