Repository intershop/intershop-pwa, pull requests merged in 2021-12, with the labels that each got.

#888 feat: SSR-only ICM call cache interceptor
  docs/guides/ssr-startup.md
  src/app/app.server.module.ts
  src/app/core/interceptors/universal-cache.interceptor.ts
  src/app/core/utils/functions.spec.ts
  src/app/core/utils/functions.ts
Labels: feature, performance

#943 fix: remove wrongly used component CSS class from 'img' tag
  src/app/shared/cms/components/cms-image-enhanced/cms-image-enhanced.component.html
Labels: bug

#945 fix: Query parameters are duplicated during multi-site nginx rewrite
  nginx/templates/multi-channel.conf.tmpl
Labels: bug

#923 refactor: rename themes - (b2b + b2c)
  .github/workflows/demo-server.yml
  .github/workflows/integration.yml
  .github/workflows/windows.yml
  angular.json
  docker-compose.yml
  docs/guides/migrations.md
  docs/guides/multi-site-configurations.md
  docs/guides/multiple-themes.md
  e2e/test-schematics-customization.sh
  nginx/README.md
  package.json
  schematics/customization/add/index.js
  schematics/src/helpers/override/factory_spec.ts
  schematics/src/helpers/override/schema.json
  src/assets/themes/b2b/img/favicon.ico
  src/assets/themes/b2b/img/logo.png
  src/assets/themes/b2b/img/logo_192x192.png
  src/assets/themes/b2b/img/logo_256x256.png
  src/assets/themes/b2b/img/logo_384x384.png
  src/assets/themes/b2b/img/logo_512x512.png
  src/assets/themes/b2b/img/logo_apple_120x120.png
  src/assets/themes/b2b/img/logo_apple_152x152.png
  src/assets/themes/b2b/img/logo_apple_167x167.png
  src/assets/themes/b2b/img/logo_apple_180x180.png
  src/assets/themes/b2b/img/logo_mobile.png
  src/assets/themes/b2b/manifest.webmanifest
  src/assets/themes/b2c/img/favicon.ico
  src/assets/themes/b2c/img/logo.png
  src/assets/themes/b2c/img/logo_192x192.png
  src/assets/themes/b2c/img/logo_256x256.png
  src/assets/themes/b2c/img/logo_384x384.png
  src/assets/themes/b2c/img/logo_512x512.png
  src/assets/themes/b2c/img/logo_apple_120x120.png
  src/assets/themes/b2c/img/logo_apple_152x152.png
  src/assets/themes/b2c/img/logo_apple_167x167.png
  src/assets/themes/b2c/img/logo_apple_180x180.png
  src/assets/themes/b2c/img/logo_mobile.png
  src/assets/themes/b2c/manifest.webmanifest
  src/environments/environment.b2b.ts
  src/environments/environment.b2c.ts
  src/index.html
  src/styles/themes/b2b/style.scss
  src/styles/themes/b2b/variables.scss
  src/styles/themes/b2c/style.scss
  src/styles/themes/b2c/variables.scss
  src/styles/themes/placeholder/style.scss
  templates/webpack/webpack.custom.ts
  tslint.json
Labels: refactoring

#952 fix: add quote to cart in case no cart exists
  src/app/extensions/quoting/services/quoting/quoting.service.spec.ts
  src/app/extensions/quoting/services/quoting/quoting.service.ts
  src/app/extensions/quoting/store/quoting/quoting.effects.spec.ts
  src/app/extensions/quoting/store/quoting/quoting.effects.ts
Labels: bug:major

#964 Fix: remove unnecessary breadcrumb data
  src/app/extensions/quoting/pages/quote-list/quote-list-page.module.ts
Labels: bug:minor

#962 bugfix: empty checkout receipt page
  src/app/core/store/customer/orders/orders.effects.spec.ts
  src/app/core/store/customer/orders/orders.effects.ts
Labels: bug

#954 refactor: feature toggle
  src/app/core/directives/feature-toggle.directive.spec.ts
  src/app/core/directives/feature-toggle.directive.ts
  src/app/core/directives/not-feature-toggle.directive.ts
  src/app/core/feature-toggle.module.ts
  src/app/core/pipes/feature-toggle.pipe.spec.ts
  src/app/core/pipes/feature-toggle.pipe.ts
  src/app/core/services/registration-form-configuration/registration-form-configuration.service.spec.ts
  src/app/core/utils/feature-toggle/feature-toggle.service.spec.ts
  src/app/core/utils/feature-toggle/feature-toggle.service.ts
  src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.spec.ts
  src/app/pages/registration/registration-page.component.spec.ts
Labels: community
