Repository intershop/intershop-pwa, pull requests merged in 2021-02, with the labels that each got.

#511 fix: preserve URLs when errors are encountered
  e2e/cypress/integration/specs/system/authentication-timeouts-anonymous.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/authentication-timeouts-loggedin.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/rest-error-handling.b2c.e2e-spec.ts
  src/app/core/guards/authorization-toggle.guard.spec.ts
  src/app/core/guards/authorization-toggle.guard.ts
  src/app/core/guards/feature-toggle.guard.spec.ts
  src/app/core/guards/feature-toggle.guard.ts
  src/app/core/guards/not-found-status.guard.ts
  src/app/core/store/core/error/error.effects.ts
  src/app/core/store/core/router/router.reducer.ts
  src/app/core/store/shopping/categories/categories.effects.spec.ts
  src/app/core/store/shopping/categories/categories.effects.ts
  src/app/core/store/shopping/products/products.effects.spec.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/search/search.effects.spec.ts
  src/app/core/store/shopping/search/search.effects.ts
  src/app/core/utils/http-status-code/http-status-code.service.spec.ts
  src/app/core/utils/http-status-code/http-status-code.service.ts
  src/app/pages/app-last-routing.module.ts
Labels: refactoring

#515 feat: devcontainer for VSCode
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  angular.json
  docs/guides/getting-started.md
  package.json
Labels: feature

#530 feat: improve styling of hierarchy switch selectbox
  projects/organization-management/src/app/store/organization-hierarchies/organization-hierarchies.effects.ts
  src/app/core/configuration.module.ts
  src/app/core/utils/http-error/organization.error-handler.ts
  src/app/extensions/organization-hierarchies/interceptors/tx-selected-group.interceptor.spec.ts
  src/app/extensions/organization-hierarchies/shared/hierarchy-switch/hierarchy-switch.component.html
  src/app/extensions/organization-hierarchies/shared/hierarchy-switch/hierarchy-switch.component.spec.ts
  src/app/extensions/organization-hierarchies/shared/hierarchy-switch/hierarchy-switch.component.ts
  src/app/extensions/organization-hierarchies/store/group/group.selectors.ts
  src/app/extensions/wishlists/shared/wishlists-link/wishlists-link.component.html
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.spec.ts
  src/app/shared/components/order/order-list/order-list.component.spec.ts
  src/app/shell/header/login-status/login-status.component.html
  src/app/shell/header/login-status/login-status.component.spec.ts
  src/app/shell/header/login-status/login-status.component.ts
  src/app/shell/header/product-compare-status/product-compare-status.component.html
  src/app/shell/header/product-compare-status/product-compare-status.component.spec.ts
  src/styles/components/header/header.scss
  src/styles/components/header/hierarchy-switch.scss
  src/styles/main.scss
Labels: feature

#533 chore: publish reports to azure
  .github/workflows/reports.yml
  Dockerfile_reports
  reports/index.html
  reports/tslint-gitlab.js
  reports/tslint-report.js
Labels: enhancement

#535 feat: display ICM managed display names for sorting keys on listings
  src/app/core/models/product-listing/product-listing.mapper.spec.ts
  src/app/core/models/product-listing/product-listing.mapper.ts
  src/app/core/models/product-listing/product-listing.model.ts
  src/app/core/services/filter/filter.service.spec.ts
  src/app/core/services/filter/filter.service.ts
  src/app/core/services/products/products.service.spec.ts
  src/app/core/services/products/products.service.ts
  src/app/core/store/shopping/filter/filter.effects.spec.ts
  src/app/core/store/shopping/filter/filter.effects.ts
  src/app/core/store/shopping/product-listing/product-listing.selectors.spec.ts
  src/app/core/store/shopping/product-listing/product-listing.selectors.ts
  src/app/core/store/shopping/products/products.effects.spec.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/search/search.effects.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.html
  src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.spec.ts
  src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.ts
  src/app/shared/components/product/product-listing/product-listing.component.html
Labels: enhancement

#540 feat: use seo metadata provided by CMS REST API for content pages
  src/app/core/models/content-pagelet-entry-point/__snapshots__/content-pagelet-entry-point.mapper.spec.ts.snap
  src/app/core/models/content-pagelet-entry-point/content-pagelet-entry-point.mapper.spec.ts
  src/app/core/models/content-pagelet-entry-point/content-pagelet-entry-point.mapper.ts
  src/app/core/models/content-pagelet-entry-point/content-pagelet-entry-point.model.ts
  src/app/core/models/content-view/content-view.model.spec.ts
  src/app/core/models/content-view/content-view.model.ts
  src/app/core/models/seo-attributes/seo-attributes.mapper.spec.ts
  src/app/core/models/seo-attributes/seo-attributes.mapper.ts
  src/app/core/services/cms/cms.service.ts
  src/app/core/store/content/content-store.spec.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
Labels: enhancement

#538 feat: deploy PWA without SSR
  .dockerignore
  .prettierignore
  Dockerfile
  Dockerfile_noSSR
  docker-compose.yml
  docs/concepts/deployment-angular.md
  nginx/channel.conf.tmpl
  templates/nginx.conf
Labels: enhancement

#547 chore: revert solution style tsconfig
  Dockerfile
  Dockerfile_noSSR
  angular.json
  package-lock.json
  package.json
  projects/organization-management/tsconfig.app.json
  schematics/src/utils/lint-fix.ts
  tsconfig.all.json
  tsconfig.app.json
  tsconfig.base.json
  tsconfig.json
  tsconfig.server.json
  tsconfig.spec.json
  tslint-rules/src/ishUsefulImportsRule.ts
Labels: refactoring

#539 refactor: move gtm token to tracking store
  src/app/core/extras.module.ts
  src/app/core/store/core/configuration/configuration.actions.ts
  src/app/core/store/core/configuration/configuration.effects.spec.ts
  src/app/core/store/core/configuration/configuration.effects.ts
  src/app/core/store/core/configuration/configuration.reducer.ts
  src/app/core/store/core/configuration/configuration.selectors.spec.ts
  src/app/core/store/core/configuration/configuration.selectors.ts
  src/app/extensions/sentry/store/sentry-config/sentry-config.reducer.ts
  src/app/extensions/sentry/store/sentry-config/sentry-config.selectors.ts
  src/app/extensions/sentry/store/sentry-store.module.ts
  src/app/extensions/sentry/store/sentry-store.ts
  src/app/extensions/tracking/exports/tracking-exports.module.ts
  src/app/extensions/tracking/store/tracking-config/tracking-config.actions.ts
  src/app/extensions/tracking/store/tracking-config/tracking-config.effects.ts
  src/app/extensions/tracking/store/tracking-config/tracking-config.reducer.ts
  src/app/extensions/tracking/store/tracking-config/tracking-config.selectors.ts
  src/app/extensions/tracking/store/tracking-store.module.ts
  src/app/extensions/tracking/store/tracking-store.ts
  src/app/extensions/tracking/tracking.module.ts
  templates/webpack/webpack.custom.ts
Labels: refactoring

#553 perf: main bundle reduction
  angular.json
  projects/organization-management/src/app.module.ts
  projects/organization-management/src/app/exports/index.ts
  projects/organization-management/src/app/organization-management.module.ts
  projects/organization-management/src/app/pages/organization-management-routing.module.ts
  projects/organization-management/src/app/pages/user-create/user-create-page.module.ts
  projects/organization-management/src/app/pages/user-detail/user-detail-page.module.ts
  projects/organization-management/src/app/pages/user-edit-budget/user-edit-budget-page.module.ts
  projects/organization-management/src/app/pages/user-edit-profile/user-edit-profile-page.module.ts
  projects/organization-management/src/app/pages/user-edit-roles/user-edit-roles-page.module.ts
  projects/organization-management/src/app/pages/users/users-page.module.ts
  projects/organization-management/src/app/services/organization-management-breadcrumb/organization-management-breadcrumb.service.spec.ts
  projects/organization-management/tsconfig.app.json
  projects/requisition-management/src/app.module.ts
  projects/requisition-management/src/app/exports/index.ts
  projects/requisition-management/src/app/pages/approver/approver-page.module.ts
  projects/requisition-management/src/app/pages/buyer/buyer-page.module.ts
  projects/requisition-management/src/app/pages/requisition-detail/budget-bar/budget-bar.component.html
  projects/requisition-management/src/app/pages/requisition-detail/budget-bar/budget-bar.component.scss
  projects/requisition-management/src/app/pages/requisition-detail/budget-bar/budget-bar.component.spec.ts
  projects/requisition-management/src/app/pages/requisition-detail/budget-bar/budget-bar.component.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.html
  projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.spec.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-detail-page.component.spec.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-detail-page.module.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-reject-dialog/requisition-reject-dialog.component.html
  projects/requisition-management/src/app/pages/requisition-detail/requisition-reject-dialog/requisition-reject-dialog.component.spec.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-reject-dialog/requisition-reject-dialog.component.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-summary/requisition-summary.component.html
  projects/requisition-management/src/app/pages/requisition-detail/requisition-summary/requisition-summary.component.spec.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-summary/requisition-summary.component.ts
  projects/requisition-management/src/app/pages/requisition-management-routing.module.ts
  projects/requisition-management/src/app/requisition-management.module.ts
  projects/requisition-management/src/app/services/requisition-management-breadcrumb/requisition-management-breadcrumb.service.spec.ts
  projects/requisition-management/tsconfig.app.json
  src/app/pages/account/account-page.module.ts
  src/app/shared/shared.module.ts
  tslint.json
Labels: enhancement

#560 chore: fix dead link
  docs/guides/cookie-consent.md
Labels: documentation

#536 feat: multi-channel with multi ICM support
  docs/guides/nginx-startup.md
  nginx/channel.conf.tmpl
  src/app/core/configurations/configuration.meta.ts
Labels: enhancement

#559 fix: crossed prices in checkout items widget
  src/app/shared/components/basket/basket-items-summary/basket-items-summary.component.html
Labels: bug

#565 chore: adapt copyright notice
  LICENSE
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#566 perf: move formly to lazy bundle
  src/app/core/core.module.ts
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.module.ts
  src/app/pages/checkout-shipping/checkout-shipping-page.module.ts
  src/app/pages/registration/registration-page.module.ts
  src/app/shared/formly/formly.module.ts
  src/app/shared/shared.module.ts
Labels: refactoring

#567 perf: move sentry to lazy loaded bundle by lazy invocation
  src/app/core/utils/default-error-handler.ts
  src/app/extensions/tacton/store/tacton-config/tacton-config.selectors.ts
  src/app/pages/account/account-user-info/account-user-info.component.ts
  tslint.json
Labels: enhancement

#568 perf: shell as standalone module
  schematics/src/extension/factory.ts
  schematics/src/extension/factory_spec.ts
  schematics/src/lazy-component/factory_spec.ts
  schematics/src/store/factory_spec.ts
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/core/core.module.ts
  src/app/core/models/search-box-configuration/search-box-configuration.model.ts
  src/app/core/pipes.module.ts
  src/app/core/utils/module-loader/module-loader.service.ts
  src/app/pages/error/error/error.component.spec.ts
  src/app/pages/search/search-no-result/search-no-result.component.spec.ts
  src/app/shared/components/search/search-box/search-box.component.html
  src/app/shared/components/search/search-box/search-box.component.spec.ts
  src/app/shared/components/search/search-box/search-box.component.ts
  src/app/shared/shared.module.ts
  src/app/shell/footer/footer/footer.component.html
  src/app/shell/footer/footer/footer.component.spec.ts
  src/app/shell/header/header-default/__snapshots__/header-default.component.spec.ts.snap
  src/app/shell/header/header-default/header-default.component.html
  src/app/shell/header/header-default/header-default.component.spec.ts
  src/app/shell/shell.module.ts
  tslint.json
Labels: refactoring

#571 fix: prevent calling forkJoin with empty array for wishlists and order templates
  src/app/extensions/order-templates/services/order-template/order-template.service.ts
  src/app/extensions/wishlists/services/wishlist/wishlist.service.ts
Labels: bug

#569 build: consistently set service-worker activation with custom webpack…
  angular.json
  docs/concepts/configuration.md
  e2e/test-schematics.sh
  schematics/customization/service-worker/index.js
  scripts/init-local-environment.js
  src/app/core/core.module.ts
  src/environments/environment.model.ts
  src/typings.d.ts
  templates/webpack/webpack.custom.ts
  tslint.json
Labels: refactoring

#552 refactor: use native swiper instead of ngx-swiper-wrapper
  angular.json
  docs/guides/migrations.md
  package-lock.json
  package.json
  src/app/core/appearance.module.ts
  src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.html
  src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.spec.ts
  src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.ts
  src/app/pages/product/product-links-carousel/product-links-carousel.component.html
  src/app/pages/product/product-links-carousel/product-links-carousel.component.spec.ts
  src/app/pages/product/product-links-carousel/product-links-carousel.component.ts
  src/app/pages/product/product-links/product-links.component.html
  src/app/pages/product/product-links/product-links.component.ts
  src/app/shared/shared.module.ts
  src/styles/global/swiper.scss
  src/styles/main.scss
Labels: enhancement

#562 perf: purgecss webpack build
  Dockerfile
  Dockerfile_noSSR
  angular.json
  docs/guides/optimizations.md
  package-lock.json
  package.json
  purgecss.config.js
  src/styles/pages/content-pages/page-content.scss
  templates/webpack/webpack.custom.ts
Labels: enhancement

#575 feat: add order template detail links on order template widget
  src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.html
  src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.spec.ts
Labels: feature

#570 perf: restructure chunk splitting for features
  schematics/src/extension/files/__name@dasherize__/exports/__name@dasherize__-exports.module.ts.template
  src/app/core/utils/module-loader/module-loader.service.ts
  src/app/extensions/order-templates/exports/order-templates-exports.module.ts
  src/app/extensions/punchout/exports/punchout-exports.module.ts
  src/app/extensions/quoting/exports/quoting-exports.module.ts
  src/app/extensions/sentry/exports/sentry-exports.module.ts
  src/app/extensions/tacton/exports/tacton-exports.module.ts
  src/app/extensions/tracking/exports/tracking-exports.module.ts
  src/app/extensions/wishlists/exports/wishlists-exports.module.ts
  templates/webpack/webpack.custom.ts
Labels: enhancement

#581 refactor: mark budget widget for automatic lazy component generation
  projects/organization-management/src/app/components/budget-widget/budget-widget.component.ts
  projects/organization-management/src/app/exports/.gitignore
  projects/organization-management/src/app/exports/lazy-budget-widget/lazy-budget-widget.component.html
  projects/organization-management/src/app/exports/lazy-budget-widget/lazy-budget-widget.component.ts
Labels: refactoring
