Repository intershop/intershop-pwa, pull requests merged in 2021-06, with the labels that each got.

#712 fix: correct french localization values
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#695 feat : load translations from icm
  .gitignore
  docs/concepts/localization.md
  package-lock.json
  package.json
  scripts/convert-to-xliff.js
  src/app/app.server.module.ts
  src/app/core/configurations/state-keys.ts
  src/app/core/internationalization.module.ts
  src/app/core/store/core/configuration/configuration.effects.spec.ts
  src/app/core/store/core/configuration/configuration.effects.ts
Labels: enhancement

#713 fix: breadcrumb styling harmonization
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.html
  src/app/pages/contact/contact-page.component.html
  src/app/pages/product/product-page.component.html
  src/app/pages/recently/recently-page.component.html
  src/app/pages/recently/recently-page.component.spec.ts
  src/app/pages/recently/recently-viewed-all/recently-viewed-all.component.html
  src/app/pages/recently/recently-viewed-all/recently-viewed-all.component.spec.ts
  src/app/pages/search/search-no-result/search-no-result.component.html
  src/app/pages/search/search-no-result/search-no-result.component.spec.ts
  src/app/pages/search/search-page.component.html
  src/app/pages/search/search-page.component.spec.ts
  src/styles/global/breadcrumbs.scss
  src/styles/pages/account/account.scss
  src/styles/pages/category/search-result.scss
  src/styles/pages/productdetail/productdetail.scss
Labels: bug

#655 feat: load translations with webpack
  docs/concepts/configuration.md
  src/app/app.server.module.ts
  src/app/core/internationalization.module.ts
  templates/webpack/webpack.custom.ts
Labels: enhancement

#659 feat: improve detecting missing translations
  src/app/app.server.module.ts
  src/app/core/configurations/ngrx-state-transfer.ts
  src/app/core/configurations/state-keys.ts
  src/app/core/internationalization.module.ts
  src/app/core/services/localizations/localizations.service.spec.ts
  src/app/core/services/localizations/localizations.service.ts
  src/app/core/store/core/configuration/configuration.actions.ts
  src/app/core/store/core/configuration/configuration.effects.spec.ts
  src/app/core/store/core/configuration/configuration.effects.ts
  src/app/core/store/core/configuration/configuration.integration.spec.ts
  src/app/core/store/core/configuration/configuration.reducer.ts
  src/app/core/store/core/configuration/configuration.selectors.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/core/utils/translate/fallback-missing-translation-handler.ts
  src/app/core/utils/translate/icm-translate-loader.ts
  src/app/core/utils/translate/translations.type.ts
Labels: enhancement

#709 feat: individual page sizes for listings
  src/app/core/configurations/injection-keys.ts
  src/app/core/models/product-listing/product-listing.mapper.spec.ts
  src/app/core/models/product-listing/product-listing.mapper.ts
  src/app/core/services/filter/filter.service.spec.ts
  src/app/core/services/filter/filter.service.ts
  src/app/core/services/products/products.service.ts
  src/app/core/store/content/parameters/parameters.effects.spec.ts
  src/app/core/store/content/parameters/parameters.effects.ts
  src/app/core/store/shopping/filter/filter.effects.spec.ts
  src/app/core/store/shopping/filter/filter.effects.ts
  src/app/core/store/shopping/product-listing/product-listing.actions.ts
  src/app/core/store/shopping/product-listing/product-listing.effects.spec.ts
  src/app/core/store/shopping/product-listing/product-listing.reducer.ts
  src/app/core/store/shopping/product-listing/product-listing.selectors.ts
  src/app/core/store/shopping/products/products.effects.spec.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/search/search.effects.spec.ts
  src/app/core/store/shopping/search/search.effects.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/environments/environment.model.ts
Labels: enhancement

#714 feat: enable the b2b customer to enter an order reference id during checkout
  src/app/core/utils/dev/basket-mock-data.ts
  src/app/pages/checkout-review/checkout-review/checkout-review.component.html
  src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.html
  src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.spec.ts
  src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.ts
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.html
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.spec.ts
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.ts
  src/app/shared/components/basket/basket-order-reference/basket-order-reference.component.html
  src/app/shared/components/basket/basket-order-reference/basket-order-reference.component.spec.ts
  src/app/shared/components/basket/basket-order-reference/basket-order-reference.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#719 feat: replace i18nPlural pipe usage with translate compiler
  docs/concepts/localization.md
  projects/requisition-management/src/app/components/requisitions-list/requisitions-list.component.html
  projects/requisition-management/src/app/components/requisitions-list/requisitions-list.component.spec.ts
  src/app/core/internationalization.module.ts
  src/app/core/utils/translate/pwa-translate-compiler.spec.ts
  src/app/core/utils/translate/pwa-translate-compiler.ts
  src/app/core/utils/translate/translations.type.ts
  src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.html
  src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.spec.ts
  src/app/extensions/wishlists/pages/account-wishlist/account-wishlist-list/account-wishlist-list.component.html
  src/app/pages/search/search-result/search-result.component.html
  src/app/shared/components/product/product-list-toolbar/product-list-toolbar.component.html
  src/app/shell/header/mini-basket/mini-basket.component.html
  src/app/shell/header/mini-basket/mini-basket.component.spec.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement

#728 fix: double-check missing translation before reporting
  src/app/core/utils/translate/fallback-missing-translation-handler.ts
Labels: bug

#715 chore: adapt demo multisite config
  docker-compose.yml
  docs/README.md
  docs/concepts/multi-site-handling.md
  docs/guides/multi-site-configurations.md
  docs/guides/nginx-startup.md
Labels: enhancement

#677 feat: basic auth support for nginx
  docker-compose.yml
  docs/guides/multi-site-configurations.md
  docs/guides/nginx-startup.md
  nginx/Dockerfile
  nginx/channel.conf.tmpl
  nginx/entrypoint.sh
Labels: feature

#732 deps: upgrade cypress to 7.x
  e2e/package.json
Labels: dependencies

#710 Formly: Checkout Review Page
  src/app/pages/checkout-review/checkout-review-page.module.ts
  src/app/pages/checkout-review/checkout-review/checkout-review.component.html
  src/app/pages/checkout-review/checkout-review/checkout-review.component.spec.ts
  src/app/pages/checkout-review/checkout-review/checkout-review.component.ts
  src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.html
  src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.spec.ts
  src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.ts
Labels: refactoring

#736 fix: quick order - enable the add-to-cart button after a valid csv file has been selected
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.html
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.ts
Labels: bug

#741 fix: display edit line item link only for variation products
  src/app/shared/components/line-item/line-item-edit/line-item-edit.component.html
Labels: bug:minor

#735 fix: don't display multiple bucket message after redirect before checkout
  src/app/pages/checkout-review/checkout-review/checkout-review.component.ts
  src/app/shared/components/basket/basket-address-summary/basket-address-summary.component.html
Labels: bug:minor

#744 fix: don`t display payment costs on checkout payment page if the value is zero
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
Labels: bug:minor

#751 fix: adapt project SCSS definitions in regards to sass '/' deprecation warnings
  src/styles/components/cookies.scss
  src/styles/components/footer/footer.scss
  src/styles/components/header/header.scss
  src/styles/components/header/language-switch.scss
  src/styles/components/header/main-navigation.scss
  src/styles/components/header/search-container.scss
  src/styles/components/header/user-information-mobile.scss
  src/styles/global/breadcrumbs.scss
  src/styles/global/buttons.scss
  src/styles/global/forms/fields.scss
  src/styles/global/forms/forms.scss
  src/styles/global/forms/labels.scss
  src/styles/global/global.scss
  src/styles/global/icons.scss
  src/styles/global/line-item.scss
  src/styles/global/lists.scss
  src/styles/global/notifications.scss
  src/styles/global/panel.scss
  src/styles/global/promotions.scss
  src/styles/global/share-tools.scss
  src/styles/global/tables.scss
  src/styles/global/toasts.scss
  src/styles/pages/account/account-navigation.scss
  src/styles/pages/category/filter-panel.scss
  src/styles/pages/category/filter-row.scss
  src/styles/pages/category/product-list.scss
  src/styles/pages/checkout/checkout.scss
  src/styles/pages/checkout/progress-bar.scss
  src/styles/pages/checkout/quick-cart.scss
  src/styles/pages/checkout/shopping-cart.scss
  src/styles/pages/content-pages/page-content.scss
  src/styles/pages/homepage/homepage.scss
  src/styles/pages/payment/payment.scss
  src/styles/pages/productdetail/product-images.scss
  src/styles/pages/productdetail/product-info.scss
  src/styles/pages/productdetail/productdetail.scss
  src/styles/pages/productdetail/rating.scss
Labels: dependencies

#750 feat: forward mouse event to callback handler in server-html directive
  src/app/core/directives/server-html.directive.ts
Labels: enhancement

#753 test: simplify router action serialize
  src/app/core/store/core/router/router.integration.spec.ts
  src/app/core/store/core/server-config/server-config.effects.spec.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/jest-serializer/NgrxActionSerializer.js
Labels: refactoring

#755 fix: add support for CMS component "Product List (Filter)" - use correct scope configuration
  src/app/core/facades/cms.facade.ts
Labels: bug
