Repository intershop/intershop-pwa, pull requests merged in 2021-07, with the labels that each got.

#722 feat: language switch with multisite support
  docker-compose.yml
  docs/guides/multi-site-configurations.md
  docs/guides/ssr-startup.md
  src/app/core/pipes/make-href.pipe.spec.ts
  src/app/core/pipes/make-href.pipe.ts
  src/app/core/store/core/configuration/configuration.effects.spec.ts
  src/app/core/store/core/configuration/configuration.effects.ts
  src/app/core/store/core/configuration/configuration.reducer.ts
  src/app/core/store/core/configuration/configuration.selectors.ts
  src/app/core/utils/multi-site/multi-site.service.spec.ts
  src/app/core/utils/multi-site/multi-site.service.ts
  src/app/shell/header/language-switch/language-switch.component.html
  src/app/shell/header/language-switch/language-switch.component.spec.ts
  src/environments/environment.model.ts
  tslint-rules/src/useCamelCaseEnvironmentPropertiesRule.ts
Labels: feature

#763 fix: incorrect product label display on product detail page (#762)
  src/app/core/facades/product-context.facade.spec.ts
  src/app/core/facades/product-context.facade.ts
  src/styles/pages/category/product-list.scss
Labels: bug

#760 fix: repair npm run start:local
  .github/workflows/integration.yml
  angular.json
  e2e/test-schematics.sh
  templates/webpack/webpack.custom.ts
Labels: bug

#746 refactor: enable multiple currencies
  docs/concepts/configuration.md
  docs/guides/migrations.md
  docs/guides/multi-site-configurations.md
  e2e/cypress/integration/specs/system/change-language-authentication.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/change-language-family-page.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/change-language-hompage.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/change-language-product-detail.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/change-language-search-result.b2c.e2e-spec.ts
  nginx/channel.conf.tmpl
  projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.spec.ts
  projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.ts
  projects/organization-management/src/app/services/users/users.service.spec.ts
  projects/organization-management/src/app/services/users/users.service.ts
  scripts/clean-up-localizations.js
  server.ts
  src/app/core/configurations/configuration.meta.ts
  src/app/core/facades/app.facade.ts
  src/app/core/models/content-configuration-parameter/content-configuration-parameter.mapper.spec.ts
  src/app/core/models/content-configuration-parameter/content-configuration-parameter.mapper.ts
  src/app/core/models/locale/locale.model.ts
  src/app/core/services/api/api.service.spec.ts
  src/app/core/services/api/api.service.ts
  src/app/core/services/configuration/configuration.service.ts
  src/app/core/services/order/order.service.spec.ts
  src/app/core/services/order/order.service.ts
  src/app/core/services/payment/payment.service.spec.ts
  src/app/core/services/payment/payment.service.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/core/store/core/configuration/configuration.effects.ts
  src/app/core/store/core/configuration/configuration.integration.spec.ts
  src/app/core/store/core/configuration/configuration.reducer.ts
  src/app/core/store/core/configuration/configuration.selectors.spec.ts
  src/app/core/store/core/configuration/configuration.selectors.ts
  src/app/core/store/hybrid/hybrid.selectors.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
  src/app/pages/account-profile-user/account-profile-user-page.component.ts
  src/app/shared/forms/utils/forms.service.ts
  src/app/shell/header/language-switch/language-switch.component.html
  src/app/shell/header/language-switch/language-switch.component.spec.ts
  src/app/shell/header/language-switch/language-switch.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/environments/environment.model.ts
Labels: enhancement, refactoring

#768 Add Azure CI pipeline
  .azure/azure-pipelines.yml
Labels: feature

#769 fix: styling issue concerning mobile language switch (#769)
  templates/webpack/webpack.custom.ts
Labels: bug

#777 fix: set canonical link and 'og:url' info independent from SSR container context to 'https'
  e2e/test-universal.sh
  src/app/extensions/seo/store/seo/seo.effects.ts
Labels: bug

#781 refactor: typing improvements
  projects/requisition-management/src/app/pages/requisition-detail/budget-bar/budget-bar.component.spec.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.spec.ts
  src/app/core/services/api/api.service.errorhandler.spec.ts
  src/app/core/services/api/api.service.spec.ts
  src/app/core/services/cms/cms.service.spec.ts
  src/app/core/store/shopping/products/products.selectors.ts
  src/app/pages/search/search-result/search-result.component.spec.ts
  src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.spec.ts
  src/setupJest.ts
Labels: refactoring

#780 refactor: use translation interpolation for punchout keys
  scripts/clean-up-localizations.js
  src/app/core/utils/translate/pwa-translate-compiler.spec.ts
  src/app/core/utils/translate/pwa-translate-compiler.ts
  src/app/extensions/punchout/pages/account-punchout-create/account-punchout-create-page.component.html
  src/app/extensions/punchout/pages/account-punchout-create/account-punchout-create-page.component.ts
  src/app/extensions/punchout/pages/account-punchout/account-punchout-header/account-punchout-header.component.html
  src/app/extensions/punchout/pages/account-punchout/account-punchout-header/account-punchout-header.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout/account-punchout-page.component.html
  src/app/extensions/punchout/pages/account-punchout/account-punchout-page.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature, refactoring

#773 feat: disable ngrx Store Devtools in production environments
  angular.json
  scripts/find-dead-code.ts
  src/app/core/state-management.module.ts
  src/app/core/store/store-devtools.module.production.ts
  src/app/core/store/store-devtools.module.ts
  tslint.json
Labels: feature

#787 style: enable prettier for dist scripts
  .prettierignore
  dist/healthcheck.js
Labels: enhancement

#788 refactor: incorporate api error handler into api service
  src/app/core/services/api/api.service.errorhandler.spec.ts
  src/app/core/services/api/api.service.errorhandler.ts
  src/app/core/services/api/api.service.spec.ts
  src/app/core/services/api/api.service.ts
Labels: refactoring

#772 refactor: adapt checkout shipping page with formly
  src/app/core/facades/checkout.facade.spec.ts
  src/app/core/facades/checkout.facade.ts
  src/app/core/utils/dev/basket-mock-data.ts
  src/app/pages/checkout-shipping/checkout-shipping-page.component.html
  src/app/pages/checkout-shipping/checkout-shipping-page.component.spec.ts
  src/app/pages/checkout-shipping/checkout-shipping-page.component.ts
  src/app/pages/checkout-shipping/checkout-shipping-page.module.ts
  src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.html
  src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.spec.ts
  src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.ts
  src/app/pages/checkout-shipping/formly/shipping-info/shipping-info.component.html
  src/app/pages/checkout-shipping/formly/shipping-info/shipping-info.component.spec.ts
  src/app/pages/checkout-shipping/formly/shipping-info/shipping-info.component.ts
  src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.html
  src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.spec.ts
  src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.ts
  src/app/shared/formly/dev/testing/formly-testing.module.ts
  src/app/shared/formly/wrappers/radio-horizontal-wrapper/radio-horizontal-wrapper.component.html
  src/styles/global/forms/forms.scss
Labels: refactoring

#790 deps: define compodoc as project development dependency with fixed version
  package-lock.json
  package.json
Labels: dependencies

#796 fix: display an error message in case the customer creation failed
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#785 feat: refactor wishlist modal with formly
  docs/guides/formly.md
  e2e/cypress/integration/pages/account/add-to-wishlist.module.ts
  e2e/cypress/integration/pages/account/wishlists-details.page.ts
  src/app/extensions/wishlists/facades/wishlists.facade.ts
  src/app/extensions/wishlists/shared/select-wishlist-form/select-wishlist-form.component.html
  src/app/extensions/wishlists/shared/select-wishlist-form/select-wishlist-form.component.spec.ts
  src/app/extensions/wishlists/shared/select-wishlist-form/select-wishlist-form.component.ts
  src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.html
  src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.spec.ts
  src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.ts
  src/app/extensions/wishlists/wishlists.module.ts
  src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.ts
  src/app/shared/formly/components/validation-icons/validation-icons.component.ts
  src/app/shared/formly/dev/testing/formly-testing.module.ts
  src/app/shared/formly/formly.module.ts
  src/app/shared/formly/types/radio-field/radio-field.component.html
  src/app/shared/formly/wrappers/horizontal-checkbox-wrapper/horizontal-checkbox-wrapper.component.html
  src/app/shared/formly/wrappers/radio-horizontal-wrapper/radio-horizontal-wrapper.component.html
  src/app/shared/formly/wrappers/radio-horizontal-wrapper/radio-horizontal-wrapper.component.spec.ts
  src/app/shared/formly/wrappers/radio-horizontal-wrapper/radio-horizontal-wrapper.component.ts
  src/app/shared/formly/wrappers/validation-wrapper/validation-wrapper.component.html
  src/styles/global/forms/formly.scss
Labels: refactoring

#792 refactor: adapt order template modal with formly
  e2e/cypress/integration/pages/account/add-to-order-template.module.ts
  e2e/cypress/integration/pages/account/order-templates-details.page.ts
  src/app/extensions/order-templates/facades/order-templates.facade.ts
  src/app/extensions/order-templates/order-templates.module.ts
  src/app/extensions/order-templates/shared/select-order-template-form/select-order-template-form.component.html
  src/app/extensions/order-templates/shared/select-order-template-form/select-order-template-form.component.spec.ts
  src/app/extensions/order-templates/shared/select-order-template-form/select-order-template-form.component.ts
  src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.html
  src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.spec.ts
  src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.ts
Labels: refactoring

#795 refactor: use formly to create the save-for-later checkbox on checkout payment page
  e2e/cypress/integration/pages/checkout/checkout-payment.page.ts
  src/app/pages/checkout-payment/checkout-payment-page.module.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
  src/app/pages/checkout-payment/formly/payment-save-checkbox/payment-save-checkbox.component.html
  src/app/pages/checkout-payment/formly/payment-save-checkbox/payment-save-checkbox.component.spec.ts
  src/app/pages/checkout-payment/formly/payment-save-checkbox/payment-save-checkbox.component.ts
  src/app/pages/checkout-payment/payment-concardis-creditcard/payment-concardis-creditcard.component.html
  src/app/pages/checkout-payment/payment-concardis-creditcard/payment-concardis-creditcard.component.spec.ts
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.html
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.spec.ts
  src/app/pages/checkout-payment/payment-concardis/payment-concardis.component.ts
  src/app/pages/checkout-payment/payment-parameter-form/payment-parameter-form.component.html
  src/app/pages/checkout-payment/payment-parameter-form/payment-parameter-form.component.spec.ts
  src/styles/pages/payment/payment.scss
Labels: refactoring

#798 fix: checkout shipping selection error and test
  src/app/pages/checkout-shipping/checkout-shipping-page.component.html
  src/app/pages/checkout-shipping/checkout-shipping-page.component.spec.ts
  src/app/pages/checkout-shipping/checkout-shipping-page.component.ts
Labels: bug:minor

#797 Refactor/unify and add translation keys for general error messages
  docs/guides/formly.md
  projects/organization-management/src/app/components/user-profile-form/user-profile-form.component.ts
  src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
  src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.ts
  src/app/pages/account-profile-email/account-profile-email/account-profile-email.component.ts
  src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.ts
  src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.ts
  src/app/pages/contact/contact-form/contact-form.component.ts
  src/app/pages/forgot-password/request-reminder-form/request-reminder-form.component.ts
  src/app/pages/forgot-password/update-password-form/update-password-form.component.ts
  src/app/shared/components/login/login-form/login-form.component.ts
  src/app/shared/formly/types/email-field/email-field.component.html
  src/app/shared/formly/types/email-field/email-field.component.ts
  src/app/shared/formly/types/password-field/password-field.component.ts
  src/app/shared/formly/types/phone-field/phone-field.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement

#801 feat: add translate-placeholder extension and use it
  docs/guides/formly.md
  src/app/extensions/quickorder/shared/direct-order/direct-order.component.ts
  src/app/shared/formly/extensions/translate-placeholder.extension.ts
  src/app/shared/formly/formly.module.ts
Labels: feature

#800 refactor: adapt account-address component with formly
  src/app/pages/account-addresses/account-addresses-page.component.html
  src/app/pages/account-addresses/account-addresses-page.component.ts
  src/app/pages/account-addresses/account-addresses/account-addresses.component.html
  src/app/pages/account-addresses/account-addresses/account-addresses.component.spec.ts
  src/app/pages/account-addresses/account-addresses/account-addresses.component.ts
  src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.spec.ts
  src/app/shared/components/checkout/basket-invoice-address-widget/basket-invoice-address-widget.component.ts
  src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.spec.ts
  src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.ts
  src/app/shared/forms/utils/forms.service.spec.ts
  src/app/shared/forms/utils/forms.service.ts
Labels: refactoring

#752 feat: quickorder rework
  e2e/cypress/integration/pages/quickorder/quickorder.page.ts
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.html
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.spec.ts
  src/app/extensions/quickorder/pages/quickorder/quickorder-page.component.ts
  src/app/extensions/quickorder/quickorder.module.ts
  src/app/extensions/quickorder/shared/direct-order/direct-order.component.ts
  src/app/extensions/quickorder/shared/quickorder-add-products-form/quickorder-add-products-form.component.html
  src/app/extensions/quickorder/shared/quickorder-add-products-form/quickorder-add-products-form.component.spec.ts
  src/app/extensions/quickorder/shared/quickorder-add-products-form/quickorder-add-products-form.component.ts
  src/app/extensions/quickorder/shared/quickorder-csv-form/quickorder-csv-form.component.html
  src/app/extensions/quickorder/shared/quickorder-csv-form/quickorder-csv-form.component.spec.ts
  src/app/extensions/quickorder/shared/quickorder-csv-form/quickorder-csv-form.component.ts
  src/app/extensions/quickorder/shared/quickorder-repeat-form-quantity/quickorder-repeat-form-quantity.component.html
  src/app/extensions/quickorder/shared/quickorder-repeat-form-quantity/quickorder-repeat-form-quantity.component.spec.ts
  src/app/extensions/quickorder/shared/quickorder-repeat-form-quantity/quickorder-repeat-form-quantity.component.ts
  src/app/extensions/quickorder/shared/quickorder-repeat-form/quickorder-repeat-form.component.html
  src/app/extensions/quickorder/shared/quickorder-repeat-form/quickorder-repeat-form.component.spec.ts
  src/app/extensions/quickorder/shared/quickorder-repeat-form/quickorder-repeat-form.component.ts
  src/app/shared/components/product/product-quantity/product-quantity.component.html
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/global/global.scss
Labels: enhancement
