Repository intershop/intershop-pwa, pull requests merged in 2021-05, with the labels that each got.

#654 feat: add feature toggle for guest checkout
  docs/guides/migrations.md
  e2e/cypress/integration/pages/checkout/checkout-addresses.page.ts
  e2e/cypress/integration/specs/checkout/register-before-checkout.b2c.e2e-spec.ts
  scripts/init-local-environment.js
  src/app/core/services/registration-form-configuration/registration-form-configuration.service.spec.ts
  src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
  src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.html
  src/app/pages/checkout-address/checkout-address-anonymous/checkout-address-anonymous.component.spec.ts
  src/environments/environment.model.ts
Labels: enhancement, feature

#644 fix: auth0 silentRefresh requires offline_access scope
  src/app/core/identity-provider/auth0.identity-provider.ts
Labels: bug

#670 feat/b2b sso invite
  docs/guides/migrations.md
  projects/organization-management/src/app/services/users/users.service.spec.ts
  projects/organization-management/src/app/services/users/users.service.ts
  src/app/core/guards/identity-provider-invite.guard.ts
  src/app/core/identity-provider/auth0.identity-provider.ts
  src/app/core/identity-provider/icm.identity-provider.ts
  src/app/core/identity-provider/identity-provider.interface.ts
  src/app/core/services/api/api.service.ts
  src/app/core/services/authorization/authorization.service.ts
  src/app/core/store/core/router/router.selectors.ts
  src/app/extensions/punchout/services/punchout/punchout.service.ts
  src/app/pages/app-routing.module.ts
Labels: feature

#675 fix: repair data refresh on product pages
  src/app/core/facades/product-context.facade.ts
Labels: bug

#651 feat: support CMS static content pages navigation
  src/app/core/facades/cms.facade.ts
  src/app/core/models/content-page-tree-view/content-page-tree-view.model.ts
  src/app/core/models/content-page-tree/content-page-tree.helper.spec.ts
  src/app/core/models/content-page-tree/content-page-tree.helper.ts
  src/app/core/models/content-page-tree/content-page-tree.interface.ts
  src/app/core/models/content-page-tree/content-page-tree.mapper.spec.ts
  src/app/core/models/content-page-tree/content-page-tree.mapper.ts
  src/app/core/models/content-page-tree/content-page-tree.model.ts
  src/app/core/models/content-view/content-view.model.spec.ts
  src/app/core/models/content-view/content-view.model.ts
  src/app/core/services/cms/cms.service.spec.ts
  src/app/core/services/cms/cms.service.ts
  src/app/core/store/content/content-store.module.ts
  src/app/core/store/content/content-store.ts
  src/app/core/store/content/page-tree/index.ts
  src/app/core/store/content/page-tree/page-tree.actions.ts
  src/app/core/store/content/page-tree/page-tree.effects.spec.ts
  src/app/core/store/content/page-tree/page-tree.effects.ts
  src/app/core/store/content/page-tree/page-tree.reducer.ts
  src/app/core/store/content/page-tree/page-tree.selectors.spec.ts
  src/app/core/store/content/page-tree/page-tree.selectors.ts
  src/app/core/store/content/pages/pages.effects.spec.ts
  src/app/core/store/content/pages/pages.effects.ts
  src/app/core/store/content/pages/pages.selectors.spec.ts
  src/app/core/store/content/pages/pages.selectors.ts
  src/app/core/utils/dev/test-data-utils.ts
  src/app/shared/cms/components/cms-static-page/cms-static-page.component.html
  src/app/shared/cms/components/cms-static-page/cms-static-page.component.spec.ts
  src/app/shared/cms/components/cms-static-page/cms-static-page.component.ts
  src/app/shared/cms/components/content-navigation/content-navigation.component.html
  src/app/shared/cms/components/content-navigation/content-navigation.component.spec.ts
  src/app/shared/cms/components/content-navigation/content-navigation.component.ts
  src/app/shared/shared.module.ts
Labels: feature

#681 fix: reset children when switching sku in context
  src/app/core/facades/product-context.facade.spec.ts
  src/app/core/facades/product-context.facade.ts
Labels: bug

#702 fix: track item changes as local state in checkout facade
  src/app/core/facades/checkout.facade.ts
Labels: bug

#701 refactor: remove reducer tests and add some selector tests
  src/app/core/store/content/includes/includes.reducer.spec.ts
  src/app/core/store/content/includes/includes.reducer.ts
  src/app/core/store/content/viewcontexts/viewcontexts.reducer.spec.ts
  src/app/core/store/content/viewcontexts/viewcontexts.selectors.spec.ts
  src/app/core/store/core/error/error.reducer.spec.ts
  src/app/core/store/core/error/error.reducer.ts
  src/app/core/store/core/error/error.selectors.spec.ts
  src/app/core/store/customer/addresses/addresses.reducer.spec.ts
  src/app/core/store/customer/addresses/addresses.reducer.ts
  src/app/core/store/customer/addresses/addresses.selectors.spec.ts
  src/app/core/store/customer/basket/basket.reducer.spec.ts
  src/app/core/store/customer/basket/basket.reducer.ts
  src/app/core/store/customer/basket/basket.selectors.spec.ts
  src/app/core/store/customer/orders/orders.reducer.spec.ts
  src/app/core/store/customer/orders/orders.reducer.ts
  src/app/core/store/customer/user/user.reducer.spec.ts
  src/app/core/store/customer/user/user.reducer.ts
  src/app/core/store/general/regions/regions.reducer.spec.ts
  src/app/core/store/general/regions/regions.reducer.ts
  src/app/core/store/shopping/categories/categories.reducer.spec.ts
  src/app/core/store/shopping/categories/categories.reducer.ts
  src/app/core/store/shopping/compare/compare.reducer.spec.ts
  src/app/core/store/shopping/compare/compare.reducer.ts
  src/app/core/store/shopping/compare/compare.selectors.spec.ts
  src/app/core/store/shopping/filter/filter.reducer.spec.ts
  src/app/core/store/shopping/filter/filter.reducer.ts
  src/app/core/store/shopping/filter/filter.selectors.spec.ts
  src/app/core/store/shopping/products/products.reducer.spec.ts
  src/app/core/store/shopping/products/products.reducer.ts
  src/app/core/store/shopping/products/products.selectors.spec.ts
  src/app/core/store/shopping/promotions/promotions.reducer.spec.ts
  src/app/core/store/shopping/promotions/promotions.reducer.ts
  src/app/core/store/shopping/search/search.selector.spec.ts
Labels: refactoring

#685 feat: use locales from ICM configuration
  docs/concepts/configuration.md
  e2e/cypress/integration/pages/meta-data.module.ts
  src/app/core/facades/app.facade.ts
  src/app/core/facades/checkout.facade.ts
  src/app/core/services/api/api.service.spec.ts
  src/app/core/store/core/configuration/configuration.effects.spec.ts
  src/app/core/store/core/configuration/configuration.integration.spec.ts
  src/app/core/store/core/configuration/configuration.reducer.ts
  src/app/core/store/core/configuration/configuration.selectors.spec.ts
  src/app/core/store/core/configuration/configuration.selectors.ts
  src/app/core/store/core/core-store.module.ts
  src/app/core/store/core/core-store.ts
  src/app/core/store/core/server-config/index.ts
  src/app/core/store/core/server-config/server-config.actions.ts
  src/app/core/store/core/server-config/server-config.effects.spec.ts
  src/app/core/store/core/server-config/server-config.effects.ts
  src/app/core/store/core/server-config/server-config.reducer.ts
  src/app/core/store/core/server-config/server-config.selectors.spec.ts
  src/app/core/store/core/server-config/server-config.selectors.ts
  src/app/core/store/customer/basket/basket-validation.effects.spec.ts
  src/app/core/store/customer/basket/basket-validation.effects.ts
  src/app/core/store/customer/customer-store.spec.ts
  src/app/core/store/customer/user/user.selectors.spec.ts
  src/app/core/store/customer/user/user.selectors.ts
  src/app/core/store/general/general-store.module.ts
  src/app/core/store/general/general-store.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/extensions/captcha/facades/captcha.facade.ts
  src/environments/environment.model.ts
Labels: feature, wait

#704 feat: omit default redirect in multi channel when one base href is root route
  docker-compose.yml
  docs/guides/nginx-startup.md
  nginx/channel.conf.tmpl
Labels: enhancement

#626 feat: display only available products in product links carousels and lists
  src/app/pages/product/product-links-carousel/product-links-carousel.component.html
  src/app/pages/product/product-links-carousel/product-links-carousel.component.spec.ts
  src/app/pages/product/product-links-carousel/product-links-carousel.component.ts
  src/app/pages/product/product-links-list/product-links-list.component.html
  src/app/pages/product/product-links-list/product-links-list.component.spec.ts
  src/app/pages/product/product-links-list/product-links-list.component.ts
  src/app/pages/product/product-links/product-links.component.html
Labels: feature

#707 refactor: remove nested async pipes for the same observable, used mapped value
  docs/guides/angular-component-development.md
  src/app/extensions/punchout/pages/account-punchout/account-punchout-page.component.html
  src/app/pages/account-order/account-order-page.component.html
  src/app/pages/account-profile-company/account-profile-company-page.component.html
Labels: refactoring

#686 fix: fix logout bug after contact us submission
  src/app/core/utils/api-token/api-token.service.ts
  src/app/pages/contact/contact-page.component.ts
Labels: bug:minor

#705 fix: add missing loading spinner when creating an account (registration)
  src/app/pages/registration/registration-page.component.html
  src/app/pages/registration/registration-page.component.spec.ts
  src/app/pages/registration/registration-page.component.ts
Labels: bug

#708 fix: using regionCode instead of id for US new-address-form
  e2e/cypress/integration/specs/checkout/checkout-validation.b2c.e2e-spec.ts
  src/app/shared/formly-address-forms/configurations/us/address-form-us.configuration.ts
Labels: bug

#682 fix: adapt static content navigation styling to meet new IAD/VD requirements
  src/app/pages/content/content-page.component.html
  src/app/pages/content/content-page.component.spec.ts
  src/app/shared/cms/components/cms-static-page/cms-static-page.component.html
  src/app/shared/cms/components/cms-static-page/cms-static-page.component.spec.ts
  src/app/shared/cms/components/content-navigation/content-navigation.component.html
  src/app/shared/cms/components/content-navigation/content-navigation.component.spec.ts
  src/styles/pages/content-pages/page-content.scss
  src/styles/pages/content-pages/page-navigation.scss
Labels: bug:minor

#711 fix: timing issue when fetching CMS content include data after logout
  src/app/core/facades/cms.facade.ts
Labels: bug
