Repository intershop/intershop-pwa, pull requests merged in 2021-03, with the labels that each got.

#580 fix: use new checkbox type in directdebit
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
Labels: bug

#586 fix: set unique ids for form fields in payment components
  src/app/pages/checkout-payment/payment-concardis-creditcard/payment-concardis-creditcard.component.html
  src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.html
Labels: bug:minor

#587 refactor: use formly checkbox to display terms and conditions checkbo…
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/app/pages/registration/registration-tac-field/registration-tac-field.component.html
  src/app/pages/registration/registration-tac-field/registration-tac-field.component.spec.ts
  src/app/pages/registration/registration-tac-field/registration-tac-field.component.ts
  src/app/shared/formly/formly.module.ts
  src/app/shared/formly/types/checkbox-field/checkbox-field.component.html
  src/app/shared/formly/wrappers/horizontal-checkbox-wrapper/horizontal-checkbox-wrapper.component.html
  src/app/shared/forms/components/tac-checkbox/tac-checkbox.component.html
  src/app/shared/forms/components/tac-checkbox/tac-checkbox.component.spec.ts
  src/app/shared/forms/components/tac-checkbox/tac-checkbox.component.ts
  src/app/shared/forms/forms.module.ts
  src/styles/global/forms/formly.scss
  src/styles/global/forms/forms.scss
Labels: refactoring

#564 chore: testing workshop input
  .prettierignore
  docs/concepts/project-structure.md
  docs/guides/testing-jest.md
  src/app/core/facades/account.facade.spec.ts
  src/app/core/facades/shopping.facade.spec.ts
  src/app/core/models/price/price.helper.spec.ts
  src/app/core/services/cms/cms.service.spec.ts
  src/app/core/store/customer/addresses/addresses.selectors.ts
  src/app/core/store/customer/authorization/authorization.effects.spec.ts
  src/app/core/store/general/server-config/server-config.effects.spec.ts
  src/app/core/store/shopping/products/products.effects.spec.ts
  src/app/core/utils/dev/html-query-utils.ts
  src/app/core/utils/dev/ngrx-testing.ts
  src/app/extensions/quoting/store/quoting/quoting.effects.spec.ts
  src/app/extensions/tacton/services/tacton-self-service-api/tacton-self-service-api.service.spec.ts
  src/app/shared/components/recently/recently-viewed/recently-viewed.component.html
  src/app/shared/components/recently/recently-viewed/recently-viewed.component.spec.ts
  src/jest-serializer/NgrxActionSerializer.js
  tslint-rules/src/meaningfulNamingInTestsRule.ts
Labels: documentation, enhancement

#579 refactor: use separate html files for the formly wrappers
  docs/guides/formly.md
  src/app/shared/formly/dev/testing/formly-testing.module.ts
  src/app/shared/formly/wrappers/description-wrapper/description-wrapper.component.html
  src/app/shared/formly/wrappers/description-wrapper/description-wrapper.component.ts
  src/app/shared/formly/wrappers/tooltip-wrapper/tooltip-wrapper.component.html
  src/app/shared/formly/wrappers/tooltip-wrapper/tooltip-wrapper.component.ts
Labels: refactoring

#590 fix: working and adjusted concardis-directdebit validation
  docs/guides/formly.md
  src/app/pages/checkout-payment/checkout-payment-page.module.ts
  src/app/pages/checkout-payment/formly/server-validation.extension.ts
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.html
  src/app/pages/checkout-payment/payment-concardis-directdebit/payment-concardis-directdebit.component.ts
  src/app/pages/checkout-payment/payment-concardis/payment-concardis.component.ts
  src/app/pages/registration/formly/registration-address-field/registration-address-field.component.html
  src/app/pages/registration/formly/registration-address-field/registration-address-field.component.spec.ts
  src/app/pages/registration/formly/registration-address-field/registration-address-field.component.ts
  src/app/pages/registration/formly/registration-heading-field/registration-heading-field.component.html
  src/app/pages/registration/formly/registration-heading-field/registration-heading-field.component.spec.ts
  src/app/pages/registration/formly/registration-heading-field/registration-heading-field.component.ts
  src/app/pages/registration/formly/registration-tac-field/registration-tac-field.component.html
  src/app/pages/registration/formly/registration-tac-field/registration-tac-field.component.spec.ts
  src/app/pages/registration/formly/registration-tac-field/registration-tac-field.component.ts
  src/app/pages/registration/registration-page.module.ts
  src/app/shared/formly/components/validation-icons/validation-icons.component.html
  src/app/shared/formly/components/validation-icons/validation-icons.component.ts
  tslint.json
Labels: bug

#602 fix: repair add-destroy schematic
  e2e/test-schematics.sh
  schematics/src/utils/ts-morph.ts
Labels: bug

#604 perf: forbid omit from lodash-es as it is not used to its full potential
  src/app/core/models/product-variation/product-variation.helper.ts
  src/app/core/models/server-config/server-config.mapper.ts
  src/app/core/services/filter/filter.service.ts
  src/app/core/utils/functions.spec.ts
  src/app/core/utils/functions.ts
  tslint.json
Labels: refactoring

#598 feat: show available stock if available
  src/app/core/models/product/product.interface.ts
  src/app/core/models/product/product.mapper.ts
  src/app/core/models/product/product.model.ts
  src/app/shared/components/product/product-inventory/product-inventory.component.html
  src/app/shared/components/product/product-inventory/product-inventory.component.ts
Labels: enhancement

#605 feat: product context access directive
  src/app/core/directives.module.ts
  src/app/core/directives/product-context-access.directive.ts
  src/app/core/facades/product-context.facade.ts
  src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.html
  src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.spec.ts
  src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.ts
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-line-item/account-wishlist-detail-line-item.component.html
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-line-item/account-wishlist-detail-line-item.component.spec.ts
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-line-item/account-wishlist-detail-line-item.component.ts
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.html
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.spec.ts
  src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.html
  src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.spec.ts
  src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.ts
  src/app/pages/product/product-brand/product-brand.component.html
  src/app/pages/product/product-brand/product-brand.component.spec.ts
  src/app/pages/product/product-brand/product-brand.component.ts
Labels: enhancement, feature

#592 refactor: use formly for b2b user creation and update
  docs/guides/formly.md
  e2e/cypress/integration/pages/organizationmanagement/user-create.page.ts
  e2e/cypress/integration/pages/organizationmanagement/user-edit-budget.page.ts
  e2e/cypress/integration/specs/organizationmanagement/user-management-crud.b2b.e2e-spec.ts
  projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.html
  projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.spec.ts
  projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.ts
  projects/organization-management/src/app/components/user-profile-form/user-profile-form.component.html
  projects/organization-management/src/app/components/user-profile-form/user-profile-form.component.spec.ts
  projects/organization-management/src/app/components/user-profile-form/user-profile-form.component.ts
  projects/organization-management/src/app/pages/user-create/user-create-page.component.spec.ts
  projects/organization-management/src/app/pages/user-create/user-create-page.component.ts
  projects/organization-management/src/app/pages/user-edit-budget/user-edit-budget-page.component.html
  projects/organization-management/src/app/pages/user-edit-budget/user-edit-budget-page.component.ts
  projects/organization-management/src/app/pages/user-edit-profile/user-edit-profile-page.component.html
  projects/organization-management/src/app/pages/user-edit-profile/user-edit-profile-page.component.spec.ts
  projects/organization-management/src/app/pages/user-edit-profile/user-edit-profile-page.component.ts
  src/app/shared/formly-address-forms/components/formly-address-form/formly-address-form.component.ts
  src/app/shared/formly/dev/testing/formly-testing.module.ts
  src/app/shared/formly/formly.module.ts
  src/app/shared/formly/types/select-field/select-field.component.ts
  src/app/shared/formly/wrappers/input-addon-wrapper/input-addon-wrapper.component.html
  src/app/shared/formly/wrappers/input-addon-wrapper/input-addon-wrapper.component.spec.ts
  src/app/shared/formly/wrappers/input-addon-wrapper/input-addon-wrapper.component.ts
  src/styles/global/forms/formly.scss
Labels: refactoring

#609 Remove obsolete gitlab pipeline
  .gitlab-ci-get-publish.sh
  .gitlab-ci-housekeeping-environments.sh
  .gitlab-ci.yml
Labels: refactoring

#603 refactor: remove redundant productAsVariationProduct from product context
  src/app/core/facades/product-context.facade.spec.ts
  src/app/core/facades/product-context.facade.ts
  src/app/core/models/product-variation/product-variation.helper.spec.ts
  src/app/core/models/product-variation/product-variation.helper.ts
  src/app/core/models/product-view/product-view.model.ts
  src/app/core/models/product/product-bundle.model.ts
  src/app/core/models/product/product-retail-set.model.ts
  src/app/core/models/product/product-variation-master.model.ts
  src/app/core/models/product/product-variation.model.ts
  src/app/core/models/product/product.helper.ts
  src/app/core/models/product/product.mapper.spec.ts
  src/app/core/models/product/product.mapper.ts
  src/app/core/models/product/product.model.ts
  src/app/core/routing/product/product.route.spec.ts
  src/app/core/services/products/products.service.ts
  src/app/core/store/shopping/products/products.effects.spec.ts
  src/app/core/store/shopping/products/products.selectors.ts
  src/app/core/store/shopping/recently/recently.selectors.spec.ts
  src/app/extensions/punchout/services/punchout-product-context-display-properties/punchout-product-context-display-properties.service.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
  src/app/extensions/tacton/services/tacton-product-context-display-properties/tacton-product-context-display-properties.service.ts
  src/app/pages/product/product-detail-actions/product-detail-actions.component.ts
  src/app/pages/product/product-detail-info-accordion/product-detail-info-accordion.component.ts
  src/app/pages/product/product-images/product-images.component.ts
  src/app/pages/product/product-master-link/product-master-link.component.ts
  src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.spec.ts
  src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.ts
  src/app/shared/components/line-item/line-item-edit/line-item-edit.component.ts
  src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.ts
  src/app/shared/components/product/product-attributes/product-attributes.component.ts
  src/app/shared/components/product/product-item-variations/product-item-variations.component.spec.ts
  src/app/shared/components/product/product-row/product-row.component.ts
  src/app/shared/components/product/product-tile/product-tile.component.ts
  src/app/shared/components/product/product-variation-display/product-variation-display.component.ts
  src/app/shared/components/product/product-variation-select/product-variation-select.component.spec.ts
  src/app/shared/components/product/product-variation-select/product-variation-select.component.ts
Labels: refactoring

#613 chore: remove deprecated camel case parameters from ng calls
  Dockerfile
  docs/concepts/cms-integration.md
  e2e/test-schematics.sh
  scripts/build-pwa.js
  templates/Dockerfile_dev
Labels: enhancement

#591 refactor: remove ngx-meta and replace with native implementation
  package-lock.json
  package.json
  src/app/extensions/seo/seo.module.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
Labels: refactoring

#614 refactor: use setLoadingOn and unsetLoadingAndErrorOn where possible
  projects/organization-management/src/app/store/users/users.reducer.ts
  src/app/core/store/content/includes/includes.reducer.ts
  src/app/core/store/content/pages/pages.reducer.ts
  src/app/core/store/customer/basket/basket.reducer.ts
  src/app/core/store/customer/user/user.reducer.ts
  src/app/core/store/general/contact/contact.reducer.ts
  src/app/core/store/general/regions/regions.reducer.ts
  src/app/core/store/shopping/product-listing/product-listing.reducer.ts
  src/app/core/utils/ngrx-creators.ts
  src/app/extensions/order-templates/store/order-template/order-template.reducer.ts
  src/app/extensions/tacton/store/product-configuration/product-configuration.reducer.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.reducer.ts
Labels: refactoring

#617 perf: use lazy properties on product context
  src/app/core/facades/product-context.facade.spec.ts
  src/app/core/facades/product-context.facade.ts
  src/app/core/facades/shopping.facade.ts
  src/app/core/store/shopping/products/products.actions.ts
  src/app/core/store/shopping/products/products.effects.spec.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/products/products.reducer.ts
  src/app/core/store/shopping/products/products.selectors.spec.ts
  src/app/pages/product/product-links/product-links.component.ts
  src/app/shared/components/product/product-promotion/product-promotion.component.spec.ts
  src/app/shared/components/product/product-promotion/product-promotion.component.ts
Labels: enhancement

#623 refactor: make display properties overridable
  src/app/core/facades/product-context.facade.spec.ts
  src/app/core/facades/product-context.facade.ts
  src/app/core/utils/product-context-display-properties/product-context-display-properties.service.ts
Labels: refactoring

#601 fix: adapt purgecss configuration to prevent purging needed styles
  src/styles/global/forms/forms.scss
  src/styles/global/global.scss
  src/styles/global/toasts.scss
  templates/webpack/webpack.custom.ts
Labels: bug

#627 refactor: use formly for update password form
  src/app/pages/forgot-password/update-password-form/update-password-form.component.html
  src/app/pages/forgot-password/update-password-form/update-password-form.component.spec.ts
  src/app/pages/forgot-password/update-password-form/update-password-form.component.ts
Labels: refactoring

#633 fix: adapt nginx Dockerfile to nginx-prometheus-exporter changes (#632)
  nginx/Dockerfile
Labels: bug

#616 feat: replace any typescript file by configuration
  docs/guides/customizations.md
  e2e/test-schematics.sh
  package-lock.json
  package.json
  templates/webpack/webpack.custom.ts
Labels: enhancement

#611 fix: allow parentheses in urls
  src/app/app.module.ts
  src/app/core/utils/custom-url-serializer.spec.ts
  src/app/core/utils/custom-url-serializer.ts
Labels: bug

#641 refactor: use formly for forgot password form (request reminder form)
  src/app/pages/forgot-password/request-reminder-form/request-reminder-form.component.html
  src/app/pages/forgot-password/request-reminder-form/request-reminder-form.component.spec.ts
  src/app/pages/forgot-password/request-reminder-form/request-reminder-form.component.ts
Labels: refactoring

#628 fix: re-apply transferred state for later initialized feature states
  src/app/core/configurations/ngrx-state-transfer.ts
Labels: bug

#636 chore: sort localizations in pre-commit
  package-lock.json
  package.json
Labels: enhancement
