Repository intershop/intershop-pwa, pull requests merged in 2021-04, with the labels that each got.

#649 fix: multi site not working language switch
  src/app/core/pipes/make-href.pipe.spec.ts
  src/app/core/pipes/make-href.pipe.ts
  src/app/shell/header/language-switch/language-switch.component.ts
Labels: bug

#652 fix: basket acceleration if cost center is required but missing
  src/app/core/models/basket-validation/basket-validation.model.ts
  src/app/core/store/customer/basket/basket-validation.effects.ts
Labels: bug:minor

#653 fix: display a product unavailable image on product detail page
  src/app/pages/product/product-images/product-images.component.spec.ts
  src/app/pages/product/product-images/product-images.component.ts
Labels: bug:minor

#658 chore: mark nginx files as property files for VSCode
  .vscode/settings.json
Labels: enhancement

#656 chore: remove logging statement in module loader
  src/app/core/utils/module-loader/module-loader.service.ts
Labels: enhancement

#657 test: fail if test runs without all required stores
  src/setupJest.ts
Labels: enhancement

#662 deps: move custom-webpack to dev dependencies
  package-lock.json
  package.json
Labels: dependencies

#663 fix: cms carousel component should handle not completely filled slides
  src/app/core/utils/functions.spec.ts
  src/app/core/utils/functions.ts
Labels: bug

#642 refactor: use formly for order template preferences form
  e2e/cypress/integration/pages/account/order-templates-overview.page.ts
  src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.html
  src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.spec.ts
  src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: refactoring

#666 fix: add missing text for navigation toggle
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#544 feat: Punchout User Management for cXML and OCI user
  docs/concepts/localization.md
  e2e/cypress/integration/pages/account/punchout-create.page.ts
  e2e/cypress/integration/pages/account/punchout-edit.page.ts
  e2e/cypress/integration/pages/account/punchout-overview.page.ts
  e2e/cypress/integration/specs/extras/punchout-management.b2b.e2e-spec.ts
  projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.html
  projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.spec.ts
  projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.ts
  projects/organization-management/src/app/store/users/users.selectors.spec.ts
  projects/organization-management/src/app/store/users/users.selectors.ts
  scripts/clean-up-localizations.js
  src/app/core/facades/app.facade.ts
  src/app/extensions/punchout/facades/punchout.facade.ts
  src/app/extensions/punchout/models/punchout-user/punchout-user.model.ts
  src/app/extensions/punchout/pages/account-punchout-create/account-punchout-create-page.component.html
  src/app/extensions/punchout/pages/account-punchout-create/account-punchout-create-page.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout-create/account-punchout-create-page.component.ts
  src/app/extensions/punchout/pages/account-punchout-create/account-punchout-create-page.module.ts
  src/app/extensions/punchout/pages/account-punchout-details/account-punchout-details-page.component.html
  src/app/extensions/punchout/pages/account-punchout-details/account-punchout-details-page.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout-details/account-punchout-details-page.component.ts
  src/app/extensions/punchout/pages/account-punchout/account-punchout-header/account-punchout-header.component.html
  src/app/extensions/punchout/pages/account-punchout/account-punchout-header/account-punchout-header.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout/account-punchout-header/account-punchout-header.component.ts
  src/app/extensions/punchout/pages/account-punchout/account-punchout-page.component.html
  src/app/extensions/punchout/pages/account-punchout/account-punchout-page.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout/account-punchout-page.component.ts
  src/app/extensions/punchout/pages/account-punchout/account-punchout-page.module.ts
  src/app/extensions/punchout/services/punchout/punchout.service.spec.ts
  src/app/extensions/punchout/services/punchout/punchout.service.ts
  src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.html
  src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.spec.ts
  src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.ts
  src/app/extensions/punchout/store/punchout-store.module.ts
  src/app/extensions/punchout/store/punchout-store.ts
  src/app/extensions/punchout/store/punchout-types/index.ts
  src/app/extensions/punchout/store/punchout-types/punchout-types.actions.ts
  src/app/extensions/punchout/store/punchout-types/punchout-types.effects.spec.ts
  src/app/extensions/punchout/store/punchout-types/punchout-types.effects.ts
  src/app/extensions/punchout/store/punchout-types/punchout-types.reducer.ts
  src/app/extensions/punchout/store/punchout-types/punchout-types.selectors.spec.ts
  src/app/extensions/punchout/store/punchout-types/punchout-types.selectors.ts
  src/app/extensions/punchout/store/punchout-users/punchout-users.actions.ts
  src/app/extensions/punchout/store/punchout-users/punchout-users.effects.spec.ts
  src/app/extensions/punchout/store/punchout-users/punchout-users.effects.ts
  src/app/extensions/punchout/store/punchout-users/punchout-users.selectors.spec.ts
  src/app/extensions/punchout/store/punchout-users/punchout-users.selectors.ts
  src/app/shared/forms/validators/special-validators.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/pages/account/account.scss
Labels: enhancement
