Repository intershop/intershop-pwa, pull requests merged in 2021-11, with the labels that each got.

#899 feat: add option to enable SSR only for crawlers in nginx
  Dockerfile
  Dockerfile_noSSR
  docker-compose.yml
  docs/guides/nginx-startup.md
  nginx/Dockerfile
  nginx/features/ssr-off.conf
  nginx/features/ssr.conf
  nginx/templates/cache-blacklist.conf.tmpl
  nginx/templates/multi-channel.conf.tmpl
  scripts/check-file-synchronization.js
Labels: feature, performance

#921 fix: use newest Bootstrap release 4.6.1 with own divide() function
  package-lock.json
  package.json
  src/styles/components/header/language-switch.scss
  src/styles/components/header/search-container.scss
  src/styles/components/header/user-information-mobile.scss
  src/styles/global/buttons.scss
  src/styles/global/forms/forms.scss
  src/styles/global/global.scss
  src/styles/global/icons.scss
  src/styles/global/panel.scss
  src/styles/global/share-tools.scss
  src/styles/global/tables.scss
  src/styles/pages/account/account-navigation.scss
  src/styles/pages/category/filter-panel.scss
  src/styles/pages/category/filter-row.scss
  src/styles/pages/category/product-list.scss
  src/styles/pages/checkout/shopping-cart.scss
  src/styles/pages/content-pages/page-content.scss
  src/styles/pages/homepage/homepage.scss
  src/styles/pages/productdetail/product-images.scss
  src/styles/pages/productdetail/product-info.scss
  src/styles/pages/productdetail/productdetail.scss
Labels: bug

#926 feat: add 'lang' property to 'html' tag
  src/app/core/store/core/configuration/configuration.effects.ts
Labels: enhancement

#934 fix: display a default promotionname if promotionmessaging disabled
  src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.html
  src/app/shared/components/basket/basket-promotion/basket-promotion.component.html
  src/app/shared/components/basket/basket-promotion/basket-promotion.component.spec.ts
Labels: bug

#935 fix: correct some language mistakes in documentation
  CONTRIBUTING.md
Labels: documentation

#937 fix: support sitemap locations for muliple servers
  nginx/templates/multi-channel.conf.tmpl
  nginx/templates/sitemap.conf.tmpl
Labels: bug:minor
