Repository intershop/intershop-pwa, pull requests merged in 2021-08, with the labels that each got.

#809 refactor: remove basic Storefront Editing (sfe) functionality
  docs/guides/angular-change-detection.md
  src/app/core/facades/cms.facade.ts
  src/app/core/store/content/includes/includes.reducer.ts
  src/app/core/store/content/includes/includes.selectors.ts
  src/app/shared/cms/cms.module.ts
  src/app/shared/cms/components/content-include/content-include.component.spec.ts
  src/app/shared/cms/components/content-include/content-include.component.ts
  src/app/shared/cms/components/content-pagelet/content-pagelet.component.spec.ts
  src/app/shared/cms/components/content-pagelet/content-pagelet.component.ts
  src/app/shared/cms/components/content-slot/content-slot.component.spec.ts
  src/app/shared/cms/components/content-slot/content-slot.component.ts
  src/app/shared/cms/sfe-adapter/dev/sfe.mapper.spec.dom-data.ts
  src/app/shared/cms/sfe-adapter/sfe-adapter.service.spec.ts
  src/app/shared/cms/sfe-adapter/sfe-adapter.service.ts
  src/app/shared/cms/sfe-adapter/sfe-metadata-wrapper.spec.ts
  src/app/shared/cms/sfe-adapter/sfe-metadata-wrapper.ts
  src/app/shared/cms/sfe-adapter/sfe.mapper.spec.ts
  src/app/shared/cms/sfe-adapter/sfe.mapper.ts
  src/app/shared/cms/sfe-adapter/sfe.types.ts
  tslint.json
Labels: refactoring

#806 docs: add code documentation for formly things
  docs/guides/formly.md
  src/app/shared/formly/components/field-tooltip/field-tooltip.component.ts
  src/app/shared/formly/components/validation-icons/validation-icons.component.ts
  src/app/shared/formly/components/validation-message/validation-message.component.ts
  src/app/shared/formly/extensions/hide-if-empty-options.extension.ts
  src/app/shared/formly/extensions/post-wrappers-extension.ts
  src/app/shared/formly/extensions/translate-select-options.extension.ts
  src/app/shared/formly/types/captcha-field/captcha-field.component.ts
  src/app/shared/formly/types/checkbox-field/checkbox-field.component.ts
  src/app/shared/formly/types/email-field/email-field.component.ts
  src/app/shared/formly/types/fieldset-field/fieldset-field.component.ts
  src/app/shared/formly/types/password-field/password-field.component.ts
  src/app/shared/formly/types/phone-field/phone-field.component.ts
  src/app/shared/formly/types/radio-field/radio-field.component.ts
  src/app/shared/formly/types/select-field/select-field.component.ts
  src/app/shared/formly/types/text-input-field/text-input-field.component.ts
  src/app/shared/formly/types/textarea-field/textarea-field.component.ts
  src/app/shared/formly/wrappers/description-wrapper/description-wrapper.component.ts
  src/app/shared/formly/wrappers/horizontal-checkbox-wrapper/horizontal-checkbox-wrapper.component.ts
  src/app/shared/formly/wrappers/horizontal-wrapper/horizontal-wrapper.component.ts
  src/app/shared/formly/wrappers/input-addon-wrapper/input-addon-wrapper.component.ts
  src/app/shared/formly/wrappers/textarea-description-wrapper/textarea-description-wrapper.component.ts
  src/app/shared/formly/wrappers/tooltip-wrapper/tooltip-wrapper.component.ts
  src/app/shared/formly/wrappers/validation-wrapper/validation-wrapper.component.ts
Labels: documentation

#717 feat: payone creditcard authorize
  src/app/pages/checkout-payment/checkout-payment-page.module.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
  src/app/pages/checkout-payment/payment-payone-creditcard/payment-payone-creditcard.component.html
  src/app/pages/checkout-payment/payment-payone-creditcard/payment-payone-creditcard.component.spec.ts
  src/app/pages/checkout-payment/payment-payone-creditcard/payment-payone-creditcard.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#813 fix: translate-select-options without expressionProperty
  src/app/pages/contact/contact-form/contact-form.component.ts
  src/app/shared/formly/extensions/translate-select-options.extension.ts
Labels: bug

#810 refactor: fix translations in localization files
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#815 refactor: remove email, password & phone type components
  docs/guides/formly.md
  src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
  src/app/shared/formly/extensions/critical-default-values.extension.ts
  src/app/shared/formly/formly.module.ts
  src/app/shared/formly/types/email-field/email-field.component.html
  src/app/shared/formly/types/email-field/email-field.component.spec.ts
  src/app/shared/formly/types/email-field/email-field.component.ts
  src/app/shared/formly/types/password-field/password-field.component.html
  src/app/shared/formly/types/password-field/password-field.component.spec.ts
  src/app/shared/formly/types/password-field/password-field.component.ts
  src/app/shared/formly/types/phone-field/phone-field.component.html
  src/app/shared/formly/types/phone-field/phone-field.component.spec.ts
  src/app/shared/formly/types/phone-field/phone-field.component.ts
  src/app/shared/formly/types/text-input-field/text-input-field.component.ts
  src/app/shared/formly/wrappers/validation-wrapper/validation-wrapper.component.html
  src/app/shared/formly/wrappers/validation-wrapper/validation-wrapper.component.ts
  src/app/shared/forms/validators/special-validators.ts
Labels: refactoring

#820 fix: remove type: text from registration password fields
  src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
  src/app/pages/account-profile-email/account-profile-email/account-profile-email.component.ts
Labels: bug:major

#816 refactor: improve formly/form css styling
  e2e/cypress/integration/pages/account/registration.page.ts
  projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.ts
  src/app/extensions/captcha/exports/lazy-captcha/lazy-captcha.component.spec.ts
  src/app/extensions/captcha/shared/captcha-v2/captcha-v2.component.html
  src/app/extensions/captcha/shared/captcha-v3/captcha-v3.component.html
  src/app/extensions/quickorder/shared/quickorder-csv-form/quickorder-csv-form.component.html
  src/app/pages/checkout-payment/payment-concardis-creditcard/payment-concardis-creditcard.component.html
  src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.html
  src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.html
  src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.html
  src/app/pages/registration/formly/registration-tac-field/registration-tac-field.component.html
  src/app/shared/components/product/product-quantity/product-quantity.component.html
  src/app/shared/formly/components/validation-icons/validation-icons.component.html
  src/app/shared/formly/wrappers/horizontal-checkbox-wrapper/horizontal-checkbox-wrapper.component.html
  src/app/shared/formly/wrappers/horizontal-wrapper/horizontal-wrapper.component.html
  src/app/shared/formly/wrappers/validation-wrapper/validation-wrapper.component.html
  src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.html
  src/styles/global/forms/formly.scss
  src/styles/global/forms/forms.scss
  src/styles/main.scss
Labels: refactoring

#825 refactor: add items to addItemsToBasketSuccess action
  src/app/core/facades/product-context.facade.ts
  src/app/core/models/product/product.helper.ts
  src/app/core/store/customer/basket/basket-items.effects.spec.ts
  src/app/core/store/customer/basket/basket-items.effects.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.selectors.spec.ts
  src/app/core/store/customer/customer-store.spec.ts
Labels: enhancement, refactoring

#826 refactor: replace local sku/quantity type definitions by the existing…
  src/app/core/services/basket/basket.service.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/extensions/quickorder/shared/quickorder-add-products-form/quickorder-add-products-form.component.ts
  src/app/extensions/quickorder/shared/quickorder-csv-form/quickorder-csv-form.component.ts
  src/app/extensions/quickorder/shared/quickorder-repeat-form-quantity/quickorder-repeat-form-quantity.component.ts
  src/app/extensions/quoting/store/quoting/quoting.actions.ts
Labels: refactoring

#833 show error messages from server for checkout payment instead of local…
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
  src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.ts
Labels: refactoring

#831 chore: prevent ngcc lock file warning
  scripts/build-multi-pwa.js
Labels: bug

#824 fix: insert none default theme at the end of active themes
  schematics/customization/add/index.js
Labels: bug:minor

#838 fix: THEME variable should be string
  src/typings.d.ts
Labels: bug

#846 Work on PR demo server deployment
  .github/workflows/demo-server-down.yml
  .github/workflows/demo-server.yml
Labels: enhancement

#829 chore: limit jest load globally to 75%
  jest.config.js
  package.json
Labels: enhancement

#840 feature: product attachments
  src/app/core/models/attachment/attachment.interface.ts
  src/app/core/models/attachment/attachment.mapper.spec.ts
  src/app/core/models/attachment/attachment.mapper.ts
  src/app/core/models/attachment/attachment.model.ts
  src/app/core/models/product/product.interface.ts
  src/app/core/models/product/product.mapper.spec.ts
  src/app/core/models/product/product.mapper.ts
  src/app/core/models/product/product.model.ts
  src/app/pages/product/product-detail-info-accordion/product-detail-info-accordion.component.html
  src/app/pages/product/product-detail-info-accordion/product-detail-info-accordion.component.spec.ts
  src/app/shared/components/product/product-attachments/product-attachments.component.html
  src/app/shared/components/product/product-attachments/product-attachments.component.spec.ts
  src/app/shared/components/product/product-attachments/product-attachments.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/global/global.scss
  src/styles/pages/productdetail/productdetail.scss
Labels: feature

#843 fix: use translate compiler for fallback translations
  src/app/core/utils/translate/fallback-missing-translation-handler.ts
Labels: bug

#850 fix: mainNavigationMaxSubCategoriesDepth configuration with '0' fails to disable main navigation hover menu
  src/app/shell/header/header-navigation/header-navigation.component.html
  src/app/shell/header/header-navigation/header-navigation.component.spec.ts
  src/app/shell/header/header-navigation/header-navigation.component.ts
  src/app/shell/header/sub-category-navigation/sub-category-navigation.component.html
  src/app/shell/header/sub-category-navigation/sub-category-navigation.component.spec.ts
Labels: bug

#835 fix: propagate extra arguments in build:multi script
  scripts/build-multi-pwa.js
  scripts/build-pwa.js
Labels: bug
