Repository intershop/intershop-pwa, pull requests merged in 2022-11, with the labels that each got.

#1311 fix: display login modal after authentication token has expired
  src/app/core/guards/login.guard.ts
  src/app/shared/components/login/login-modal/login-modal.component.html
  src/app/shared/components/login/login-modal/login-modal.component.ts
Labels: bug:minor

#1291 deps: update formly to version 6
  .eslintrc.json
  docs/guides/migrations.md
  package-lock.json
  package.json
  src/app/extensions/contact-us/pages/contact/contact-form/contact-form.component.spec.ts
  src/app/extensions/quickorder/shared/direct-order/direct-order.component.spec.ts
  src/app/extensions/quickorder/shared/quickorder-add-products-form/quickorder-add-products-form.component.spec.ts
  src/app/pages/account-addresses/account-addresses/account-addresses.component.spec.ts
  src/app/pages/account-profile-company/account-profile-company/account-profile-company.component.spec.ts
  src/app/pages/account-profile-email/account-profile-email/account-profile-email.component.spec.ts
  src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.spec.ts
  src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.spec.ts
  src/app/pages/registration/registration-page.component.spec.ts
  src/app/shared/components/basket/basket-cost-center-selection/basket-cost-center-selection.component.spec.ts
  src/app/shared/components/checkout/basket-shipping-address-widget/basket-shipping-address-widget.component.spec.ts
  src/app/shared/formly/extensions/translate-placeholder.extension.ts
  src/app/shared/formly/field-library/library-config-replacement.extension.ts
  src/app/shared/formly/types/select-field/select-field.component.html
  src/app/shared/formly/wrappers/description-wrapper/description-wrapper.component.spec.ts
Labels: has conflicts

#1322 fix: add promotion scope to basket checkout step (#80931)
  src/app/core/store/customer/basket/basket-validation.effects.ts
Labels: bug

#1315 Feature/customer address update
  e2e/cypress/e2e/pages/account/addresses.page.ts
  e2e/cypress/e2e/specs/account/addresses-crud.b2b.e2e-spec.ts
  src/app/core/facades/account.facade.ts
  src/app/core/store/customer/addresses/addresses.actions.ts
  src/app/core/store/customer/addresses/addresses.effects.spec.ts
  src/app/core/store/customer/addresses/addresses.effects.ts
  src/app/core/store/customer/addresses/addresses.reducer.ts
  src/app/pages/account-addresses/account-addresses/account-addresses.component.html
  src/app/pages/account-addresses/account-addresses/account-addresses.component.spec.ts
  src/app/pages/account-addresses/account-addresses/account-addresses.component.ts
  src/app/shared/formly-address-forms/components/formly-address-form/formly-address-form.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1325 feat: save desired delivery date at basket items
  docs/guides/migrations.md
  src/app/core/facades/checkout.facade.ts
  src/app/core/models/line-item/line-item.interface.ts
  src/app/core/models/line-item/line-item.mapper.ts
  src/app/core/models/line-item/line-item.model.ts
  src/app/core/services/basket/basket.service.spec.ts
  src/app/core/services/basket/basket.service.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.effects.spec.ts
  src/app/core/store/customer/basket/basket.effects.ts
  src/app/core/store/customer/basket/basket.reducer.ts
  src/app/pages/checkout-review/checkout-review-page.component.ts
  src/app/shared/components/basket/basket-desired-delivery-date/basket-desired-delivery-date.component.spec.ts
  src/app/shared/components/basket/basket-desired-delivery-date/basket-desired-delivery-date.component.ts
Labels: enhancement

#1328 refactor: add enum CheckoutTargetStep to set next checkout step
  src/app/core/facades/checkout.facade.ts
  src/app/core/models/checkout/checkout-step.type.ts
  src/app/core/store/customer/basket/basket-validation.effects.spec.ts
  src/app/core/store/customer/basket/basket-validation.effects.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.effects.ts
  src/app/pages/checkout-address/checkout-address-page.component.ts
  src/app/pages/checkout-payment/checkout-payment-page.component.ts
  src/app/pages/checkout-shipping/checkout-shipping-page.component.ts
Labels: refactoring

#1332 fix: error when submitting consecutive search after submitting search from search suggestion
  src/app/shared/components/search/search-box/search-box.component.ts
Labels: bug

#1316 feat: route to product detail page if only one search result was found
  e2e/cypress/e2e/specs/shopping/search-products.b2c.e2e-spec.ts
  e2e/cypress/e2e/specs/system/change-language-search-result.b2c.e2e-spec.ts
  src/app/core/store/shopping/search/search.effects.ts
  src/app/core/store/shopping/shopping-store.spec.ts
Labels: feature
