Repository intershop/intershop-pwa, pull requests merged in 2022-03, with the labels that each got.

#1033 refactor: rename store locator model
  src/app/extensions/store-locator/.eslintrc.json
  src/app/extensions/store-locator/facades/store-locator.facade.ts
  src/app/extensions/store-locator/models/store-location/store-location.helper.spec.ts
  src/app/extensions/store-locator/models/store-location/store-location.helper.ts
  src/app/extensions/store-locator/models/store-location/store-location.interface.ts
  src/app/extensions/store-locator/models/store-location/store-location.mapper.spec.ts
  src/app/extensions/store-locator/models/store-location/store-location.mapper.ts
  src/app/extensions/store-locator/models/store-location/store-location.model.ts
  src/app/extensions/store-locator/models/store/store.helper.spec.ts
  src/app/extensions/store-locator/models/store/store.helper.ts
  src/app/extensions/store-locator/models/store/store.mapper.ts
  src/app/extensions/store-locator/pages/store-locator/store-locator-page.component.ts
  src/app/extensions/store-locator/services/stores-map/stores-map.service.ts
  src/app/extensions/store-locator/services/stores/stores.service.ts
  src/app/extensions/store-locator/shared/store-address/store-address.component.spec.ts
  src/app/extensions/store-locator/shared/store-address/store-address.component.ts
  src/app/extensions/store-locator/store/stores/stores.actions.ts
  src/app/extensions/store-locator/store/stores/stores.reducer.ts
  src/app/extensions/store-locator/store/stores/stores.selectors.spec.ts
Labels: refactoring, community

#1034 refactor: recently as extension
  .dockerignore
  docs/guides/migrations.md
  e2e/cypress/integration/pages/shopping/recently-viewed.page.ts
  src/app/app.module.ts
  src/app/core/facades/shopping.facade.ts
  src/app/core/store/shopping/recently/recently.reducer.ts
  src/app/core/store/shopping/shopping-store.module.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/core/store/shopping/shopping-store.ts
  src/app/extensions/recently/exports/.gitignore
  src/app/extensions/recently/exports/recently-exports.module.ts
  src/app/extensions/recently/facades/recently.facade.ts
  src/app/extensions/recently/models/recently-viewed-product/recently-viewed-product.model.ts
  src/app/extensions/recently/pages/recently-routing.module.ts
  src/app/extensions/recently/pages/recently/recently-page.component.html
  src/app/extensions/recently/pages/recently/recently-page.component.spec.ts
  src/app/extensions/recently/pages/recently/recently-page.component.ts
  src/app/extensions/recently/pages/recently/recently-page.module.ts
  src/app/extensions/recently/recently.module.ts
  src/app/extensions/recently/shared/recently-viewed/recently-viewed.component.html
  src/app/extensions/recently/shared/recently-viewed/recently-viewed.component.spec.ts
  src/app/extensions/recently/shared/recently-viewed/recently-viewed.component.ts
  src/app/extensions/recently/store/recently-store.module.ts
  src/app/extensions/recently/store/recently-store.ts
  src/app/extensions/recently/store/recently/index.ts
  src/app/extensions/recently/store/recently/recently.actions.ts
  src/app/extensions/recently/store/recently/recently.effects.spec.ts
  src/app/extensions/recently/store/recently/recently.effects.ts
  src/app/extensions/recently/store/recently/recently.integration.spec.ts
  src/app/extensions/recently/store/recently/recently.reducer.ts
  src/app/extensions/recently/store/recently/recently.selectors.ts
  src/app/pages/app-routing.module.ts
  src/app/pages/basket/basket-page.component.html
  src/app/pages/basket/basket-page.component.spec.ts
  src/app/pages/product/product-page.component.html
  src/app/pages/product/product-page.component.spec.ts
  src/app/pages/recently/recently-page.component.html
  src/app/pages/recently/recently-page.component.spec.ts
  src/app/pages/recently/recently-page.module.ts
  src/app/pages/recently/recently-viewed-all/recently-viewed-all.component.html
  src/app/pages/recently/recently-viewed-all/recently-viewed-all.component.spec.ts
  src/app/pages/recently/recently-viewed-all/recently-viewed-all.component.ts
  src/app/shared/shared.module.ts
  templates/webpack/webpack.custom.ts
Labels: refactoring, community

#1037 fix: render content of product detail description tab as html
  src/app/pages/product/product-detail-info/product-detail-info.component.html
Labels: bug:minor

#974 Feature/payone ideal pwa
  src/app/core/core.module.ts
  src/app/core/interceptors/payment-payone.interceptor.ts
  src/app/core/models/payment-method/payment-method.mapper.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1040 fix: prevent console error messages on checkout shipping page
  src/app/core/facades/checkout.facade.ts
  src/app/pages/checkout-shipping/checkout-shipping/checkout-shipping.component.ts
  src/app/pages/checkout-shipping/formly/shipping-info/shipping-info.component.html
  src/app/pages/checkout-shipping/formly/shipping-info/shipping-info.component.spec.ts
  src/app/pages/checkout-shipping/formly/shipping-info/shipping-info.component.ts
  src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.html
  src/app/pages/checkout-shipping/formly/shipping-radio-wrapper/shipping-radio-wrapper.component.ts
Labels: bug:minor

#1031 fix: prevent out of stock products from being added to basket on order templates
  src/app/core/facades/product-context.facade.spec.ts
  src/app/core/facades/product-context.facade.ts
  src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.html
  src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.spec.ts
  src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.ts
Labels: bug, community

#1043 test: fail on console error
  src/app/pages/basket/shopping-basket/shopping-basket.component.spec.ts
  src/setupJest.ts
Labels: bug

#1039 chore: eslint testbed sorting
  .eslintrc.json
  eslint-rules/src/index.ts
  eslint-rules/src/rules/sort-testbed-metadata-arrays.ts
  eslint-rules/tests/sort-testbed-metadata-arrays.spec.ts
  projects/organization-management/src/app/pages/cost-center-detail/cost-center-detail-page.component.spec.ts
  src/app/app.module.ts
  src/app/extensions/recently/pages/recently/recently-page.component.spec.ts
  src/app/extensions/recently/store/recently/recently.integration.spec.ts
  src/app/extensions/store-locator/pages/store-locator/store-locator-page.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-parameter/tacton-parameter.component.spec.ts
  src/app/pages/basket/basket-page.component.spec.ts
  src/app/pages/product/product-page.component.spec.ts
  src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.spec.ts
  src/app/shell/header/header-navigation/header-navigation.component.spec.ts
Labels: enhancement, community

#1044 perf(schematics): better linter performance
  .eslintignore
  .github/workflows/development.yml
  e2e/test-schematics-customization.sh
  e2e/test-schematics-normal.sh
  package.json
  schematics/src/helpers/add-destroy/factory.ts
  schematics/src/lazy-component/factory.ts
  schematics/src/utils/filesystem.ts
  schematics/src/utils/lint-fix.ts
Labels: performance, community

#1021 feat: fetch and display personalized category and product data
  docs/guides/migrations.md
  src/app/core/facades/shopping.facade.ts
  src/app/core/identity-provider/icm.identity-provider.ts
  src/app/core/services/categories/categories.service.spec.ts
  src/app/core/services/categories/categories.service.ts
  src/app/core/services/filter/filter.service.spec.ts
  src/app/core/services/filter/filter.service.ts
  src/app/core/services/products/products.service.spec.ts
  src/app/core/services/products/products.service.ts
  src/app/core/store/customer/customer-store.spec.ts
  src/app/core/store/customer/user/user.actions.ts
  src/app/core/store/customer/user/user.effects.spec.ts
  src/app/core/store/customer/user/user.effects.ts
  src/app/core/store/customer/user/user.reducer.ts
  src/app/core/store/shopping/categories/categories.effects.spec.ts
  src/app/core/store/shopping/categories/categories.effects.ts
  src/app/core/store/shopping/products/products.effects.spec.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/promotions/promotions.effects.spec.ts
  src/app/core/store/shopping/search/search.effects.spec.ts
  src/app/core/store/shopping/search/search.effects.ts
  src/app/core/store/shopping/shopping-store.module.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/core/utils/api-token/api-token.service.ts
  src/app/core/utils/meta-reducers.spec.ts
  src/app/core/utils/meta-reducers.ts
  src/app/core/utils/operators.ts
Labels: enhancement

#1045 fix: repair service worker
  Dockerfile
  nginx/templates/multi-channel.conf.tmpl
  scripts/build-pwa.js
  server.ts
  src/ssr/server-scripts/server.js
Labels: bug, community

#1058 chore: cypress test stabilization
  e2e/cypress-ci-e2e.js
  e2e/cypress/integration/framework/index.ts
  e2e/cypress/integration/pages/checkout/cart.page.ts
  e2e/cypress/integration/pages/meta-data.module.ts
  e2e/cypress/integration/specs/quoting/quote-handling-anonymous-basket-to-quote-request.b2b.e2e-spec.ts
  e2e/cypress/integration/specs/system/seo-home-page.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/seo-product-detail-page.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/seo-search-page.b2c.e2e-spec.ts
  src/app/core/services/filter/filter.service.spec.ts
  src/app/core/services/products/products.service.ts
Labels: community

#1065 chore: enable function argument to log operator
  src/app/core/utils/dev/operators.spec.ts
  src/app/core/utils/dev/operators.ts
Labels: enhancement, nice to have, community

#1057 fix: repair cleanup testbed
  .github/workflows/dead-code.yml
  .github/workflows/development.yml
  package.json
  scripts/cleanup-testbed.ts
  src/app/core/guards/auth.guard.spec.ts
  src/app/core/guards/authorization-toggle.guard.spec.ts
  src/app/core/guards/feature-toggle.guard.spec.ts
  src/app/core/identity-provider/auth0.identity-provider.spec.ts
  src/app/core/routing/category/category.route.spec.ts
  src/app/core/routing/product/product.route.spec.ts
  src/app/core/services/api/api.service.spec.ts
  src/app/core/store/customer/customer-store.spec.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/core/utils/http-status-code/http-status-code.service.spec.ts
  src/app/core/utils/meta-reducers.spec.ts
  src/app/extensions/punchout/identity-provider/punchout-identity-provider.spec.ts
  src/app/pages/account-addresses/account-addresses-page.component.spec.ts
  src/app/pages/account-order/account-order-page.component.spec.ts
  src/app/pages/account-order/account-order/account-order.component.spec.ts
  src/app/pages/account-overview/account-overview/account-overview.component.spec.ts
  src/app/pages/account-payment/account-payment-page.component.spec.ts
  src/app/pages/account-profile-company/account-profile-company-page.component.spec.ts
  src/app/pages/account-profile-email/account-profile-email-page.component.spec.ts
  src/app/pages/account-profile-password/account-profile-password-page.component.spec.ts
  src/app/pages/account-profile-user/account-profile-user-page.component.spec.ts
  src/app/pages/basket/shopping-basket/shopping-basket.component.spec.ts
  src/app/pages/checkout-address/checkout-address-page.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment-page.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
  src/app/pages/checkout-payment/payment-concardis/payment-concardis.component.spec.ts
  src/app/pages/checkout-payment/payment-parameter-form/payment-parameter-form.component.spec.ts
  src/app/pages/checkout-receipt/checkout-receipt-page.component.spec.ts
  src/app/pages/checkout-receipt/checkout-receipt/checkout-receipt.component.spec.ts
  src/app/pages/checkout-review/checkout-review/checkout-review.component.spec.ts
  src/app/pages/checkout-shipping/checkout-shipping-page.component.spec.ts
  src/app/pages/compare/product-compare-list/product-compare-list.component.spec.ts
  src/app/pages/compare/product-compare-paging/product-compare-paging.component.spec.ts
  src/app/pages/contact/contact-page.component.spec.ts
  src/app/pages/error/error-page.component.spec.ts
  src/app/pages/forgot-password/request-reminder/request-reminder.component.spec.ts
  src/app/pages/forgot-password/update-password/update-password.component.spec.ts
  src/app/pages/loading/loading-page.component.spec.ts
  src/app/pages/login/login-page.component.spec.ts
  src/app/pages/product/product-bundle-parts/product-bundle-parts.component.spec.ts
  src/app/pages/product/product-detail-actions/product-detail-actions.component.spec.ts
  src/app/pages/product/product-detail-info/product-detail-info.component.spec.ts
  src/app/pages/product/product-detail/product-detail.component.spec.ts
  src/app/pages/product/product-links-carousel/product-links-carousel.component.spec.ts
  src/app/pages/product/product-links-list/product-links-list.component.spec.ts
  src/app/pages/product/product-links/product-links.component.spec.ts
  src/app/pages/product/retail-set-parts/retail-set-parts.component.spec.ts
  src/app/pages/registration/registration-page.component.spec.ts
  src/app/shell/footer/footer-top/footer-top.component.spec.ts
  src/app/shell/footer/footer/footer.component.spec.ts
  src/app/shell/header/header-checkout/header-checkout.component.spec.ts
  src/app/shell/header/header-default/header-default.component.spec.ts
  src/app/shell/header/header/header.component.spec.ts
Labels: regression, community

#1068 build: dedicated directory for angular cache per theme
  templates/webpack/webpack.custom.ts
Labels: bug, community

#1046 chore: activate eslint for js files
  .dockerignore
  .eslintignore
  .eslintrc.json
  angular.json
  docs/check-dead-links.js
  docs/check-sentence-newline.js
  e2e/.gitignore
  e2e/cypress/tsconfig.json
  intershop-changelog.js
  package.json
  schematics/customization/service-worker/index.js
  schematics/scripts/generate-schema-defs.js
  scripts/check-file-synchronization.js
  scripts/clean-up-localizations.js
  scripts/convert-to-xliff.js
  scripts/update-dockerignore.js
  scripts/upgrade-pwa.js
  src/jest-serializer/AngularHTMLSerializer.js
  src/jest-serializer/CategoryTreeSerializer.js
  templates/review-server/review-proxy.js
  templates/webpack/data-testing-id-loader.js
Labels: enhancement, community

#1061 build: simplify win check for PR build
  .github/workflows/windows.yml
Labels: enhancement, community

#1030 feat: handle and display scaled prices
  src/app/core/models/price-item/price-item.helper.spec.ts
  src/app/core/models/price-item/price-item.helper.ts
  src/app/core/models/price-item/price-item.model.ts
  src/app/core/models/price/price.model.ts
  src/app/core/models/product-prices/product-prices.mapper.spec.ts
  src/app/core/models/product-prices/product-prices.mapper.ts
  src/app/core/models/product-prices/product-prices.model.ts
  src/app/core/models/product-view/product-view.model.ts
  src/app/core/store/shopping/products/products.selectors.spec.ts
  src/app/pages/product/product-detail/product-detail.component.html
  src/app/shared/components/product/product-price/product-price.component.html
  src/app/shared/components/product/product-price/product-price.component.spec.ts
  src/app/shared/components/product/product-price/product-price.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/global/tables.scss
  src/styles/pages/category/product-list.scss
Labels: feature

#1055 feat(eslint): rules for customization
  .eslintrc.json
  eslint-rules/src/index.ts
  eslint-rules/src/rules/do-not-use-theme-identifier.ts
  eslint-rules/src/rules/use-correct-component-overrides.ts
  eslint-rules/tests/do-not-use-theme-identifier.spec.ts
  eslint-rules/tests/use-correct-component-overrides.spec.ts
Labels: enhancement, community

#1074 chore: activate eslint rules arrow-body-style and prefer-arrow-callback
  .eslintrc.json
  eslint-rules/src/rules/sort-testbed-metadata-arrays.ts
  intershop-changelog.js
  scripts/eslint-hard.js
  src/app/core/interceptors/payment-payone.interceptor.ts
  src/app/core/services/products/products.service.spec.ts
  src/app/core/store/shopping/product-prices/product-prices.reducer.ts
  src/jest-serializer/NgrxActionArraySerializer.js
  src/jest-serializer/NgrxActionSerializer.js
  templates/review-server/review-proxy.js
Labels: refactoring, community

#1075 chore: add rule for meaningful top-level describes in tests
  .eslintrc.json
  eslint-rules/src/index.ts
  eslint-rules/src/rules/meaningful-describe-in-tests.ts
  eslint-rules/tests/meaningful-describe-in-tests.spec.ts
  src/app/core/store/shopping/product-prices/product-prices.effects.spec.ts
  src/app/core/store/shopping/product-prices/product-prices.selectors.spec.ts
  src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.spec.ts
  src/app/extensions/recently/store/recently/recently.integration.spec.ts
  src/app/extensions/store-locator/store/store-locator-config/store-locator-config.selectors.spec.ts
Labels: regression, community

#1076 chore: minor cleanup testbed improvements
  .eslintrc.json
  package.json
  scripts/cleanup-testbed.mjs
Labels: bug:minor, community

#1082 Fix/button row of product tile
  src/app/core/icon.module.ts
  src/app/pages/product/product-detail-actions/product-detail-actions.component.html
  src/app/pages/product/product-detail-actions/product-detail-actions.component.spec.ts
  src/app/shared/components/product/product-add-to-compare/product-add-to-compare.component.html
  src/app/shell/header/product-compare-status/product-compare-status.component.html
  src/app/shell/header/product-compare-status/product-compare-status.component.spec.ts
  src/styles/pages/category/product-list.scss
Labels: bug:minor

#1085 deps: use node.js 16 LTS
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/dead-code.yml
  .github/workflows/development.yml
  .github/workflows/docs.yml
  .github/workflows/integration.yml
  .github/workflows/updates.yml
  .github/workflows/windows.yml
  .vscode/intershop.txt
  Dockerfile
  Dockerfile_reports
  docs/guides/getting-started.md
  docs/guides/migrations.md
  e2e/package.json
  e2e/test-schematics-customization.sh
  e2e/test-schematics-normal.sh
  package-lock.json
  package.json
  schematics/package.json
  scripts/build-multi-pwa.js
  scripts/upgrade-pwa.js
  templates/Dockerfile_dev
Labels: dependencies, community

#1083 chore: gitignore improvements
  .dockerignore
  package.json
  schematics/src/extension/files/__name@dasherize__/exports/.gitignore
  src/app/extensions/order-templates/exports/.gitignore
  src/app/extensions/punchout/exports/.gitignore
  src/app/extensions/quickorder/exports/.gitignore
  src/app/extensions/quoting/exports/.gitignore
  src/app/extensions/recently/exports/.gitignore
  src/app/extensions/tacton/exports/.gitignore
  src/app/extensions/wishlists/exports/.gitignore
Labels: enhancement, community

#1078 refactor(schematics): improve schema generation
  .prettierrc.json
  package-lock.json
  package.json
  schematics/package.json
  schematics/scripts/generate-schema-defs.js
  schematics/scripts/generate-schema-defs.mjs
  schematics/src/address-form-configuration/factory.ts
  schematics/src/address-form-configuration/files/__countryCode@dasherize__/address-form-__countryCode@dasherize__.configuration.ts.template
  schematics/src/address-form-configuration/schema.json
  schematics/src/azure-pipeline/schema.json
  schematics/src/cms-component/schema.json
  schematics/src/component/schema.json
  schematics/src/eslint-rule/schema.json
  schematics/src/extension/schema.json
  schematics/src/helpers/add-destroy/schema.json
  schematics/src/helpers/customized-copy/schema.json
  schematics/src/helpers/lazy-components/schema.json
  schematics/src/helpers/move-component/schema.json
  schematics/src/helpers/override/schema.json
  schematics/src/kubernetes-deployment/schema.json
  schematics/src/lazy-component/factory.ts
  schematics/src/lazy-component/factory_spec.ts
  schematics/src/lazy-component/schema.json
  schematics/src/migration/decontainerize-0.16-to-0.17/schema.json
  schematics/src/model/schema.json
  schematics/src/module/schema.json
  schematics/src/page/factory.ts
  schematics/src/page/schema.json
  schematics/src/pipe/schema.json
  schematics/src/service/schema.json
  schematics/src/store-group/schema.json
  schematics/src/store/schema.json
  schematics/src/utils/ts-morph.ts
Labels: enhancement, community

#1086 Feature: Enable nginx access logging in json format
  .vscode/intershop.txt
  docs/concepts/logging.md
  nginx/Dockerfile
  nginx/nginx.conf
  nginx/templates/multi-channel.conf.tmpl
Labels: enhancement

#1090 test: use correct MockComponent and MockDirective
  src/app/pages/account-overview/account-overview/account-overview.component.spec.ts
  src/app/pages/category/category-categories/category-categories.component.spec.ts
  src/app/pages/category/category-products/category-products.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
  src/app/pages/checkout-payment/payment-concardis-creditcard/payment-concardis-creditcard.component.spec.ts
  src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.spec.ts
  src/app/pages/search/search-result/search-result.component.spec.ts
  src/app/shared/components/basket/basket-cost-summary/basket-cost-summary.component.spec.ts
  src/app/shared/components/basket/basket-promotion-code/basket-promotion-code.component.spec.ts
  src/app/shared/components/common/accordion-item/accordion-item.component.spec.ts
  src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.spec.ts
  src/app/shell/header/header-default/header-default.component.spec.ts
Labels: refactoring, community

#1088 refactor: disconnect pricing from product view model
  src/app/core/facades/product-context.facade.spec.ts
  src/app/core/facades/product-context.facade.ts
  src/app/core/facades/shopping.facade.ts
  src/app/core/models/price-item/price-item.helper.ts
  src/app/core/models/price/price.model.ts
  src/app/core/models/product-view/product-view.model.spec.ts
  src/app/core/models/product-view/product-view.model.ts
  src/app/core/routing/product/product.route.spec.ts
  src/app/core/store/shopping/products/products.selectors.spec.ts
  src/app/core/store/shopping/products/products.selectors.ts
  src/app/pages/compare/product-compare-list/product-compare-list.component.spec.ts
  src/app/pages/product/product-detail-actions/product-detail-actions.component.spec.ts
  src/app/pages/product/product-page.component.spec.ts
  src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.html
  src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.spec.ts
  src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.ts
  src/app/shared/components/product/product-price/product-price.component.spec.ts
  src/app/shared/components/product/product-price/product-price.component.ts
Labels: refactoring, community

#1067 feat: display feedback when product is out of stock on order templates
  src/app/extensions/order-templates/facades/order-templates.facade.ts
  src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-line-item/account-order-template-detail-line-item.component.html
  src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-line-item/account-order-template-detail-line-item.component.spec.ts
  src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-line-item/account-order-template-detail-line-item.component.ts
  src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.html
  src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.spec.ts
  src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.ts
  src/app/extensions/order-templates/store/order-template/order-template.selectors.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement, community

#1084 refactor: compile schematics into a dist folder
  .dockerignore
  .eslintignore
  .prettierignore
  package-lock.json
  package.json
  schematics/.gitignore
  schematics/package.json
  schematics/scripts/copy-dist-files.mjs
  schematics/scripts/generate-schema-defs.mjs
  schematics/src/address-form-configuration/factory.ts
  schematics/src/address-form-configuration/factory_spec.ts
  schematics/src/azure-pipeline/factory.ts
  schematics/src/cms-component/factory.ts
  schematics/src/cms-component/factory_spec.ts
  schematics/src/component/factory.ts
  schematics/src/component/factory_spec.ts
  schematics/src/eslint-rule/factory_spec.ts
  schematics/src/extension/factory.ts
  schematics/src/extension/factory_spec.ts
  schematics/src/helpers/add-destroy/factory.ts
  schematics/src/helpers/add-destroy/factory_spec.ts
  schematics/src/helpers/customized-copy/factory.ts
  schematics/src/helpers/customized-copy/factory_spec.ts
  schematics/src/helpers/lazy-components/factory.ts
  schematics/src/helpers/move-component/factory.ts
  schematics/src/helpers/move-component/factory_spec.ts
  schematics/src/helpers/override/factory.ts
  schematics/src/helpers/override/factory_spec.ts
  schematics/src/kubernetes-deployment/factory.ts
  schematics/src/lazy-component/factory.ts
  schematics/src/lazy-component/factory_spec.ts
  schematics/src/migration/decontainerize-0.16-to-0.17/factory.ts
  schematics/src/model/factory.ts
  schematics/src/model/factory_spec.ts
  schematics/src/module/factory.ts
  schematics/src/module/factory_spec.ts
  schematics/src/package.json
  schematics/src/page/factory.ts
  schematics/src/page/factory_spec.ts
  schematics/src/pipe/factory.ts
  schematics/src/pipe/factory_spec.ts
  schematics/src/service/factory.ts
  schematics/src/service/factory_spec.ts
  schematics/src/store-group/factory.ts
  schematics/src/store-group/factory_spec.ts
  schematics/src/store/factory.ts
  schematics/src/store/factory_spec.ts
  schematics/src/utils/lint-fix-mock.js
  schematics/src/utils/registration.ts
  schematics/src/utils/testHelper.ts
  schematics/src/utils/ts-morph.ts
  schematics/tsconfig.json
Labels: refactoring, community

#1093 refactor: interpolate date placeholders
  src/app/core/internationalization.module.ts
  src/app/core/utils/translate/translations-generator.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement, community

#1094 chore: fix import in identity-provider module
  src/app/core/identity-provider.module.ts
Labels: bug:minor, community

#1096 perf: faster npm install
  .github/workflows/updates.yml
  Dockerfile
  Dockerfile_reports
  package.json
Labels: performance, community
