Repository intershop/intershop-pwa, pull requests merged in 2022-10, with the labels that each got.

#1250 fix: respect navigation root when displaying the breadcrumb of cms pages
  src/app/core/facades/cms.facade.ts
  src/app/core/store/content/pages/pages.actions.ts
  src/app/core/store/content/pages/pages.effects.spec.ts
  src/app/core/store/content/pages/pages.effects.ts
  src/app/core/store/content/pages/pages.selectors.spec.ts
  src/app/core/store/content/pages/pages.selectors.ts
  src/app/shared/cms/components/cms-static-page/cms-static-page.component.ts
Labels: bug

#1287 fix: show mini cart animation after add quote to cart
  src/app/core/services/basket/basket.service.ts
  src/app/extensions/quoting/store/quoting/quoting.effects.spec.ts
  src/app/extensions/quoting/store/quoting/quoting.effects.ts
Labels: bug:minor

#1289 feat: support for two separate applications in hybrid mode
  docs/concepts/hybrid-approach.md
  nginx/templates/multi-channel.conf.tmpl
  server.ts
  src/app/core/store/core/configuration/configuration.reducer.ts
  src/app/core/store/core/configuration/configuration.selectors.ts
  src/app/core/store/hybrid/hybrid.selectors.ts
  src/environments/environment.model.ts
  src/hybrid/default-url-mapping-table.ts
  src/main.server.ts
Labels: feature

#1288 refactor: rename environment variable 'ICM_IDENTITY_PROVIDER'
  docs/guides/migrations.md
  docs/guides/ssr-startup.md
  src/app/core/store/core/configuration/configuration.effects.ts
Labels: refactoring

#1214 feat: add landing page for confirmation data request
  .dockerignore
  .gitignore
  server.ts
  src/app/core/configuration.module.ts
  src/app/core/facades/account.facade.ts
  src/app/core/models/data-request/data-request.interface.ts
  src/app/core/models/data-request/data-request.mapper.spec.ts
  src/app/core/models/data-request/data-request.mapper.ts
  src/app/core/models/data-request/data-request.model.ts
  src/app/core/services/data-requests/data-requests.service.spec.ts
  src/app/core/services/data-requests/data-requests.service.ts
  src/app/core/store/customer/customer-store.module.ts
  src/app/core/store/customer/customer-store.spec.ts
  src/app/core/store/customer/customer-store.ts
  src/app/core/store/customer/data-requests/data-requests.actions.ts
  src/app/core/store/customer/data-requests/data-requests.effects.spec.ts
  src/app/core/store/customer/data-requests/data-requests.effects.ts
  src/app/core/store/customer/data-requests/data-requests.reducer.ts
  src/app/core/store/customer/data-requests/data-requests.selectors.spec.ts
  src/app/core/store/customer/data-requests/data-requests.selectors.ts
  src/app/core/store/customer/data-requests/index.ts
  src/app/core/utils/http-error/data-request.error-handler.ts
  src/app/pages/app-routing.module.ts
  src/app/pages/data-request/data-request-page.component.html
  src/app/pages/data-request/data-request-page.component.spec.ts
  src/app/pages/data-request/data-request-page.component.ts
  src/app/pages/data-request/data-request-page.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1284 feat: redirect page for customer approval
  src/app/core/facades/account.facade.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/core/store/customer/user/user.actions.ts
  src/app/core/store/customer/user/user.effects.spec.ts
  src/app/core/store/customer/user/user.effects.ts
  src/app/core/store/customer/user/user.reducer.ts
  src/app/core/store/customer/user/user.selectors.spec.ts
  src/app/core/store/customer/user/user.selectors.ts
  src/app/core/utils/http-error/login-user.error-handler.ts
  src/app/pages/registration/registration-approval/registration-approval.component.html
  src/app/pages/registration/registration-approval/registration-approval.component.spec.ts
  src/app/pages/registration/registration-approval/registration-approval.component.ts
  src/app/pages/registration/registration-page.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1304 chore: upgrade github actions
  .github/workflows/automated-upgrade.yml
  .github/workflows/dead-code.yml
  .github/workflows/demo-server-up.yml
  .github/workflows/development.yml
  .github/workflows/docs.yml
  .github/workflows/integration.yml
  .github/workflows/reports.yml
  .github/workflows/updates.yml
  .github/workflows/windows.yml
Labels: community

#1310 fix: add matrix parameter spgid to promotion REST calls
  src/app/core/services/promotions/promotions.service.spec.ts
  src/app/core/services/promotions/promotions.service.ts
Labels: bug
