Repository intershop/intershop-pwa, pull requests merged in 2022-05, with the labels that each got.

#1122 refactor: delegate types in lazy-component schematic
  schematics/src/lazy-component/factory.ts
  schematics/src/lazy-component/factory_spec.ts
  schematics/src/lazy-component/files/__name@dasherize__/__name@dasherize__.component.ts.template
Labels: enhancement, community

#1135 refactor: use date as model for date picker
  src/app/core/utils/date-helper.spec.ts
  src/app/core/utils/date-helper.ts
  src/app/shared/components/basket/basket-desired-delivery-date/basket-desired-delivery-date.component.spec.ts
  src/app/shared/components/basket/basket-desired-delivery-date/basket-desired-delivery-date.component.ts
  src/app/shared/formly/types/date-picker-field/date-picker-field.component.spec.ts
  src/app/shared/formly/types/date-picker-field/date-picker-field.component.ts
  src/app/shared/formly/types/date-picker-field/fixed-format-adapter.ts
  src/app/shared/formly/types/date-picker-field/ish-datepicker-i18n.ts
  src/app/shared/formly/types/date-picker-field/localized-parser-formatter.ts
  src/app/shared/formly/types/types.module.ts
  src/app/shared/forms/validators/special-validators.ts
Labels: enhancement, community

#1138 fix: use feature subscription instead of static check in lazy components
  schematics/src/lazy-component/factory.ts
  schematics/src/lazy-component/factory_spec.ts
  schematics/src/lazy-component/files/__name@dasherize__/__name@dasherize__.component.ts.template
  src/app/core/utils/feature-toggle/feature-toggle.service.ts
Labels: bug, community

#1115 URL encode formParamsToString values
  src/app/core/utils/url-form-params.spec.ts
  src/app/core/utils/url-form-params.ts
Labels: bug, community

#1120 refactor: restrict display types of components
  src/app/extensions/compare/shared/product-add-to-compare/product-add-to-compare.component.ts
  src/app/pages/product/retail-set-parts/retail-set-parts.component.ts
  src/app/shared/cms/components/cms-product-list-category/cms-product-list-category.component.html
  src/app/shared/cms/components/cms-product-list-filter/cms-product-list-filter.component.html
  src/app/shared/cms/components/cms-product-list-manual/cms-product-list-manual.component.html
  src/app/shared/components/product/product-item/product-item.component.ts
  src/app/shared/components/product/product-promotion/product-promotion.component.ts
  src/app/shared/components/product/products-list/products-list.component.ts
Labels: enhancement, community

#1047 feat: clean-localizations on used sources
  docs/concepts/localization.md
  scripts/clean-up-localizations.js
  templates/webpack/webpack.custom.ts
Labels: enhancement, community

#1089 feat: introduce price update strategies
  src/app/core/configurations/injection-keys.ts
  src/app/core/facades/product-context.facade.ts
  src/app/core/facades/shopping.facade.ts
  src/app/core/models/price/price.model.ts
  src/app/core/store/shopping/products/products.effects.spec.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/environments/environment.model.ts
Labels: enhancement, community

#1139 fix: enable locale override for development mode
  src/app/core/store/core/configuration/configuration.selectors.spec.ts
  src/app/core/store/core/configuration/configuration.selectors.ts
  src/environments/environment.model.ts
Labels: enhancement, community

#1091 build: add pipeline for automated upgrade
  .github/workflows/automated-upgrade.yml
  scripts/upgrade-pwa.js
Labels: dependencies, nice to have, community

#1146 fix(schematics): make override schematic robust to path seperators
  schematics/src/helpers/override/factory.ts
  schematics/src/helpers/override/factory_spec.ts
Labels: bug:minor

#1148 fix: cookie page guard should only use NgModal on browser
  src/app/pages/cookies/cookies-page.guard.ts
Labels: bug:minor

#1145 feat: display dynamic promotion messages on the shopping cart page
  src/app/pages/basket/shopping-basket/shopping-basket.component.html
Labels: feature

#1142 chore: remove useless schematics vscode extension
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  .vscode/settings.json
  docs/concepts/cms-integration.md
Labels: wait

#1153 fix: only update cost center when it actually changes
  src/app/shared/components/basket/basket-cost-center-selection/basket-cost-center-selection.component.html
  src/app/shared/components/basket/basket-cost-center-selection/basket-cost-center-selection.component.spec.ts
  src/app/shared/components/basket/basket-cost-center-selection/basket-cost-center-selection.component.ts
Labels: bug:minor

#1162 fix: lazy check for available product links
  src/app/pages/product/product-links-carousel/product-links-carousel.component.html
  src/app/pages/product/product-links-carousel/product-links-carousel.component.spec.ts
  src/app/pages/product/product-links-carousel/product-links-carousel.component.ts
Labels: enhancement, performance, community

#1119 perf(test): local jest speedup
  jest.config.haste-map.js
  jest.config.js
Labels: enhancement, community

#1118 fix: use jest test related for cleanup-testbed
  .github/workflows/development.yml
  scripts/cleanup-testbed.mjs
Labels: enhancement, community

#1171 deps: dependencies upgrade (Angular 13.3.9)
  eslint-rules/src/rules/no-formly-explicit-pseudo-type.ts
  package-lock.json
  package.json
  schematics/src/component/factory_spec.ts
  scripts/upgrade-pwa.js
Labels: dependencies

#1167 fix: preserve semicolons in query params
  src/app/core/routing/pwa-url.serializer.spec.ts
  src/app/core/routing/pwa-url.serializer.ts
Labels: bug, community
