Repository intershop/intershop-pwa, pull requests merged in 2022-07, with the labels that each got.

#1199 fix: make default favicon accessible from root
  angular.json
  nginx/templates/multi-channel.conf.tmpl
  server.ts
  templates/webpack/webpack.custom.ts
Labels: bug, community

#1207 fix: purgecss exeption for generated filter-layer CSS classes (#1204)
  src/styles/pages/category/filter-panel.scss
  src/styles/pages/category/product-list.scss
Labels: bug

#1128 chore(schematics): remove deprecated customized-copy schematic
  docs/guides/customizations.md
  docs/guides/migrations.md
  e2e/test-schematics-customization.sh
  schematics/src/collection.json
  schematics/src/helpers/customized-copy/factory.ts
  schematics/src/helpers/customized-copy/factory_spec.ts
  schematics/src/helpers/customized-copy/schema.json
Labels: wait, community

#1080 refactor: introduce SSR variable for platform checks
  .eslintrc.json
  docs/concepts/configuration.md
  docs/guides/migrations.md
  eslint-rules/src/rules/use-ssr-variable-instead-of-platform-id.ts
  eslint-rules/tests/use-ssr-variable-instead-of-platform-id.spec.ts
  src/app/app.component.ts
  src/app/core/directives/intersection-observer.directive.ts
  src/app/core/facades/checkout.facade.ts
  src/app/core/guards/auth.guard.ts
  src/app/core/identity-provider.module.ts
  src/app/core/identity-provider/identity-provider.factory.ts
  src/app/core/interceptors/icm-error-mapper.interceptor.ts
  src/app/core/interceptors/universal-mock.interceptor.ts
  src/app/core/store/core/configuration/configuration.effects.ts
  src/app/core/store/core/server-config/server-config.effects.ts
  src/app/core/store/core/viewconf/viewconf.effects.ts
  src/app/core/store/customer/basket/basket.effects.ts
  src/app/core/store/customer/orders/orders.effects.ts
  src/app/core/store/customer/user/user.effects.ts
  src/app/core/store/hybrid/hybrid-store.module.ts
  src/app/core/store/hybrid/hybrid.effects.ts
  src/app/core/store/shopping/products/products.effects.ts
  src/app/core/store/shopping/search/search.effects.ts
  src/app/core/utils/api-token/api-token.service.ts
  src/app/core/utils/cookies/cookies.service.ts
  src/app/core/utils/http-status-code/http-status-code.service.spec.ts
  src/app/core/utils/http-status-code/http-status-code.service.ts
  src/app/core/utils/state-transfer/state-properties.service.ts
  src/app/core/utils/translate/fallback-missing-translation-handler.ts
  src/app/core/utils/translate/icm-translate-loader.ts
  src/app/extensions/punchout/pages/punchout/punchout-page.guard.ts
  src/app/extensions/sentry/sentry.module.ts
  src/app/extensions/sentry/store/sentry-config/sentry-config.effects.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
  src/app/extensions/store-locator/store/store-locator-config/store-locator-config.effects.ts
  src/app/extensions/tracking/store/tracking-config/tracking-config.effects.ts
  src/app/pages/category/category-categories/category-categories.component.ts
  src/app/pages/category/category-products/category-products.component.ts
  src/app/pages/cookies/cookies-page.guard.ts
  src/app/pages/login/login-page.component.ts
  src/app/pages/search/search-result/search-result.component.ts
  src/app/shell/application/cookies-banner/cookies-banner.component.ts
  src/app/shell/footer/footer/footer.component.ts
  src/setupJest.ts
  src/typings.d.ts
  src/typings.spec.d.ts
  templates/webpack/webpack.custom.ts
  tsconfig.app.json
Labels: refactoring, community, vote

#1166 feat: CMS managed footer
  docs/guides/migrations.md
  e2e/cypress/integration/pages/footer.module.ts
  src/app/shell/footer/footer/footer.component.html
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature, has conflicts

#1164 feat(seo): optimized product URLs with full category path
  e2e/cypress/integration/pages/shopping/product-detail.page.ts
  e2e/cypress/integration/specs/system/seo-product-detail-page.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/seo-search-page.b2c.e2e-spec.ts
  e2e/test-universal.sh
  src/app/core/directives/server-html.directive.spec.ts
  src/app/core/facades/product-context.facade.spec.ts
  src/app/core/models/content-view/content-view.helper.spec.ts
  src/app/core/models/product-view/product-view.model.spec.ts
  src/app/core/models/product-view/product-view.model.ts
  src/app/core/routing/product/product-route.pipe.ts
  src/app/core/routing/product/product.route.spec.ts
  src/app/core/routing/product/product.route.ts
  src/app/core/routing/routing.integration.spec.ts
  src/app/core/store/shopping/products/products.selectors.ts
  src/app/core/utils/link-parser.spec.ts
  src/app/core/utils/link-parser.ts
  src/app/core/utils/routing.ts
  src/app/pages/product/product-page.component.spec.ts
  src/app/pages/product/product-page.module.ts
Labels: has conflicts

#1191 feat: additional features extending defaults in multi-site
  docs/guides/multi-site-configurations.md
  nginx/templates/multi-channel.conf.tmpl
  src/app/core/configurations/configuration.meta.ts
  src/app/core/store/core/configuration/configuration.reducer.ts
  src/app/core/store/core/configuration/configuration.selectors.spec.ts
  src/app/core/store/core/configuration/configuration.selectors.ts
Labels: enhancement, community

#1133 feat: complex configuration can be supplied as yaml
  docker-compose.yml
  package-lock.json
  package.json
  src/app/core/store/core/configuration/configuration.actions.ts
  src/app/core/store/core/configuration/configuration.effects.ts
  src/app/core/store/core/configuration/configuration.reducer.ts
  src/app/core/utils/functions.spec.ts
  src/app/core/utils/functions.ts
  src/app/core/utils/state-transfer/state-properties.service.spec.ts
  src/app/core/utils/state-transfer/state-properties.service.ts
  src/app/extensions/tacton/store/tacton-config/tacton-config.effects.ts
Labels: enhancement, community

#1190 feat: active files report includes style files
  scripts/dead-files.js
  templates/webpack/webpack.custom.ts
Labels: enhancement, community

#1066 fix: disable add-to-basket when quantity is zero
  src/app/core/facades/product-context.facade.ts
  src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.spec.ts
  src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.ts
Labels: bug, community

#1227 fix: display confirmation page returning from redirect after checkout
  src/app/pages/checkout/checkout-page.module.ts
Labels: bug

#1228 fix: failing precommit hook, if this commit doesn't include tests
  package.json
Labels: bug

#1168 feat: Angular A11y ESLint Rules (Accessibility)
  .eslintrc.json
  src/app/extensions/tacton/pages/configure/tacton-group/tacton-group.component.html
  src/app/extensions/tacton/pages/configure/tacton-image-text-buttons/tacton-image-text-buttons.component.html
  src/app/extensions/tacton/pages/configure/tacton-image-text-buttons/tacton-image-text-buttons.component.spec.ts
  src/app/extensions/tacton/pages/configure/tacton-selected-image/tacton-selected-image.component.html
  src/app/pages/category/category-image/category-image.component.html
  src/app/pages/product/product-master-variations/product-master-variations.component.html
  src/app/pages/product/product-master-variations/product-master-variations.component.spec.ts
  src/app/shared/components/product/product-listing/product-listing.component.html
  src/app/shared/components/promotion/promotion-details/promotion-details.component.html
  src/app/shell/header/header-checkout/header-checkout.component.html
  src/app/shell/header/header-checkout/header-checkout.component.spec.ts
  src/app/shell/header/header-default/__snapshots__/header-default.component.spec.ts.snap
  src/app/shell/header/header-default/header-default.component.html
  src/app/shell/header/header-simple/header-simple.component.html
  src/app/shell/header/header-simple/header-simple.component.spec.ts
Labels: enhancement
