Repository intershop/intershop-pwa, pull requests merged in 2022-09, with the labels that each got.

#1268 refactor: reuse default product listing type for mobile
  src/app/core/configurations/injection-keys.ts
  src/app/core/store/shopping/product-listing/product-listing.effects.ts
  src/environments/environment.model.ts
Labels: refactoring, community

#1269 chore: remove lazy components on synchronize
  .husky/post-checkout
  schematics/src/helpers/lazy-components/factory.ts
  schematics/src/utils/lint-fix.ts
Labels: enhancement, nice to have, community

#1267 refactor: fix translations in localization files
  e2e/cypress/e2e/specs/shopping/product-reviews.b2b.e2e-spec.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#1276 fix: rework category completeness computation
  src/app/core/models/category/category.mapper.spec.ts
  src/app/core/models/category/category.mapper.ts
Labels: bug

#1277 feat: add "no server side rendering" guard to protect routes that should not be rendered in SSR
  src/app/core/guards/no-server-side-rendering.guard.ts
  src/app/pages/checkout/checkout-page.module.ts
Labels: enhancement

#1279 fix: update product information, add attributes even if the completen…
  src/app/core/models/product/product.helper.spec.ts
  src/app/core/models/product/product.helper.ts
  src/app/core/store/shopping/products/products.selectors.spec.ts
Labels: bug

#1265 Quoting feature results in a non stable application on certain pages
  src/app/extensions/quoting/facades/quoting.facade.ts
  src/app/extensions/quoting/pages/quote-list/quote-list-page.component.html
  src/app/extensions/quoting/pages/quote-list/quote-list-page.component.spec.ts
  src/app/extensions/quoting/pages/quote-list/quote-list-page.component.ts
  src/app/extensions/quoting/shared/quote-widget/quote-widget.component.html
  src/app/extensions/quoting/shared/quote-widget/quote-widget.component.ts
Labels: bug
