Repository intershop/intershop-pwa, pull requests merged in 2022-01, with the labels that each got.

#975 fix: rename component inputs named 'class' to 'cssClass'
  src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.html
  src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.html
  src/app/extensions/order-templates/shared/basket-create-order-template/basket-create-order-template.component.html
  src/app/extensions/order-templates/shared/basket-create-order-template/basket-create-order-template.component.ts
  src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.html
  src/app/extensions/order-templates/shared/product-add-to-order-template/product-add-to-order-template.component.html
  src/app/extensions/order-templates/shared/product-add-to-order-template/product-add-to-order-template.component.ts
  src/app/extensions/quoting/shared/product-add-to-quote/product-add-to-quote.component.html
  src/app/extensions/quoting/shared/product-add-to-quote/product-add-to-quote.component.ts
  src/app/extensions/quoting/shared/quote-line-item-list-element/quote-line-item-list-element.component.html
  src/app/extensions/wishlists/shared/product-add-to-wishlist/product-add-to-wishlist.component.html
  src/app/extensions/wishlists/shared/product-add-to-wishlist/product-add-to-wishlist.component.ts
  src/app/pages/basket/shopping-basket/shopping-basket.component.html
  src/app/pages/product/product-detail/product-detail.component.html
  src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.html
  src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.html
  src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.ts
  src/app/shared/components/product/product-add-to-compare/product-add-to-compare.component.html
  src/app/shared/components/product/product-add-to-compare/product-add-to-compare.component.ts
  src/app/shared/components/product/product-row/product-row.component.html
  src/app/shared/components/product/product-tile/product-tile.component.html
Labels: bug

#986 deps: update cypress from 7.x to 9.x
  e2e/cypress/integration/pages/meta-data.module.ts
  e2e/open-cypress.js
  e2e/package.json
Labels: dependencies

#979 fix: stringify SSR error if possible
  src/app/app.server.module.ts
Labels: bug, community

#973 fix: catch and log errors from translation API
  src/app/core/services/localizations/localizations.service.spec.ts
  src/app/core/services/localizations/localizations.service.ts
Labels: bug, community

#976 fix: remove matrix parameters from URL to prevent accumulation
  .eslintrc.json
  src/app/app.module.ts
  src/app/core/guards/configuration.guard.spec.ts
  src/app/core/guards/configuration.guard.ts
  src/app/core/routing/category/category.route.spec.ts
  src/app/core/routing/product/product.route.spec.ts
  src/app/core/routing/pwa-url.serializer.spec.ts
  src/app/core/routing/pwa-url.serializer.ts
  src/app/core/store/core/configuration/configuration.integration.spec.ts
  src/app/core/store/core/core-store.module.ts
  src/app/core/utils/custom-url-serializer.spec.ts
  src/hybrid/default-url-mapping-table.ts
Labels: bug, community

#991 refactor: use the ICM channel preference to configure the advancedVar…
  docs/concepts/configuration.md
  docs/guides/migrations.md
  docs/guides/multi-site-configurations.md
  nginx/README.md
  src/app/core/facades/selected-product-context.facade.ts
  src/app/core/services/filter/filter.service.spec.ts
  src/app/core/services/filter/filter.service.ts
  src/app/core/services/products/products.service.spec.ts
  src/app/core/services/products/products.service.ts
  src/app/core/store/core/server-config/server-config.selectors.ts
  src/app/core/store/shopping/recently/recently.effects.spec.ts
  src/app/core/store/shopping/recently/recently.effects.ts
  src/app/core/store/shopping/recently/recently.selectors.spec.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/pages/product/product-detail-variations/product-detail-variations.component.html
  src/app/pages/product/product-detail-variations/product-detail-variations.component.spec.ts
  src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.html
  src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.spec.ts
  src/app/shared/components/product/product-item-variations/product-item-variations.component.html
  src/app/shared/components/product/product-item-variations/product-item-variations.component.spec.ts
  src/environments/environment.b2b.ts
  src/environments/environment.model.ts
Labels: refactoring

#978 fix: lazily resolve translate service in translate compiler
  src/app/core/utils/translate/pwa-translate-compiler.ts
Labels: bug, community
