Repository intershop/intershop-pwa, pull requests merged in 2022-04, with the labels that each got.

#1112 fix: remove equal character from url slugs
  src/app/core/utils/routing.ts
Labels: bug, community

#1104 fix: display buyer information for orders
  projects/requisition-management/src/app/components/requisitions-list/requisitions-list.component.spec.ts
  projects/requisition-management/src/app/models/requisition/requisition.mapper.spec.ts
  projects/requisition-management/src/app/models/requisition/requisition.model.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-buyer-approval/requisition-buyer-approval.component.spec.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-cost-center-approval/requisition-cost-center-approval.component.spec.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-cost-center-approval/requisition-cost-center-approval.component.ts
  projects/requisition-management/src/app/store/requisitions/requisitions.selectors.spec.ts
  src/app/core/models/basket/basket.interface.ts
  src/app/core/models/basket/basket.mapper.ts
  src/app/core/models/basket/basket.model.ts
  src/app/core/models/order/order.interface.ts
  src/app/core/models/order/order.mapper.ts
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.html
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.spec.ts
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.ts
Labels: bug

#1073 feat: support language plural rules for translations
  src/app/core/utils/translate/pwa-translate-compiler.spec.ts
  src/app/core/utils/translate/pwa-translate-compiler.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement, community

#1114 chore: remove obsolete CMS LandingPage rendering component
  src/app/shared/cms/cms.module.ts
  src/app/shared/cms/components/cms-container/cms-container.component.html
  src/app/shared/cms/components/cms-landing-page/cms-landing-page.component.html
  src/app/shared/cms/components/cms-landing-page/cms-landing-page.component.spec.ts
  src/app/shared/cms/components/cms-landing-page/cms-landing-page.component.ts
  src/app/shared/shared.module.ts
Labels: refactoring

#1130 fix: reimplement tracking of anonymous basket for merge basket logic
  src/app/core/store/customer/basket/basket.effects.ts
Labels: refactoring, regression, community

#1132 chore: add pipeline for marking PRs with conflicts
  .github/workflows/mark-conflicts.yml
Labels: enhancement, community

#1129 chore: activate docs check for PRs
  .github/workflows/docs.yml
  docs/check-dead-links.js
  docs/check-dead-links.mjs
  package.json
Labels: enhancement, community

#1126 refactor: contact us as extension
  docs/concepts/configuration.md
  docs/guides/migrations.md
  src/app/app.module.ts
  src/app/core/facades/account.facade.ts
  src/app/core/store/general/general-store.module.ts
  src/app/core/store/general/general-store.ts
  src/app/extensions/contact-us/contact-us.module.ts
  src/app/extensions/contact-us/exports/contact-us-exports.module.ts
  src/app/extensions/contact-us/facades/contact-us.facade.ts
  src/app/extensions/contact-us/pages/contact-us-routing.module.ts
  src/app/extensions/contact-us/pages/contact/contact-confirmation/contact-confirmation.component.html
  src/app/extensions/contact-us/pages/contact/contact-confirmation/contact-confirmation.component.spec.ts
  src/app/extensions/contact-us/pages/contact/contact-confirmation/contact-confirmation.component.ts
  src/app/extensions/contact-us/pages/contact/contact-form/contact-form.component.html
  src/app/extensions/contact-us/pages/contact/contact-form/contact-form.component.spec.ts
  src/app/extensions/contact-us/pages/contact/contact-form/contact-form.component.ts
  src/app/extensions/contact-us/pages/contact/contact-page.component.html
  src/app/extensions/contact-us/pages/contact/contact-page.component.spec.ts
  src/app/extensions/contact-us/pages/contact/contact-page.component.ts
  src/app/extensions/contact-us/pages/contact/contact-page.module.ts
  src/app/extensions/contact-us/services/contact/contact.service.spec.ts
  src/app/extensions/contact-us/services/contact/contact.service.ts
  src/app/extensions/contact-us/store/contact-us-store.module.ts
  src/app/extensions/contact-us/store/contact-us-store.ts
  src/app/extensions/contact-us/store/contact/contact.actions.ts
  src/app/extensions/contact-us/store/contact/contact.effects.spec.ts
  src/app/extensions/contact-us/store/contact/contact.effects.ts
  src/app/extensions/contact-us/store/contact/contact.reducer.ts
  src/app/extensions/contact-us/store/contact/contact.selectors.spec.ts
  src/app/extensions/contact-us/store/contact/contact.selectors.ts
  src/app/extensions/contact-us/store/contact/index.ts
  src/app/pages/app-routing.module.ts
  src/app/shared/shared.module.ts
  src/environments/environment.b2b.ts
  src/environments/environment.b2c.ts
  src/environments/environment.model.ts
Labels: refactoring, community

#1123 refactor: store locator footer component as lazy extension component
  .dockerignore
  src/app/extensions/store-locator/exports/.gitignore
  src/app/extensions/store-locator/exports/store-locator-exports.module.ts
  src/app/extensions/store-locator/shared/store-locator-footer/store-locator-footer.component.html
  src/app/extensions/store-locator/shared/store-locator-footer/store-locator-footer.component.spec.ts
  src/app/extensions/store-locator/shared/store-locator-footer/store-locator-footer.component.ts
  src/app/extensions/store-locator/store-locator.module.ts
  src/app/shell/footer/footer-top/footer-top.component.html
  src/app/shell/footer/footer-top/footer-top.component.ts
  src/app/shell/footer/footer/footer.component.html
  src/app/shell/footer/footer/footer.component.spec.ts
  src/app/shell/shell.module.ts
Labels: refactoring, community

#1121 feat(eslint): rule disallowing optional inputs
  .eslintrc.json
  eslint-rules/src/rules/no-optional-inputs.ts
  eslint-rules/tests/no-optional-inputs.spec.ts
  projects/organization-management/src/app/components/cost-center-budget/cost-center-budget.component.ts
  projects/organization-management/src/app/components/cost-center-form/cost-center-form.component.ts
  projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.ts
  projects/organization-management/src/app/components/user-profile-form/user-profile-form.component.ts
  projects/requisition-management/src/app/pages/requisition-detail/budget-bar/budget-bar.component.ts
  src/app/extensions/compare/shared/product-add-to-compare/product-add-to-compare.component.ts
  src/app/extensions/order-templates/pages/account-order-template/account-order-template-list/account-order-template-list.component.ts
  src/app/extensions/order-templates/shared/basket-create-order-template/basket-create-order-template.component.ts
  src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.ts
  src/app/extensions/order-templates/shared/product-add-to-order-template/product-add-to-order-template.component.ts
  src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.ts
  src/app/extensions/quoting/pages/quote-list/quote-list/quote-list.component.ts
  src/app/extensions/quoting/shared/product-add-to-quote/product-add-to-quote.component.ts
  src/app/extensions/tacton/shared/tacton-configure-product/tacton-configure-product.component.ts
  src/app/extensions/wishlists/shared/product-add-to-wishlist/product-add-to-wishlist.component.ts
  src/app/extensions/wishlists/shared/wishlist-preferences-dialog/wishlist-preferences-dialog.component.ts
  src/app/pages/product/retail-set-parts/retail-set-parts.component.ts
  src/app/shared/cms/components/content-slot/content-slot.component.ts
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.ts
  src/app/shared/components/common/info-box/info-box.component.ts
  src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.ts
  src/app/shared/components/line-item/line-item-list/line-item-list.component.ts
  src/app/shared/components/order/order-list/order-list.component.ts
  src/app/shared/components/product/product-add-to-basket/product-add-to-basket.component.ts
  src/app/shared/components/product/product-image/product-image.component.ts
  src/app/shared/components/product/product-list/product-list.component.ts
  src/app/shared/components/product/product-listing/product-listing.component.ts
  src/app/shared/components/product/product-promotion/product-promotion.component.ts
  src/app/shared/components/search/search-box/search-box.component.ts
Labels: enhancement, community

#1100 refactor: fetch personalization as part of the user login
  src/app/core/models/customer/customer.model.ts
  src/app/core/services/personalization/personalization.service.spec.ts
  src/app/core/services/personalization/personalization.service.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/core/store/customer/customer-store.spec.ts
  src/app/core/store/customer/user/user.actions.ts
  src/app/core/store/customer/user/user.effects.spec.ts
  src/app/core/store/customer/user/user.effects.ts
  src/app/core/store/customer/user/user.reducer.ts
Labels: refactoring, community
