Repository intershop/intershop-pwa, pull requests merged in 2022-08, with the labels that each got.

#1226 fix: prevent linting for running schematics with dry-run option
  schematics/src/utils/lint-fix.ts
Labels: bug:minor

#1230 feat: display multiple basket errors
  e2e/cypress/e2e/specs/checkout/basket-handling.b2c.e2e-spec.ts
  src/app/core/interceptors/icm-error-mapper.interceptor.spec.ts
  src/app/core/interceptors/icm-error-mapper.interceptor.ts
  src/app/core/models/http-error/http-error.model.ts
  src/app/core/services/basket/basket.service.ts
  src/app/core/store/customer/basket/basket-items.effects.spec.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.reducer.ts
  src/app/pages/basket/shopping-basket/shopping-basket.component.html
  src/app/pages/basket/shopping-basket/shopping-basket.component.spec.ts
  src/app/shared/components/basket/basket-error-message/basket-error-message.component.html
  src/app/shared/components/basket/basket-error-message/basket-error-message.component.spec.ts
  src/app/shared/components/basket/basket-error-message/basket-error-message.component.ts
  src/app/shared/components/basket/mini-basket-content/mini-basket-content.component.html
  src/app/shared/components/common/error-message/error-message.component.ts
  src/app/shared/shared.module.ts
Labels: bug, feature

#1234 fix: unnecessary emissions of the getCurrentBasket selector if the ba…
  src/app/core/store/customer/basket/basket.selectors.ts
Labels: bug, performance

#1240 fix: correct selector for custom components in projects generated by …
  schematics/customization/add/index.js
Labels: bug:minor

#1238 feat: show system reject errors for requisition
  projects/requisition-management/src/app/models/requisition/requisition.interface.ts
  projects/requisition-management/src/app/models/requisition/requisition.mapper.spec.ts
  projects/requisition-management/src/app/models/requisition/requisition.mapper.ts
  projects/requisition-management/src/app/models/requisition/requisition.model.ts
  projects/requisition-management/src/app/pages/requisition-detail/requisition-summary/requisition-summary.component.html
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement

#1241 fix: prevent directory traversal on SSR
  server.ts
Labels: bug:major

#1180 Add Back To Top Button
  e2e/cypress/e2e/framework/index.ts
  e2e/cypress/support/commands.js
  src/app/shell/header/back-to-top/back-to-top.component.html
  src/app/shell/header/back-to-top/back-to-top.component.spec.ts
  src/app/shell/header/back-to-top/back-to-top.component.ts
  src/app/shell/header/header/header.component.html
  src/app/shell/header/header/header.component.spec.ts
  src/app/shell/shell.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/components/header/back-to-top.scss
  src/styles/main.scss
Labels: enhancement, feature

#1255 chore: devcontainer optimization
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/shellrc.sh
  .vscode/extensions.json
  scripts/check-file-synchronization.js
Labels: community

#1254 fix: add missing translation key for company information on registration page
  src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#1252 fix: display variation products if a non-matching product filter has previously been set
  docs/guides/migrations.md
  src/app/shared/components/product/product-image/product-image.component.html
  src/app/shared/components/product/product-image/product-image.component.ts
  src/app/shared/components/product/product-listing/product-listing.component.ts
  src/app/shared/components/product/product-name/product-name.component.html
  src/app/shared/components/product/product-name/product-name.component.ts
Labels: bug

#1261 fix: do not override favicon if requested from assets
  server.ts
Labels: bug, community

#1260 chore: enable multi container deployments in our demo environment
  .github/scripts/docker-compose.py
  .github/scripts/requirements.txt
  .github/workflows/demo-server-up.yml
  .prettierignore
Labels: enhancement

#1249 fix: show success messages for cost center buyer actions (#959)
  projects/organization-management/src/app/components/cost-center-buyer-edit-dialog/cost-center-buyer-edit-dialog.component.spec.ts
  projects/organization-management/src/app/components/cost-center-buyer-edit-dialog/cost-center-buyer-edit-dialog.component.ts
  projects/organization-management/src/app/store/cost-centers/cost-centers.effects.spec.ts
  projects/organization-management/src/app/store/cost-centers/cost-centers.effects.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor
