Repository intershop/intershop-pwa, pull requests merged in 2022-02, with the labels that each got.

#993 fix: respect ICM setting basket.maxItemQuantity
  docs/guides/migrations.md
  src/app/core/facades/product-context.facade.spec.ts
  src/app/core/facades/product-context.facade.ts
  src/app/core/facades/selected-product-context.facade.ts
  src/app/core/models/product/__snapshots__/product.mapper.spec.ts.snap
  src/app/core/models/product/product.mapper.ts
Labels: bug

#949 Scrolling to error message
  src/app/core/directives.module.ts
  src/app/core/directives/scroll.directive.ts
  src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.html
  src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.spec.ts
  src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.ts
Labels: enhancement

#998 fix: fix missing space on caching ignore (entrypoint.sh)
  nginx/entrypoint.sh
Labels: bug:minor

#980 chore: pm2 logging adaptions for Intershop CaaS
  server.ts
  src/ssr/server-scripts/build-ecosystem.js
Labels: nice to have, community

#995 chore: configure eslint rules to show warnings instead of errors
  .eslintrc.json
Labels: enhancement

#867 feat: local ICM cache for (performance) testing purposes
  scripts/icm-cache.js
Labels: research

#994 feat: replace product detail info accordion with tabs
  e2e/cypress/integration/pages/shopping/product-detail.page.ts
  e2e/cypress/integration/specs/shopping/variation-handling.b2b.e2e-spec.ts
  e2e/cypress/integration/specs/shopping/variation-handling.b2c.e2e-spec.ts
  src/app/pages/product/product-detail-info-accordion/product-detail-info-accordion.component.html
  src/app/pages/product/product-detail-info/product-detail-info.component.html
  src/app/pages/product/product-detail-info/product-detail-info.component.spec.ts
  src/app/pages/product/product-detail-info/product-detail-info.component.ts
  src/app/pages/product/product-detail/product-detail.component.html
  src/app/pages/product/product-detail/product-detail.component.spec.ts
  src/app/pages/product/product-page.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/pages/productdetail/productdetail.scss
Labels: feature

#1005 feat: recalculate basket after language/currency change
  src/app/core/store/customer/basket/basket.effects.spec.ts
  src/app/core/store/customer/basket/basket.effects.ts
Labels: enhancement

#1010 fix: payment redirect respects baseHref
  src/app/core/services/order/order.service.spec.ts
  src/app/core/services/order/order.service.ts
  src/app/core/services/payment/payment.service.spec.ts
  src/app/core/services/payment/payment.service.ts
Labels: bug:major

#1014 fix: include all theme in allowed overrides
  .eslintrc.json
Labels: bug, community

#1013 fix: sanitize payment parameter form values
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
Labels: bug:minor

#1015 refactor: fix translations in localization files
  e2e/cypress/integration/specs/system/seo-home-page.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/seo-product-detail-page.b2c.e2e-spec.ts
  e2e/cypress/integration/specs/system/seo-search-page.b2c.e2e-spec.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#1006 refactor: formly cleanup
  src/app/extensions/store-locator/pages/store-locator/store-locator-page.component.spec.ts
  src/app/pages/checkout-review/checkout-review/checkout-review.component.ts
  src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.html
  src/app/pages/checkout-review/formly/checkout-review-tac-field/checkout-review-tac-field.component.ts
  src/app/pages/registration/registration-page.component.spec.ts
  src/app/pages/registration/registration-page.component.ts
  src/app/pages/registration/registration-page.guard.ts
  src/app/pages/registration/registration-page.module.ts
  src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.spec.ts
  src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
  src/app/shared/formly-address-forms/components/formly-address-form/formly-address-form.component.ts
  src/app/shared/formly-address-forms/components/formly-customer-address-form/formly-customer-address-form.component.ts
  src/app/shared/formly-address-forms/configurations/address-form-configuration.provider.ts
  src/app/shared/formly-address-forms/configurations/address-form.configuration.ts
  src/app/shared/formly/components/components.module.ts
  src/app/shared/formly/extensions/extensions.module.ts
  src/app/shared/formly/formly.module.ts
  src/app/shared/formly/types/types.module.ts
  src/app/shared/formly/wrappers/wrappers.module.ts
Labels: refactoring

#1023 chore: lint-hard with auto restore of configs
  .dockerignore
  .github/workflows/development.yml
  .gitignore
  package.json
  scripts/eslint-hard.js
  scripts/update-dockerignore.js
Labels: enhancement, community

#1026 chore: adapt copyright notice
  LICENSE
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#1022 fix: update propagation of parent context if child context is removed
  src/app/core/directives/product-context.directive.ts
Labels: bug, community
