Repository intershop/intershop-pwa, pull requests merged in 2023-12, with the labels that each got.

#1543 fix: handle relative links in cms content
  src/app/core/directives/server-html.directive.spec.ts
  src/app/core/directives/server-html.directive.ts
Labels: bug:minor

#1553 fix: trailing '/' in path results to a wrong multi channel configuration
  nginx/templates/multi-channel.conf.tmpl
Labels: bug

#1550 fix: remove sortkey 'default' from product list REST call
  src/app/core/services/products/products.service.ts
Labels: bug:minor

#1551 fix: sanitize potentially dangerous values in order template...
  src/app/extensions/order-templates/models/order-template/order-template.mapper.ts
  src/app/extensions/order-templates/services/order-template/order-template.service.spec.ts
  src/app/extensions/order-templates/services/order-template/order-template.service.ts
  src/app/extensions/wishlists/models/wishlist/wishlist.mapper.ts
  src/app/extensions/wishlists/services/wishlist/wishlist.service.spec.ts
  src/app/extensions/wishlists/services/wishlist/wishlist.service.ts
Labels: bug

#1554 fix: use take instead of first to prevent EmptyError on missing translation
  src/app/core/utils/translate/fallback-missing-translation-handler.ts
Labels: bug

#1557 deps: update prometheus nginx exporter
  nginx/Dockerfile
Labels: dependencies, community

#1556 refactor: remove obsolete action UpdateBasketItems
  docs/guides/migrations.md
  src/app/core/models/line-item-update/line-item-update.helper.ts
  src/app/core/models/line-item-update/line-item-update.spec.ts
  src/app/core/store/customer/basket/basket-items.effects.spec.ts
  src/app/core/store/customer/basket/basket-items.effects.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.reducer.ts
Labels: refactoring, regression

#1537 feat: button for clearing basket
  src/app/core/facades/checkout.facade.ts
  src/app/core/models/basket-info/basket-info.mapper.ts
  src/app/core/services/basket-items/basket-items.service.spec.ts
  src/app/core/services/basket-items/basket-items.service.ts
  src/app/core/store/customer/basket/basket-items.effects.spec.ts
  src/app/core/store/customer/basket/basket-items.effects.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/pages/basket/shopping-basket/shopping-basket.component.html
  src/app/pages/basket/shopping-basket/shopping-basket.component.spec.ts
  src/app/shared/components/basket/clear-basket/clear-basket.component.html
  src/app/shared/components/basket/clear-basket/clear-basket.component.spec.ts
  src/app/shared/components/basket/clear-basket/clear-basket.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1552 refactor: type-safe omit helper
  src/app/core/utils/functions.ts
  src/app/core/utils/meta-reducers.ts
Labels: enhancement

#1475 feat(ICM 11): co-browsing support via CEC
  .vscode/intershop.txt
  docker-compose.yml
  docs/README.md
  docs/guides/authentication_co_browse.md
  docs/guides/authentication_punchout.md
  docs/guides/updating-pwa.md
  src/app/core/identity-provider.module.ts
  src/app/core/identity-provider/co-browse.identity-provider.spec.ts
  src/app/core/identity-provider/co-browse.identity-provider.ts
  src/app/pages/app-routing.module.ts
  src/app/pages/co-browse/co-browse-page.guard.ts
  src/app/pages/co-browse/co-browse-page.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature
