Repository intershop/intershop-pwa, pull requests merged in 2023-06, with the labels that each got.

#1431 feat: OCI punchout configuration
  .eslintrc.json
  .vscode/intershop.txt
  src/app/core/configuration.module.ts
  src/app/core/icon.module.ts
  src/app/core/utils/functions.spec.ts
  src/app/core/utils/functions.ts
  src/app/core/utils/http-error/update-oci-configuration.error-handler.ts
  src/app/extensions/punchout/facades/punchout.facade.ts
  src/app/extensions/punchout/models/oci-configuration-item/oci-configuration-item.model.ts
  src/app/extensions/punchout/models/oci-options/oci-options.interface.ts
  src/app/extensions/punchout/models/oci-options/oci-options.mapper.spec.ts
  src/app/extensions/punchout/models/oci-options/oci-options.mapper.ts
  src/app/extensions/punchout/models/oci-options/oci-options.model.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/account-punchout-configuration-page.component.html
  src/app/extensions/punchout/pages/account-punchout-configuration/account-punchout-configuration-page.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/account-punchout-configuration-page.component.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/account-punchout-configuration-page.module.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/formly/oci-configuration-mapping-repeat-field/oci-configuration-mapping-repeat-field.component.html
  src/app/extensions/punchout/pages/account-punchout-configuration/formly/oci-configuration-mapping-repeat-field/oci-configuration-mapping-repeat-field.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/formly/oci-configuration-mapping-repeat-field/oci-configuration-mapping-repeat-field.component.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/formly/oci-configuration-mapping-wrapper/oci-configuration-mapping-wrapper.component.html
  src/app/extensions/punchout/pages/account-punchout-configuration/formly/oci-configuration-mapping-wrapper/oci-configuration-mapping-wrapper.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/formly/oci-configuration-mapping-wrapper/oci-configuration-mapping-wrapper.component.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/formly/oci-configuration-repeat-field/oci-configuration-repeat-field.component.html
  src/app/extensions/punchout/pages/account-punchout-configuration/formly/oci-configuration-repeat-field/oci-configuration-repeat-field.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/formly/oci-configuration-repeat-field/oci-configuration-repeat-field.component.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/oci-configuration-form/oci-configuration-form.component.html
  src/app/extensions/punchout/pages/account-punchout-configuration/oci-configuration-form/oci-configuration-form.component.spec.ts
  src/app/extensions/punchout/pages/account-punchout-configuration/oci-configuration-form/oci-configuration-form.component.ts
  src/app/extensions/punchout/pages/account-punchout/account-punchout-header/account-punchout-header.component.html
  src/app/extensions/punchout/pages/punchout-account-routing.module.ts
  src/app/extensions/punchout/services/punchout/punchout.service.spec.ts
  src/app/extensions/punchout/services/punchout/punchout.service.ts
  src/app/extensions/punchout/store/oci-configuration/index.ts
  src/app/extensions/punchout/store/oci-configuration/oci-configuration.actions.ts
  src/app/extensions/punchout/store/oci-configuration/oci-configuration.effects.spec.ts
  src/app/extensions/punchout/store/oci-configuration/oci-configuration.effects.ts
  src/app/extensions/punchout/store/oci-configuration/oci-configuration.reducer.ts
  src/app/extensions/punchout/store/oci-configuration/oci-configuration.selectors.spec.ts
  src/app/extensions/punchout/store/oci-configuration/oci-configuration.selectors.ts
  src/app/extensions/punchout/store/punchout-store.module.ts
  src/app/extensions/punchout/store/punchout-store.ts
  src/app/shared/forms/validators/special-validators.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/global/buttons.scss
  src/styles/global/forms.scss
Labels: enhancement, feature

#1444 fix: save company name(s) at address after b2b customer registration
  src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
Labels: bug

#1441 Make sure that `*.mts` files are using typescript parser with prettier
  .prettierrc.json
Labels: enhancement, community

#1449 fix: product variation master facet selection does not work for non-string filters
  src/app/core/models/product-variation/product-variation.helper.ts
Labels: bug:minor

#1442 chore: add generic intersection types for ViewType & DeviceType
  src/app/core/models/viewtype/viewtype.types.ts
Labels: enhancement, community

#1434 Refactor: activate eslint rule @angular-eslint/template/accessibility-label-for
  .eslintrc.json
  projects/organization-management/src/app/components/cost-center-budget/cost-center-budget.component.html
  projects/organization-management/src/app/components/user-budget/user-budget.component.html
  projects/organization-management/src/app/components/user-roles-selection/user-roles-selection.component.html
  src/app/extensions/quoting/shared/quote-edit/quote-edit.component.html
  src/app/extensions/quoting/shared/quote-line-item-list-element/quote-line-item-list-element.component.html
  src/app/extensions/quoting/shared/quote-line-item-list-element/quote-line-item-list-element.component.spec.ts
  src/app/extensions/quoting/shared/quote-view/quote-view.component.html
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-line-item/account-wishlist-detail-line-item.component.html
  src/app/pages/account-profile-email/account-profile-email/account-profile-email.component.html
  src/app/shared/components/basket/basket-error-message/basket-error-message.component.html
  src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.html
  src/app/shared/components/line-item/line-item-edit-dialog/line-item-edit-dialog.component.spec.ts
  src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.html
  src/app/shared/components/line-item/line-item-list-element/line-item-list-element.component.spec.ts
  src/app/shared/components/product/product-id/product-id.component.html
  src/app/shared/components/product/product-variation-display/product-variation-display.component.html
  src/styles/pages/category/product-list.scss
  src/styles/pages/productdetail/product-info.scss
Labels: refactoring

#1452 fix: fix: handle token errors for local development
  src/app/core/utils/api-token/api-token.service.ts
Labels: bug:minor

#1451 fix: minor address form issues
  src/app/shared/formly-address-forms/components/formly-address-form/formly-address-form.component.ts
Labels: bug:minor
