Repository intershop/intershop-pwa, pull requests merged in 2023-03, with the labels that each got.

#1379 fix: basket page errors on reload
  src/app/core/store/customer/basket/basket.effects.spec.ts
  src/app/core/store/customer/basket/basket.effects.ts
Labels: bug, bug:major

#1384 i18n: fix translations in localization files
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#1383 feat: add title for status checkboxes
  docs/guides/formly.md
  projects/organization-management/src/app/components/cost-center-form/cost-center-form.component.ts
  projects/organization-management/src/app/components/user-profile-form/user-profile-form.component.ts
  src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.ts
  src/app/shared/formly/wrappers/horizontal-checkbox-wrapper/horizontal-checkbox-wrapper.component.html
  src/app/shared/formly/wrappers/horizontal-checkbox-wrapper/horizontal-checkbox-wrapper.component.ts
  src/app/shared/formly/wrappers/horizontal-wrapper/horizontal-wrapper.component.html
  src/app/shared/formly/wrappers/horizontal-wrapper/horizontal-wrapper.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1389 refactor: use action group creator in the store action schematics
  docs/guides/migrations.md
  schematics/src/store/factory.ts
  schematics/src/store/files/__name@dasherize__/__name@dasherize__.actions.ts.template
  schematics/src/store/files/__name@dasherize__/__name@dasherize__.effects.spec.ts.template
  schematics/src/store/files/__name@dasherize__/__name@dasherize__.effects.ts.template
  schematics/src/store/files/__name@dasherize__/__name@dasherize__.reducer.ts.template
  schematics/src/store/files/__name@dasherize__/__name@dasherize__.selectors.spec.ts.template
Labels: enhancement, refactoring

#1391 fix: quick quantity change on item lists
  docs/guides/angular-component-development.md
  docs/guides/migrations.md
  src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.html
  src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.ts
  src/app/extensions/quoting/shared/quote-line-item-list/quote-line-item-list.component.html
  src/app/extensions/quoting/shared/quote-line-item-list/quote-line-item-list.component.ts
  src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.html
  src/app/extensions/quoting/shared/quoting-basket-line-items/quoting-basket-line-items.component.ts
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.html
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.ts
Labels: bug:minor

#1270 refactor: injection token type safety
  .eslintrc.json
  .vscode/intershop.txt
  docs/concepts/configuration.md
  docs/guides/migrations.md
  eslint-rules/src/rules/use-type-safe-injection-token.ts
  eslint-rules/tests/use-type-safe-injection-token.spec.ts
  src/app/core/configurations/injection-keys.ts
  src/app/core/facades/shopping.facade.ts
  src/app/core/interceptors/mock.interceptor.ts
  src/app/core/models/price/price.model.ts
  src/app/core/store/core/configuration/configuration.effects.ts
  src/app/core/store/shopping/categories/categories.effects.ts
  src/app/core/store/shopping/product-listing/product-listing.effects.ts
  src/app/core/utils/cookies/cookies.service.ts
  src/app/core/utils/http-error/login-user.error-handler.ts
  src/app/core/utils/http-status-code/http-status-code.service.ts
  src/app/core/utils/injection.ts
  src/app/core/utils/theme/theme.service.ts
  src/app/core/utils/translate/fallback-missing-translation-handler.ts
  src/app/core/utils/translate/icm-translate-loader.ts
  src/app/extensions/compare/store/compare-store.module.ts
  src/app/extensions/recently/store/recently-store.module.ts
  src/app/extensions/seo/store/seo/seo.effects.ts
  src/app/extensions/store-locator/services/stores-map/stores-map.service.ts
  src/app/extensions/tacton/store/tacton-store.module.ts
  src/app/extensions/wishlists/shared/wishlist-widget/wishlist-widget.component.ts
  src/app/pages/cookies/cookies-modal/cookies-modal.component.ts
  src/app/pages/product/product-links-carousel/product-links-carousel.component.ts
  src/app/shared/components/login/login-form/login-form.component.ts
  src/app/shared/components/product/products-list/products-list.component.ts
  src/app/shared/formly-address-forms/configurations/address-form-configuration.provider.ts
  src/app/shared/formly/field-library/field-library.ts
  src/app/shell/header/header-navigation/header-navigation.component.ts
  src/app/shell/header/sub-category-navigation/sub-category-navigation.component.ts
  src/environments/environment.model.ts
Labels: enhancement, refactoring, community
