Repository intershop/intershop-pwa, pull requests merged in 2023-08, with the labels that each got.

#1470 chore:adjusted french and german translations
  src/assets/i18n/de_DE.json
  src/assets/i18n/fr_FR.json
Labels: nice to have

#1476 fix: repair partial build after npm upgrade
  Dockerfile
Labels: bug, regression

#1473 fix: repair caching for output-hashed files
  server.ts
Labels: bug, regression, performance

#1478 chore: reactivate curly rule
  .eslintrc.json
  e2e/cypress-ci-e2e.ts
  eslint-rules/src/rules/sort-testbed-metadata-arrays.ts
  schematics/src/utils/lint-fix.ts
  scripts/find-dead-code.ts
Labels: regression

#1474 fix: display first product image after switching products
  src/app/pages/product/product-images/product-images.component.ts
Labels: bug:minor

#1461 fix: reload the application after the pgid changed
  src/app/core/core.module.ts
  src/app/core/interceptors/pgid-change.interceptor.ts
  src/app/core/utils/api-token/api-token.service.ts
Labels: bug

#1471 fix: properly handle system signals in pwa docker container
  Dockerfile
  dist/entrypoint.sh
  docker-compose.yml
Labels: bug

#1481 fix: remove query parameter "page" for product detail page routes
  src/app/shared/components/product/product-image/product-image.component.html
  src/app/shared/components/product/product-name/product-name.component.html
Labels: bug

#1480 refactor: rename checkout field 'order reference id'
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement
