Repository intershop/intershop-pwa, pull requests merged in 2023-09, with the labels that each got.

#1465 fix: handle multitab browsing
  src/app/core/facades/account.facade.ts
  src/app/core/identity-provider/icm.identity-provider.ts
  src/app/core/utils/api-token/api-token.service.ts
  src/app/extensions/punchout/identity-provider/punchout-identity-provider.ts
Labels: bug:minor

#1494 perf: increase pm2 ssr max memory
  src/ssr/server-scripts/build-ecosystem.js
Labels: performance

#1492 fix: prevent setting values on uninitialized field
  src/app/shared/cms/components/cms-carousel/cms-carousel.component.html
  src/app/shared/cms/components/cms-carousel/cms-carousel.component.ts
Labels: bug

#1496 perf: reduce number of distributors
  src/ssr/server-scripts/build-ecosystem.js
Labels: performance

#1493 perf: reduce product price call aggregation delay
  src/app/core/store/shopping/product-prices/product-prices.effects.ts
Labels: performance

#1499 refactor: save orderReferenceId as native basket attribute
  docs/guides/migrations.md
  projects/requisition-management/src/app/models/requisition/requisition.mapper.spec.ts
  src/app/core/facades/checkout.facade.ts
  src/app/core/models/basket/basket.interface.ts
  src/app/core/models/basket/basket.mapper.spec.ts
  src/app/core/models/basket/basket.mapper.ts
  src/app/core/models/basket/basket.model.ts
  src/app/core/models/order/order.mapper.spec.ts
  src/app/core/models/order/order.mapper.ts
  src/app/core/services/basket/basket.service.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.effects.spec.ts
  src/app/core/utils/dev/basket-mock-data.ts
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.html
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.ts
  src/app/shared/components/basket/basket-order-reference/basket-order-reference.component.spec.ts
  src/app/shared/components/basket/basket-order-reference/basket-order-reference.component.ts
Labels: refactoring

#1472 feat: logging restriction to errors
  Dockerfile
  docker-compose.yml
  docs/guides/nginx-startup.md
  docs/guides/ssr-startup.md
  nginx/Dockerfile
  nginx/features/log_all-off.conf
  nginx/features/log_all.conf
  nginx/features/prometheus.conf
  nginx/templates/multi-channel.conf.tmpl
  server.ts
  src/app/core/interceptors/universal-log.interceptor.ts
Labels: nice to have

#1500 fix: prevent invoking destroyed injector
  src/app/core/utils/module-loader/module-loader.service.ts
Labels: bug, wait

#1447 feat: save language selection as cookie
  docs/concepts/configuration.md
  docs/guides/cookie-consent.md
  docs/guides/migrations.md
  e2e/cypress/e2e/specs/system/change-language-authentication.b2c.e2e-spec.ts
  src/app/core/pipes/make-href.pipe.spec.ts
  src/app/core/pipes/make-href.pipe.ts
  src/app/core/store/core/server-config/server-config.effects.spec.ts
  src/app/core/store/core/server-config/server-config.effects.ts
  src/app/core/utils/multi-site/multi-site.service.spec.ts
  src/app/core/utils/multi-site/multi-site.service.ts
  src/app/shell/header/language-switch/language-switch.component.html
  src/app/shell/header/language-switch/language-switch.component.spec.ts
  src/app/shell/header/language-switch/language-switch.component.ts
  src/environments/environment.model.ts
Labels: feature

#1504 refactor: rename 'id' to 'productListingId'
  docs/guides/migrations.md
  src/app/pages/category/category-products/category-products.component.html
  src/app/pages/product/product-master-variations/product-master-variations.component.html
  src/app/pages/product/product-master-variations/product-master-variations.component.spec.ts
  src/app/pages/search/search-result/search-result.component.html
  src/app/shared/components/product/product-listing/product-listing.component.spec.ts
  src/app/shared/components/product/product-listing/product-listing.component.ts
Labels: refactoring

#1502 uniform code-style for effects to check for ssr
  src/app/core/store/core/configuration/configuration.effects.ts
  src/app/core/store/core/messages/messages.effects.ts
  src/app/core/store/core/viewconf/viewconf.effects.ts
  src/app/core/store/customer/basket/basket.effects.ts
  src/app/core/store/customer/orders/orders.effects.ts
  src/app/core/store/customer/user/user.effects.ts
  src/app/core/store/shopping/search/search.effects.ts
Labels: refactoring

#1515 chore: add docker image names to compose file
  docker-compose.yml
Labels: nice to have
