Repository intershop/intershop-pwa, pull requests merged in 2024-05, with the labels that each got.

#1649 build: reevaluate has-conflicts label on PR push
  .github/workflows/mark-conflicts.yml
Labels: enhancement

#1643 fix: repair devcontainer init
  .devcontainer/devcontainer.json
Labels: bug, regression

#1650 perf: disable rendering of view contexts by default
  .prettierignore
  docs/concepts/cms-integration.md
  docs/guides/migrations.md
  src/app/pages/category/category-categories/category-categories.component.html
  src/app/pages/category/category-products/category-products.component.html
  src/app/pages/product/product-detail/product-detail.component.html
  src/app/pages/product/product-detail/product-detail.component.spec.ts
  src/app/pages/product/product-page.component.html
  src/app/pages/product/product-page.component.spec.ts
  src/assets/sample-data/view_contexts_import.xml
Labels: performance

#1577 feat: provide page structure tree information for the Design View
  src/app/core/utils/design-view/design-view.service.ts
  src/app/pages/content/content-page.component.html
  src/app/shared/cms/components/content-viewcontext/content-viewcontext.component.ts
Labels: enhancement

#1651 fix: show Design View editing frame highlighting inside the component to avoid cut display
  src/app/shared/cms/components/content-design-view-wrapper/content-design-view-wrapper.component.scss
Labels: bug, refactoring

#1652 fix: localization - avoid NoSuchElementException when adding a new locale
  src/app/core/utils/translate/icm-translate-loader.ts
Labels: bug

#1653 chore: add .nvmrc
  .dockerignore
  .gitignore
  .nvmrc
  .prettierignore
Labels: nice to have

#1655 fix: implement input mask for IBAN and BIC
  src/app/pages/checkout-payment/payment-parameter-form/payment-parameter-form.component.ts
Labels: bug:minor

#1659 fix: handle setting price notification for products without a price
  src/app/extensions/product-notifications/shared/product-notification-edit-form/product-notification-edit-form.component.ts
Labels: bug

#1658 fix: wishlist and order templates title with special characters not displayed correct
  src/app/core/pipes/html-encode.pipe.ts
  src/app/extensions/order-templates/models/order-template/order-template.mapper.ts
  src/app/extensions/order-templates/services/order-template/order-template.service.spec.ts
  src/app/extensions/order-templates/shared/select-order-template-modal/select-order-template-modal.component.html
  src/app/extensions/wishlists/models/wishlist/wishlist.mapper.ts
  src/app/extensions/wishlists/services/wishlist/wishlist.service.spec.ts
  src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.html
Labels: bug

#1661 refactor: classify actions
  projects/organization-management/src/app/store/budget/budget.actions.ts
  projects/organization-management/src/app/store/cost-centers/cost-centers.actions.ts
  projects/organization-management/src/app/store/cost-centers/cost-centers.effects.spec.ts
  projects/requisition-management/src/app/store/requisitions/requisitions.effects.spec.ts
  scripts/find-dead-code.ts
  src/app/core/facades/account.facade.spec.ts
  src/app/core/services/api/api.service.spec.ts
  src/app/core/store/content/pages/pages.actions.ts
  src/app/core/store/content/pages/pages.effects.spec.ts
  src/app/core/store/core/configuration/configuration.actions.ts
  src/app/core/store/core/error/error.actions.ts
  src/app/core/store/core/error/error.selectors.spec.ts
  src/app/core/store/core/viewconf/viewconf.actions.ts
  src/app/core/store/customer/addresses/addresses.actions.ts
  src/app/core/store/customer/basket/basket-payment.effects.spec.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.effects.spec.ts
  src/app/core/store/customer/orders/orders.actions.ts
  src/app/core/store/customer/orders/orders.effects.spec.ts
  src/app/core/store/customer/sso-registration/sso-registration.actions.ts
  src/app/core/store/customer/user/user.actions.ts
  src/app/core/store/general/countries/countries.actions.ts
  src/app/core/store/general/regions/regions.actions.ts
  src/app/core/store/shopping/categories/categories.actions.ts
  src/app/core/store/shopping/categories/categories.effects.spec.ts
  src/app/core/store/shopping/filter/filter.actions.ts
  src/app/core/store/shopping/product-listing/product-listing.effects.spec.ts
  src/app/core/store/shopping/product-prices/product-prices.actions.ts
  src/app/core/store/shopping/products/products.actions.ts
  src/app/core/store/shopping/promotions/promotions.actions.ts
  src/app/core/store/shopping/search/search.actions.ts
  src/app/core/store/shopping/search/search.effects.spec.ts
  src/app/core/store/shopping/shopping-store.spec.ts
  src/app/extensions/contact-us/store/contact/contact.actions.ts
  src/app/extensions/order-templates/store/order-template/order-template.actions.ts
  src/app/extensions/punchout/store/punchout-types/punchout-types.actions.ts
  src/app/extensions/punchout/store/punchout-types/punchout-types.effects.spec.ts
  src/app/extensions/punchout/store/punchout-users/punchout-users.actions.ts
  src/app/extensions/recently/store/recently/recently.actions.ts
  src/app/extensions/store-locator/store/store-locator-config/store-locator-config.actions.ts
  src/app/extensions/store-locator/store/stores/stores.actions.ts
  src/app/extensions/tacton/store/product-configuration/product-configuration.actions.ts
  src/app/extensions/tracking/store/tracking-config/tracking-config.actions.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.actions.ts
Labels: refactoring
