Repository intershop/intershop-pwa, pull requests merged in 2024-08, with the labels that each got.

#1701 fix: change facade method for eligible address determination (#98413)
  src/app/core/facades/checkout.facade.ts
Labels: bug

#1704 refactor: encoding of resource IDs
  docs/concepts/configuration.md
  docs/guides/migrations.md
  projects/organization-management/src/app/services/cost-centers/cost-centers.service.spec.ts
  projects/organization-management/src/app/services/cost-centers/cost-centers.service.ts
  projects/organization-management/src/app/services/organization-management-breadcrumb/organization-management-breadcrumb.service.ts
  projects/organization-management/src/app/services/users/users.service.spec.ts
  projects/organization-management/src/app/services/users/users.service.ts
  projects/requisition-management/src/app/services/requisitions/requisitions.service.spec.ts
  projects/requisition-management/src/app/services/requisitions/requisitions.service.ts
  src/app/core/services/address/address.service.spec.ts
  src/app/core/services/address/address.service.ts
  src/app/core/services/api/api.service.spec.ts
  src/app/core/services/api/api.service.ts
  src/app/core/services/authorization/authorization.service.spec.ts
  src/app/core/services/authorization/authorization.service.ts
  src/app/core/services/basket-items/basket-items.service.spec.ts
  src/app/core/services/basket-items/basket-items.service.ts
  src/app/core/services/basket/basket.service.spec.ts
  src/app/core/services/basket/basket.service.ts
  src/app/core/services/categories/categories.service.spec.ts
  src/app/core/services/categories/categories.service.ts
  src/app/core/services/cms/cms.service.spec.ts
  src/app/core/services/cms/cms.service.ts
  src/app/core/services/data-requests/data-requests.service.spec.ts
  src/app/core/services/data-requests/data-requests.service.ts
  src/app/core/services/newsletter/newsletter.service.spec.ts
  src/app/core/services/newsletter/newsletter.service.ts
  src/app/core/services/order/order.service.spec.ts
  src/app/core/services/order/order.service.ts
  src/app/core/services/payment/payment.service.spec.ts
  src/app/core/services/payment/payment.service.ts
  src/app/core/services/products/products.service.spec.ts
  src/app/core/services/products/products.service.ts
  src/app/core/services/promotions/promotions.service.spec.ts
  src/app/core/services/promotions/promotions.service.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/core/services/warranty/warranty.service.spec.ts
  src/app/core/services/warranty/warranty.service.ts
  src/app/core/utils/url-resource-ids.spec.ts
  src/app/core/utils/url-resource-ids.ts
  src/app/extensions/order-templates/services/order-template/order-template.service.spec.ts
  src/app/extensions/order-templates/services/order-template/order-template.service.ts
  src/app/extensions/product-notifications/services/product-notifications/product-notifications.service.spec.ts
  src/app/extensions/product-notifications/services/product-notifications/product-notifications.service.ts
  src/app/extensions/punchout/services/punchout/punchout.service.spec.ts
  src/app/extensions/punchout/services/punchout/punchout.service.ts
  src/app/extensions/quoting/services/quoting/quoting.service.spec.ts
  src/app/extensions/quoting/services/quoting/quoting.service.ts
  src/app/extensions/rating/services/reviews/reviews.service.spec.ts
  src/app/extensions/rating/services/reviews/reviews.service.ts
  src/app/extensions/wishlists/services/wishlist/wishlist.service.spec.ts
  src/app/extensions/wishlists/services/wishlist/wishlist.service.ts
  src/environments/environment.model.ts
Labels: refactoring

#1682 feat: fast checkout payment (e.g. PAYPAL Express)
  src/app/core/facades/checkout.facade.ts
  src/app/core/models/payment-method/payment-method.mapper.ts
  src/app/core/services/payment/payment.service.spec.ts
  src/app/core/services/payment/payment.service.ts
  src/app/core/store/customer/basket/basket-payment.effects.spec.ts
  src/app/core/store/customer/basket/basket-payment.effects.ts
  src/app/core/store/customer/basket/basket-validation.effects.spec.ts
  src/app/core/store/customer/basket/basket-validation.effects.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.effects.ts
  src/app/core/store/customer/basket/basket.selectors.ts
  src/app/core/utils/dev/basket-mock-data.ts
  src/app/pages/account-order/account-order/account-order.component.html
  src/app/pages/basket/basket-page.module.ts
  src/app/pages/basket/shopping-basket-payment/shopping-basket-payment.component.html
  src/app/pages/basket/shopping-basket-payment/shopping-basket-payment.component.spec.ts
  src/app/pages/basket/shopping-basket-payment/shopping-basket-payment.component.ts
  src/app/pages/basket/shopping-basket/shopping-basket.component.html
  src/app/pages/basket/shopping-basket/shopping-basket.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment-page.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment-page.component.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
  src/app/shared/components/basket/basket-buyer/basket-buyer.component.ts
  src/app/shared/components/basket/basket-payment-cost-info/basket-payment-cost-info.component.html
  src/app/shared/components/basket/basket-payment-cost-info/basket-payment-cost-info.component.spec.ts
  src/app/shared/components/basket/basket-payment-cost-info/basket-payment-cost-info.component.ts
  src/app/shared/components/common/error-message/error-message.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1697 feat: extend order list filter by buyer selection
  docs/guides/migrations.md
  projects/organization-management/src/app/components/buyers-select/buyers-select.component.html
  projects/organization-management/src/app/components/buyers-select/buyers-select.component.spec.ts
  projects/organization-management/src/app/components/buyers-select/buyers-select.component.ts
  projects/organization-management/src/app/exports/index.ts
  projects/organization-management/src/app/exports/organization-management-exports.module.ts
  projects/organization-management/src/app/facades/organization-management.facade.ts
  projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.spec.ts
  projects/organization-management/src/app/models/b2b-user/b2b-user.mapper.ts
  projects/organization-management/src/app/organization-management.module.ts
  src/app/core/facades/account.facade.ts
  src/app/core/models/order-list-query/order-list-query.model.ts
  src/app/core/services/order/order.service.ts
  src/app/pages/account-order-history/account-order-filters/account-order-filters.component.html
  src/app/pages/account-order-history/account-order-filters/account-order-filters.component.spec.ts
  src/app/pages/account-order-history/account-order-filters/account-order-filters.component.ts
  src/app/pages/account-order-history/account-order-history-page.component.html
  src/app/pages/account-order-history/account-order-history-page.component.spec.ts
  src/app/pages/account-order-history/account-order-history-page.component.ts
  src/app/pages/account-order-history/account-order-history-page.module.ts
  src/app/pages/account-order-history/formly/account-order-select-buyer-field/account-order-select-buyer-field.component.html
  src/app/pages/account-order-history/formly/account-order-select-buyer-field/account-order-select-buyer-field.component.spec.ts
  src/app/pages/account-order-history/formly/account-order-select-buyer-field/account-order-select-buyer-field.component.ts
  src/app/shared/components/order/order-list/order-list.component.html
  src/app/shared/components/order/order-list/order-list.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement
