Repository intershop/intershop-pwa, pull requests merged in 2024-06, with the labels that each got.

#1687 fix: remove '%' signs from product slugs
  src/app/core/utils/routing.ts
Labels: bug:minor

#1684 fix: add localizations for aria labels of oci punchout configuration
  src/app/extensions/punchout/pages/account-punchout-configuration/oci-configuration-form/oci-configuration-form.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug:minor

#1674 chore: sort i18n files in format task
  package.json
  scripts/sort-i18n.mjs
Labels: nice to have

#1688 fix: encode product urls
  src/app/core/facades/selected-product-context.facade.ts
  src/app/core/utils/routing.ts
Labels: bug:minor

#1679 fix: suppress the wrong display of Search-No-Results page after a search
  src/app/core/store/shopping/product-listing/product-listing.effects.spec.ts
  src/app/core/store/shopping/product-listing/product-listing.effects.ts
  src/app/core/store/shopping/search/search.effects.spec.ts
  src/app/core/store/shopping/shopping-store.spec.ts
Labels: bug

#1673 refactor: rework account-profile-user component
  src/app/pages/account-profile-user/account-profile-user-page.component.html
  src/app/pages/account-profile-user/account-profile-user-page.component.spec.ts
  src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.html
  src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.spec.ts
  src/app/pages/account-profile-user/account-profile-user/account-profile-user.component.ts
Labels: refactoring
