Repository intershop/intershop-pwa, pull requests merged in 2024-03, with the labels that each got.

#1594 deps: updates + vulnerabilities fix
  package-lock.json
  package.json
Labels: dependencies

#1586 feat: Lazy Loading of Sub categories
  src/app/core/store/shopping/categories/categories.effects.ts
  src/app/shell/header/header-navigation/header-navigation.component.html
  src/app/shell/header/header-navigation/header-navigation.component.ts
Labels: performance

#1595 refactor: minimize cookie banner
  e2e/cypress/e2e/specs/system/cookie-consent.b2c.e2e-spec.ts
  src/app/shell/application/cookies-banner/cookies-banner.component.html
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
  src/styles/components/cookies.scss
Labels: enhancement, performance

#1605 docs: documentation improvements (Redis, Address Doctor)
  docs/guides/address-doctor.md
  docs/guides/nginx-startup.md
Labels: documentation

#1604 fix: small UI issues
  src/app/pages/product/product-detail-actions/product-detail-actions.component.html
  src/app/shared/formly/types/date-picker-field/date-picker-field.component.html
  src/styles/pages/category/product-list.scss
  src/styles/pages/productdetail/productdetail.scss
Labels: bug:minor

#1599 fix: display variations when there are no variation attributes
  src/app/core/models/product-variation/product-variation.helper.ts
  src/app/core/models/product-variation/variation-attribute.mapper.ts
  src/app/core/routing/product/product.route.ts
  src/app/pages/product/product-master-variations/product-master-variations.component.html
  src/app/pages/product/product-master-variations/product-master-variations.component.spec.ts
  src/app/pages/product/product-master-variations/product-master-variations.component.ts
Labels: bug

#1592 feat: create cart from order
  src/app/pages/account-order/account-order/account-order.component.html
  src/app/pages/account-order/account-order/account-order.component.spec.ts
  src/app/pages/account-order/account-order/account-order.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1612 docs: review + improvement of NGINX and migration parts + extended Google Tag Manager information
  docs/guides/google-tag-manager.md
  docs/guides/migrations.md
  docs/guides/nginx-startup.md
  docs/guides/optimizations.md
Labels: documentation

#1608 fix: render CMS content based on component templates correctly
  src/app/core/models/content-pagelet-entry-point/content-pagelet-entry-point.mapper.spec.ts
  src/app/core/models/content-pagelet/__snapshots__/content-pagelet.mapper.spec.ts.snap
  src/app/core/models/content-pagelet/content-pagelet.mapper.spec.ts
  src/app/core/models/content-pagelet/content-pagelet.mapper.ts
Labels: bug

#1600 feat: handle complex values of variation attributes
  src/app/core/models/product-variation/product-variation.helper.spec.ts
  src/app/core/models/product-variation/product-variation.helper.ts
  src/app/core/models/product-variation/variation-attribute.model.ts
  src/app/core/pipes.module.ts
  src/app/core/pipes/variation-attribute.pipe.spec.ts
  src/app/core/pipes/variation-attribute.pipe.ts
  src/app/shared/components/product/product-variation-display/product-variation-display.component.html
Labels: enhancement

#1613 fix: product variation availability for more than 2 variation attributes combinations
  src/app/core/models/product-variation/product-variation.helper.spec.ts
  src/app/core/models/product-variation/product-variation.helper.ts
Labels: bug, has conflicts

#1617 fix: suppress validation error after data creation in dialogs
  projects/requisition-management/src/app/pages/requisition-detail/requisition-reject-dialog/requisition-reject-dialog.component.ts
  src/app/extensions/order-templates/shared/order-template-preferences-dialog/order-template-preferences-dialog.component.ts
  src/app/extensions/wishlists/shared/wishlist-preferences-dialog/wishlist-preferences-dialog.component.ts
Labels: bug:minor

#1571 feat: order list filtering
  docs/guides/formly.md
  src/app/core/facades/account.facade.ts
  src/app/core/models/order-list-query/order-list-query.model.ts
  src/app/core/services/order/order.service.spec.ts
  src/app/core/services/order/order.service.ts
  src/app/core/store/customer/orders/orders.actions.ts
  src/app/core/store/customer/orders/orders.effects.spec.ts
  src/app/core/store/customer/orders/orders.effects.ts
  src/app/core/store/customer/orders/orders.reducer.ts
  src/app/core/store/customer/orders/orders.selectors.spec.ts
  src/app/core/store/customer/orders/orders.selectors.ts
  src/app/pages/account-order-history/account-order-filters/account-order-filters.component.html
  src/app/pages/account-order-history/account-order-filters/account-order-filters.component.spec.ts
  src/app/pages/account-order-history/account-order-filters/account-order-filters.component.ts
  src/app/pages/account-order-history/account-order-history-page.component.html
  src/app/pages/account-order-history/account-order-history-page.component.spec.ts
  src/app/pages/account-order-history/account-order-history-page.component.ts
  src/app/pages/account-order-history/account-order-history-page.module.ts
  src/app/shared/components/order/order-widget/order-widget.component.ts
  src/app/shared/formly/dev/testing/formly-testing.module.ts
  src/app/shared/formly/extensions/translate-placeholder.extension.ts
  src/app/shared/formly/types/date-picker-field/date-picker-field.component.ts
  src/app/shared/formly/types/date-range-picker-field/date-range-picker-field.component.html
  src/app/shared/formly/types/date-range-picker-field/date-range-picker-field.component.scss
  src/app/shared/formly/types/date-range-picker-field/date-range-picker-field.component.spec.ts
  src/app/shared/formly/types/date-range-picker-field/date-range-picker-field.component.ts
  src/app/shared/formly/types/types.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1555 fix: infinite loop can occur in the mapping of the content page tree
  src/app/core/models/content-page-tree-view/content-page-tree-view.model.spec.ts
  src/app/core/models/content-page-tree-view/content-page-tree-view.model.ts
  src/app/core/models/content-page-tree/content-page-tree.mapper.ts
Labels: bug

#1619 fix: confirming cookie preferences removes punchout related cookies
  docs/guides/cookie-banner.png
  docs/guides/cookie-consent.md
  docs/guides/cookie-preferences.png
  src/environments/environment.model.ts
Labels: bug

#1620 deps: update dependencies + fix vulnerability
  package-lock.json
  package.json
Labels: dependencies

#1615 fix: wrong scrolling behavior
  src/app/core/directives/scroll.directive.ts
  src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.html
  src/app/shared/components/basket/basket-validation-results/basket-validation-results.component.ts
Labels: bug
