Repository intershop/intershop-pwa, pull requests merged in 2024-04, with the labels that each got.

#1623 docs: update default icmBaseUrl in doc files
  docs/guides/customizations.md
  docs/guides/getting-started.md
Labels: documentation

#1624 feat: exclusive ICM url for SSR process
  docs/guides/ssr-startup.md
  scripts/icm-cache.js
  src/app/core/store/core/configuration/configuration.selectors.ts
Labels: enhancement

#1632 feat(nginx): make `worker_processes` and `worker_connections` configurable
  docs/guides/nginx-startup.md
  nginx/Dockerfile
  nginx/docker-entrypoint.d/40-gomplate.sh
  nginx/nginx.conf.tmpl
Labels: enhancement

#1622 fix: save address doctor configuration in the ngrx store
  docs/guides/address-doctor.md
  src/app/extensions/address-doctor/exports/address-doctor-exports.module.ts
  src/app/extensions/address-doctor/services/address-doctor/address-doctor.service.spec.ts
  src/app/extensions/address-doctor/services/address-doctor/address-doctor.service.ts
  src/app/extensions/address-doctor/store/address-doctor-store.module.ts
  src/app/extensions/address-doctor/store/address-doctor-store.ts
  src/app/extensions/address-doctor/store/address-doctor/address-doctor.actions.ts
  src/app/extensions/address-doctor/store/address-doctor/address-doctor.effects.spec.ts
  src/app/extensions/address-doctor/store/address-doctor/address-doctor.effects.ts
  src/app/extensions/address-doctor/store/address-doctor/address-doctor.reducer.ts
  src/app/extensions/address-doctor/store/address-doctor/address-doctor.selectors.spec.ts
  src/app/extensions/address-doctor/store/address-doctor/address-doctor.selectors.ts
  src/app/extensions/address-doctor/store/address-doctor/index.ts
Labels: bug

#1639 feat: use template for environment.development.ts if avalable
  docs/guides/development.md
  scripts/init-development-environment.js
Labels: enhancement, nice to have

#1636 refactor: consolidate feature toggle imports
  .eslintrc.json
  src/app/core/configurations/configuration.meta.ts
  src/app/core/directives/feature-toggle.directive.spec.ts
  src/app/core/directives/feature-toggle.directive.ts
  src/app/core/directives/not-feature-toggle.directive.spec.ts
  src/app/core/directives/not-feature-toggle.directive.ts
  src/app/core/feature-toggle.module.ts
  src/app/core/guards/feature-toggle.guard.spec.ts
  src/app/core/guards/feature-toggle.guard.ts
  src/app/core/identity-provider/identity-provider.factory.ts
  src/app/core/interceptors/icm-compatibility.interceptor.ts
  src/app/core/pipes/feature-toggle.pipe.spec.ts
  src/app/core/pipes/feature-toggle.pipe.ts
  src/app/core/store/core/configuration/configuration.effects.ts
  src/app/core/store/core/configuration/configuration.reducer.ts
  src/app/core/store/core/server-config/server-config.effects.ts
  src/app/core/utils/feature-event/feature-event.service.ts
  src/app/core/utils/module-loader/module-loader.service.ts
  src/app/pages/account/account-navigation/account-navigation.component.ts
  src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
Labels: refactoring

#1611 refactor: remove unused RouterModule exports
  projects/organization-management/src/app/pages/organization-management-routing.module.ts
  projects/requisition-management/src/app/pages/requisition-management-routing.module.ts
  schematics/src/extension/files/__name@dasherize__/pages/__name@dasherize__-routing.module.ts.template
  src/app/extensions/compare/pages/compare-routing.module.ts
  src/app/extensions/contact-us/pages/contact-us-routing.module.ts
  src/app/extensions/order-templates/pages/order-templates-routing.module.ts
  src/app/extensions/product-notifications/pages/product-notifications-routing.module.ts
  src/app/extensions/punchout/pages/punchout-account-routing.module.ts
  src/app/extensions/punchout/pages/punchout-routing.module.ts
  src/app/extensions/quickorder/pages/quickorder-routing.module.ts
  src/app/extensions/quoting/pages/quoting-routing.module.ts
  src/app/extensions/recently/pages/recently-routing.module.ts
  src/app/extensions/store-locator/pages/store-locator-routing.module.ts
  src/app/extensions/tacton/pages/tacton-routing.module.ts
  src/app/extensions/wishlists/pages/wishlists-routing.module.ts
  src/app/pages/account-order-history/account-order-history-page.module.ts
Labels: refactoring

#1637 feat: set default theme also as default for override schematic
  schematics/customization/add/index.js
  schematics/src/helpers/override/factory_spec.ts
Labels: enhancement, nice to have

#1635 fix: disable hydration HTTP transfer cache
  src/app/app.module.ts
Labels: bug, regression
