Repository intershop/intershop-pwa, pull requests merged in 2025-06, with the labels that each got.

#1813 docs: migration guide review
  CHANGELOG.md
  docs/guides/migrations.md
Labels: documentation

#1843 fix(accessibility): tab focus outline for carousel (#1826, #1843)
  src/styles/components/carousel/carousel.scss
  src/styles/global/global.scss
Labels: accessibility

#1844 fix(accessibility): provide legends for fieldsets in forms
  docs/guides/formly.md
  projects/organization-management/src/app/components/cost-center-form/cost-center-form.component.ts
  projects/organization-management/src/app/components/user-budget-form/user-budget-form.component.ts
  projects/organization-management/src/app/components/user-profile-form/user-profile-form.component.ts
  src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.ts
  src/app/pages/account-order-history/account-order-filters/account-order-filters.component.ts
  src/app/pages/checkout-address/formly/components/checkout-address-anonymous-form/checkout-address-anonymous-form.component.ts
  src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.spec.ts
  src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
  src/app/shared/formly-address-forms/components/formly-address-extension-form/formly-address-extension-form.component.ts
  src/app/shared/formly-address-forms/components/formly-address-form/formly-address-form.component.spec.ts
  src/app/shared/formly-address-forms/components/formly-address-form/formly-address-form.component.ts
  src/app/shared/formly-address-forms/configurations/address-form.configuration.ts
  src/app/shared/formly/types/fieldset-field/fieldset-field.component.html
  src/app/shared/formly/types/fieldset-field/fieldset-field.component.ts
  src/app/shared/formly/wrappers/horizontal-checkbox-wrapper/horizontal-checkbox-wrapper.component.html
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: bug, refactoring, accessibility

#1851 feat(accessibility): screenreader announcements for checkout payment instrument form (#1846, #1851)
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.spec.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement, accessibility

#1852 fix: checkout "add payment instrument" submit is called twice (#1850, #1852)
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.html
Labels: bug, accessibility

#1853 feat(accessibility): wrap category navigation into `<nav>` element (#1834, #1853)
  src/app/pages/category/category-categories/category-categories.component.html
  src/app/pages/category/category-products/category-products.component.html
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement, accessibility

#1858 feat(accessibility): indicate which categories/filters are selected (#1832, #1858)
  src/app/pages/category/category-navigation/category-navigation.component.html
  src/app/pages/category/category-navigation/category-navigation.component.spec.ts
  src/app/shared/components/filter/filter-swatch-images/__snapshots__/filter-swatch-images.component.spec.ts.snap
  src/app/shared/components/filter/filter-swatch-images/filter-swatch-images.component.html
  src/app/shared/components/filter/filter-text/filter-text.component.html
  src/app/shared/components/filter/filter-text/filter-text.component.spec.ts
Labels: enhancement, accessibility

#1859 test: add `@babel/plugin-proposal-decorators` to dev dependencies (#1857, #1859)
  package-lock.json
  package.json
Labels: enhancement

#1860 fix(accessibility): valid `aria-controls`-id's for collapsible filters (#1837, #1860)
  src/app/shared/components/filter/filter-checkbox/__snapshots__/filter-checkbox.component.spec.ts.snap
  src/app/shared/components/filter/filter-checkbox/filter-checkbox.component.html
  src/app/shared/components/filter/filter-checkbox/filter-checkbox.component.spec.ts
  src/app/shared/components/filter/filter-checkbox/filter-checkbox.component.ts
  src/app/shared/components/filter/filter-collapsible/filter-collapsible.component.html
  src/app/shared/components/filter/filter-collapsible/filter-collapsible.component.spec.ts
  src/app/shared/components/filter/filter-collapsible/filter-collapsible.component.ts
  src/app/shared/components/filter/filter-dropdown/filter-dropdown.component.html
  src/app/shared/components/filter/filter-dropdown/filter-dropdown.component.ts
  src/app/shared/components/filter/filter-navigation-sidebar/filter-navigation-sidebar.component.html
  src/app/shared/components/filter/filter-swatch-images/__snapshots__/filter-swatch-images.component.spec.ts.snap
  src/app/shared/components/filter/filter-swatch-images/filter-swatch-images.component.html
  src/app/shared/components/filter/filter-swatch-images/filter-swatch-images.component.spec.ts
  src/app/shared/components/filter/filter-swatch-images/filter-swatch-images.component.ts
  src/app/shared/components/filter/filter-text/filter-text.component.html
  src/app/shared/components/filter/filter-text/filter-text.component.spec.ts
  src/app/shared/components/filter/filter-text/filter-text.component.ts
Labels: bug, enhancement, accessibility
