Repository intershop/intershop-pwa, pull requests merged in 2025-01, with the labels that each got.

#1590 feat: wishlist sharing
  e2e/cypress/e2e/pages/account/wishlists-details.page.ts
  e2e/cypress/e2e/specs/extras/wishlists-management.b2c.e2e-spec.ts
  src/app/app.module.ts
  src/app/core/icon.module.ts
  src/app/extensions/wishlists/facades/wishlists.facade.ts
  src/app/extensions/wishlists/guards/fetch-shared-wishlist.guard.ts
  src/app/extensions/wishlists/models/wishlist-sharing/wishlist-sharing.model.ts
  src/app/extensions/wishlists/models/wishlist/wishlist.interface.ts
  src/app/extensions/wishlists/models/wishlist/wishlist.mapper.spec.ts
  src/app/extensions/wishlists/models/wishlist/wishlist.mapper.ts
  src/app/extensions/wishlists/models/wishlist/wishlist.model.ts
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.html
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.component.ts
  src/app/extensions/wishlists/pages/account-wishlist-detail/account-wishlist-detail-page.module.ts
  src/app/extensions/wishlists/pages/account-wishlist/account-wishlist-list/account-wishlist-list.component.html
  src/app/extensions/wishlists/pages/shared-wishlist/shared-wishlist-page.component.html
  src/app/extensions/wishlists/pages/shared-wishlist/shared-wishlist-page.component.spec.ts
  src/app/extensions/wishlists/pages/shared-wishlist/shared-wishlist-page.component.ts
  src/app/extensions/wishlists/pages/shared-wishlist/shared-wishlist-page.module.ts
  src/app/extensions/wishlists/pages/wishlist-sharing-routing.module.ts
  src/app/extensions/wishlists/services/wishlist/wishlist.service.spec.ts
  src/app/extensions/wishlists/services/wishlist/wishlist.service.ts
  src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.ts
  src/app/extensions/wishlists/shared/wishlist-line-item/wishlist-line-item.component.html
  src/app/extensions/wishlists/shared/wishlist-line-item/wishlist-line-item.component.spec.ts
  src/app/extensions/wishlists/shared/wishlist-line-item/wishlist-line-item.component.ts
  src/app/extensions/wishlists/shared/wishlist-sharing-dialog/wishlist-sharing-dialog.component.html
  src/app/extensions/wishlists/shared/wishlist-sharing-dialog/wishlist-sharing-dialog.component.spec.ts
  src/app/extensions/wishlists/shared/wishlist-sharing-dialog/wishlist-sharing-dialog.component.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.actions.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.spec.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.effects.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.reducer.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.selectors.spec.ts
  src/app/extensions/wishlists/store/wishlist/wishlist.selectors.ts
  src/app/extensions/wishlists/wishlists.module.ts
  src/app/shared/forms/validators/special-validators.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: feature

#1732 fix: SSR rendered pages with status code 404 or 503 should be returned
  nginx/features/cache.conf
Labels: bug

#1734 ci: fix demoserver workflow
  .github/scripts/docker-compose.py
  .github/scripts/requirements.txt
Labels: dependencies

#1740 deps: fix vulnerabilities + update dependencies
  .cspell.json
  .nsprc
  docs/guides/code-documentation.md
  docs/guides/mocking-rest-calls.md
  docs/guides/nginx-startup.md
  package-lock.json
  package.json
  src/app/extensions/sentry/store/sentry-config/sentry-config.effects.ts
  src/app/extensions/store-locator/services/stores-map/stores-map.service.ts
Labels: dependencies

#1744 chore: configure cspell to English only spell checking and remove unnecessary dependencies
  .cspell.json
  .vscode/intershop.txt
  package-lock.json
  package.json
  scripts/update-pwa.js
  src/app/core/utils/dev/basket-mock-data.ts
  src/app/shared/components/order/order-widget/order-widget.component.ts
  src/assets/i18n/de_DE.json
Labels: dependencies

#1743 fix: fetch updated redirect url before redirecting
  src/app/core/facades/checkout.facade.ts
  src/app/core/services/payment/payment.service.spec.ts
  src/app/core/services/payment/payment.service.ts
  src/app/core/store/customer/basket/basket-payment.effects.spec.ts
  src/app/core/store/customer/basket/basket-payment.effects.ts
  src/app/core/store/customer/basket/basket.actions.ts
  src/app/core/store/customer/basket/basket.reducer.ts
  src/app/pages/checkout-payment/checkout-payment-page.component.ts
  src/app/pages/checkout-payment/checkout-payment/checkout-payment.component.ts
Labels: bug

#1746 fix: use correct punchout REST API headers for cXML and OCI punchout
  src/app/extensions/punchout/services/punchout/punchout.service.ts
Labels: refactoring
