Repository intershop/intershop-pwa, pull requests merged in 2025-03, with the labels that each got.

#1770 feat(accessibility): sticky header feature toggle
  docs/concepts/configuration.md
  docs/guides/migrations.md
  src/app/core/store/core/viewconf/viewconf.effects.ts
  src/app/core/store/core/viewconf/viewconf.integration.spec.ts
  src/environments/environment.model.ts
Labels: feature, accessibility

#1775 deps: update vulnerable babel dependencies
  angular.json
  package-lock.json
Labels: dependencies

#1768 docs: provide some guidance to aproach PCI DSS 4
  .vscode/intershop.txt
  docs/README.md
  docs/guides/pci-dss-4.md
Labels: documentation

#1752 feat(accessibility): add password reveal button
  .vscode/intershop.txt
  docs/guides/formly.md
  docs/guides/migrations.md
  src/app/core/configurations/injection-keys.ts
  src/app/core/directives.module.ts
  src/app/core/directives/focus-outside.directive.ts
  src/app/core/icon.module.ts
  src/app/extensions/punchout/shared/punchout-user-form/punchout-user-form.component.ts
  src/app/pages/account-profile-password/account-profile-password/account-profile-password.component.ts
  src/app/pages/forgot-password/update-password-form/update-password-form.component.ts
  src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
  src/app/shared/components/login/login-form/login-form.component.ts
  src/app/shared/formly/components/validation-icons/validation-icons.component.html
  src/app/shared/formly/dev/testing/formly-testing.module.ts
  src/app/shared/formly/types/password-field/password-field.component.html
  src/app/shared/formly/types/password-field/password-field.component.scss
  src/app/shared/formly/types/password-field/password-field.component.spec.ts
  src/app/shared/formly/types/password-field/password-field.component.ts
  src/app/shared/formly/types/types.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement, refactoring, accessibility

#1700 docs: update and extend accessibility documentation
  .vscode/intershop.txt
  docs/README.md
  docs/guides/accessibility-easy-check.md
  docs/guides/accessibility.md
  docs/guides/migrations.md
Labels: documentation, accessibility

#1782 docs: review changes after PWA 6.0.0 release
  docs/guides/formly.md
  docs/guides/forms.md
  docs/guides/migrations.md
Labels: documentation

#1783 docs: add ToC to concepts and guides
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  .vscode/settings.json
  docs/concepts/authentication.md
  docs/concepts/captcha.md
  docs/concepts/cms-integration.md
  docs/concepts/configuration.md
  docs/concepts/deploy-url.md
  docs/concepts/deployment-angular.md
  docs/concepts/hybrid-approach.md
  docs/concepts/localization.md
  docs/concepts/logging.md
  docs/concepts/multi-site-handling.md
  docs/concepts/progressive-web-app.md
  docs/concepts/project-structure.md
  docs/concepts/pwa-building-blocks.md
  docs/concepts/search-engine-optimization.md
  docs/concepts/state-management.md
  docs/concepts/styling-behavior.md
  docs/concepts/testing.md
  docs/concepts/url-rewriting.md
  docs/guides/accessibility.md
  docs/guides/address-doctor.md
  docs/guides/angular-change-detection.md
  docs/guides/angular-component-development.md
  docs/guides/authentication_co_browse.md
  docs/guides/authentication_icm.md
  docs/guides/authentication_punchout.md
  docs/guides/authentication_sso.md
  docs/guides/code-documentation.md
  docs/guides/continuous-integration.md
  docs/guides/cookie-consent.md
  docs/guides/copilot.md
  docs/guides/core-web-vitals.md
  docs/guides/customizations.md
  docs/guides/development.md
  docs/guides/eslint.md
  docs/guides/field-library.md
  docs/guides/formly.md
  docs/guides/forms.md
  docs/guides/getting-started.md
  docs/guides/hybrid-approach-icm-url-rewriting.md
  docs/guides/mocking-rest-calls.md
  docs/guides/multi-site-configurations.md
  docs/guides/newsletter-subscription.md
  docs/guides/nginx-startup.md
  docs/guides/optimizations.md
  docs/guides/product-context.md
  docs/guides/prometheus-monitoring.md
  docs/guides/propagating-environment-variables.md
  docs/guides/ssr-startup.md
  docs/guides/state-management.md
  docs/guides/store-locator.md
  docs/guides/tacton-product-configuration.md
  docs/guides/testing-cypress.md
  docs/guides/testing-jest.md
  docs/guides/themes.md
  docs/guides/updating-pwa.md
Labels: documentation
