Repository intershop/intershop-pwa, pull requests merged in 2025-07, with the labels that each got.

#1809 fix: No error message for unchecked terms & conditions in registration form
  src/app/pages/registration/services/registration-form-configuration/registration-form-configuration.service.ts
Labels: bug

#1869 fix(accessibility): use skip content link component (#1824, #1838)
  src/app/pages/account/account-page.component.html
Labels: accessibility

#1866 fix: Order history filters open unintended
  src/app/pages/account-order-history/account-order-filters/account-order-filters.component.ts
Labels: bug

#1871 docs: improve SPARQUE.AI documentation
  docs/guides/sparque-ai.md
Labels: documentation

#1776 feat: order history pagination instead of "load more"
  docs/guides/migrations.md
  src/app/core/facades/account.facade.ts
  src/app/core/models/order-list-query/order-list-query.model.ts
  src/app/core/models/order/order.interface.ts
  src/app/core/models/order/order.mapper.spec.ts
  src/app/core/models/order/order.mapper.ts
  src/app/core/models/order/order.model.ts
  src/app/core/models/paging-info/paging-info.model.ts
  src/app/core/services/order/order.service.spec.ts
  src/app/core/services/order/order.service.ts
  src/app/core/store/customer/orders/orders.actions.ts
  src/app/core/store/customer/orders/orders.effects.spec.ts
  src/app/core/store/customer/orders/orders.effects.ts
  src/app/core/store/customer/orders/orders.reducer.ts
  src/app/core/store/customer/orders/orders.selectors.spec.ts
  src/app/core/store/customer/orders/orders.selectors.ts
  src/app/pages/account-order-history/account-order-history-page.component.html
  src/app/pages/account-order-history/account-order-history-page.component.ts
  src/app/shared/shared.module.ts
  src/assets/i18n/de_DE.json
  src/assets/i18n/en_US.json
  src/assets/i18n/fr_FR.json
Labels: enhancement

#1879 docs: update project description in readme
  README.md
Labels: documentation
